// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package paygentic

// Generated from OpenAPI doc version 0.1.0 and generator version 2.881.4

import (
	"context"
	"fmt"
	"github.com/paygentic/sdk-go/internal/config"
	"github.com/paygentic/sdk-go/internal/hooks"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
	"github.com/paygentic/sdk-go/retry"
	"net/http"
	"time"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	// Production API
	"https://api.paygentic.io",
	// Sandbox API
	"https://api.sandbox.paygentic.io",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// Client - Paygentic API: The Paygentic API provides billing infrastructure for usage-based and subscription monetization — customers, subscriptions, usage metering, invoicing, entitlements, and payments.
//
// See the [Quickstart](https://docs.paygentic.io/getting-started/quickstart) to go from zero to billing in a handful of steps.
type Client struct {
	SDKVersion      string
	BillableMetrics *BillableMetrics
	// A `Customer` is an entity connected to a `Merchant` via a `Subscription`. This represents the merchant-facing perspective of `Consumers` who purchase their `Products`.
	Customers    *Customers
	Entitlements *Entitlements
	// A `Feature` represents a specific capability or functionality provided by a `Product`. Features can be metered (usage-based), static (fixed allocation), or boolean (enabled/disabled).
	Features *Features
	// A `Fee` defines a recurring or one-time charge tied to a `Product`. Fees are linked to prices, and cadence is defined on the Price.
	Fees *Fees
	// A `Plan` links a collection of `Prices` to a `Product`. It functions as a pricing structure document for a particular feature set or service offering.
	Plans *Plans
	// A `Price` determines the monetary value for a single unit of a `Billable Metric`. Prices are exclusively grouped within a `Plan`.
	Prices *Prices
	// A `Product` is an offering sold by a `Merchant`. It includes product metadata like title, summary, and pricing details. `Plans`, `Prices`, and `Subscriptions` are all associated with products.
	Products *Products
	// A `Source` is an external data provider capable of automatically creating usage events. Configuration occurs at the plan level, enabling data retrieval from third-party platforms such as Stripe to produce billable events.
	Sources *Sources
	// A `Subscription` is a customer's commitment to purchase a `Product` following the terms of a `Plan` and its linked `Prices`.
	Subscriptions *Subscriptions
	// A `User` is an entity granted access to an Organization's resources. All operations are performed by users.
	Users *Users
	// Invoice V2 operations supporting billing cycles organized by time periods. Warning: v0 invoice endpoints are no longer supported.
	InvoicesV2 *InvoicesV2
	// Create and manage one-off payments. A payment represents a single charge that a merchant wants to collect from a customer.
	Payments *Payments
	// Ingest raw metering events that are processed by the meters service.
	Events *Events
	// A Cost represents the operational or infrastructure expense of serving customers for a given product. Costs are metered (driven by event-based usage) and are tracked in parallel with billable metrics to give merchants visibility into both revenue and cost per customer.
	Costs *Costs
	// Revenue data from invoices and payments
	Revenue *Revenue
	// Test clocks provide programmable time control to simulate subscription and billing scenarios during testing.
	TestClocks *TestClocks

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*Client)

// WithServerURL allows providing an alternative server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *Client) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *Client) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *Client) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *Client) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(bearerAuth string) SDKOption {
	return func(sdk *Client) {
		security := components.Security{BearerAuth: &bearerAuth}
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(&security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (components.Security, error)) SDKOption {
	return func(sdk *Client) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *Client) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *Client) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *Client {
	sdk := &Client{
		SDKVersion: "0.2.0",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:  "speakeasy-sdk/go 0.2.0 2.881.4 0.1.0 github.com/paygentic/sdk-go",
			ServerList: ServerList,
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	if sdk.sdkConfiguration.Security == nil {
		var envVarSecurity components.Security
		if utils.PopulateSecurityFromEnv(&envVarSecurity) {
			sdk.sdkConfiguration.Security = utils.AsSecuritySource(envVarSecurity)
		}
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.BillableMetrics = newBillableMetrics(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Customers = newCustomers(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Entitlements = newEntitlements(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Features = newFeatures(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Fees = newFees(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Plans = newPlans(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Prices = newPrices(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Products = newProducts(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Sources = newSources(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Subscriptions = newSubscriptions(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Users = newUsers(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.InvoicesV2 = newInvoicesV2(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Payments = newPayments(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Events = newEvents(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Costs = newCosts(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Revenue = newRevenue(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.TestClocks = newTestClocks(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
