// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/models/components"
)

type BatchCreateUsageEventsRequest struct {
	Events []components.CreateUsageEventRequest `json:"events"`
}

func (b *BatchCreateUsageEventsRequest) GetEvents() []components.CreateUsageEventRequest {
	if b == nil {
		return []components.CreateUsageEventRequest{}
	}
	return b.Events
}
