// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type BulkRejectSourceEventsRequestBody struct {
	// IDs of events to reject
	EventIds []string `json:"eventIds"`
}

func (b *BulkRejectSourceEventsRequestBody) GetEventIds() []string {
	if b == nil {
		return []string{}
	}
	return b.EventIds
}

type BulkRejectSourceEventsRequest struct {
	ID   string                            `pathParam:"style=simple,explode=false,name=id"`
	Body BulkRejectSourceEventsRequestBody `request:"mediaType=application/json"`
}

func (b *BulkRejectSourceEventsRequest) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BulkRejectSourceEventsRequest) GetBody() BulkRejectSourceEventsRequestBody {
	if b == nil {
		return BulkRejectSourceEventsRequestBody{}
	}
	return b.Body
}

// BulkRejectSourceEventsResponse - Bulk rejection results
type BulkRejectSourceEventsResponse struct {
	// Number of rejected events
	Rejected *int64 `json:"rejected,omitzero"`
}

func (b *BulkRejectSourceEventsResponse) GetRejected() *int64 {
	if b == nil {
		return nil
	}
	return b.Rejected
}
