// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/internal/utils"
)

type BulkApproveSourceEventsRequestBody struct {
	// IDs of events to approve
	EventIds []string `json:"eventIds"`
}

func (b *BulkApproveSourceEventsRequestBody) GetEventIds() []string {
	if b == nil {
		return []string{}
	}
	return b.EventIds
}

type BulkApproveSourceEventsRequest struct {
	ID   string                             `pathParam:"style=simple,explode=false,name=id"`
	Body BulkApproveSourceEventsRequestBody `request:"mediaType=application/json"`
}

func (b *BulkApproveSourceEventsRequest) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BulkApproveSourceEventsRequest) GetBody() BulkApproveSourceEventsRequestBody {
	if b == nil {
		return BulkApproveSourceEventsRequestBody{}
	}
	return b.Body
}

type Failed struct {
	ID    *string `json:"id,omitzero"`
	Error *string `json:"error,omitzero"`
}

func (f *Failed) GetID() *string {
	if f == nil {
		return nil
	}
	return f.ID
}

func (f *Failed) GetError() *string {
	if f == nil {
		return nil
	}
	return f.Error
}

type BulkApproveSourceEventsDetails struct {
	// IDs of successfully processed events
	Processed []string `json:"processed,omitzero"`
	// Failed events with error messages
	Failed []Failed `json:"failed,omitzero"`
}

func (b BulkApproveSourceEventsDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BulkApproveSourceEventsDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BulkApproveSourceEventsDetails) GetProcessed() []string {
	if b == nil {
		return nil
	}
	return b.Processed
}

func (b *BulkApproveSourceEventsDetails) GetFailed() []Failed {
	if b == nil {
		return nil
	}
	return b.Failed
}

// BulkApproveSourceEventsResponse - Bulk approval results
type BulkApproveSourceEventsResponse struct {
	// Number of successfully approved events
	Processed *int64 `json:"processed,omitzero"`
	// Number of events that failed to process
	Failed  *int64                          `json:"failed,omitzero"`
	Details *BulkApproveSourceEventsDetails `json:"details,omitzero"`
}

func (b BulkApproveSourceEventsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BulkApproveSourceEventsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BulkApproveSourceEventsResponse) GetProcessed() *int64 {
	if b == nil {
		return nil
	}
	return b.Processed
}

func (b *BulkApproveSourceEventsResponse) GetFailed() *int64 {
	if b == nil {
		return nil
	}
	return b.Failed
}

func (b *BulkApproveSourceEventsResponse) GetDetails() *BulkApproveSourceEventsDetails {
	if b == nil {
		return nil
	}
	return b.Details
}
