// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
	"github.com/paygentic/sdk-go/optionalnullable"
)

// CreatePriceModel - Pricing calculation model. Required for billable metrics, optional for fees (defaults to 'standard').
type CreatePriceModel string

const (
	CreatePriceModelStandard   CreatePriceModel = "standard"
	CreatePriceModelDynamic    CreatePriceModel = "dynamic"
	CreatePriceModelVolume     CreatePriceModel = "volume"
	CreatePriceModelPercentage CreatePriceModel = "percentage"
)

func (e CreatePriceModel) ToPointer() *CreatePriceModel {
	return &e
}
func (e *CreatePriceModel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "standard":
		fallthrough
	case "dynamic":
		fallthrough
	case "volume":
		fallthrough
	case "percentage":
		*e = CreatePriceModel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreatePriceModel: %v", v)
	}
}

// CreatePricePaymentTerm - Billing timing preference. For billable metrics: 'instant' (charges immediately) or 'in_arrears' (charges at period end). For fees: 'in_advance' (charges upfront) or 'in_arrears' (charges at period end).
type CreatePricePaymentTerm string

const (
	CreatePricePaymentTermInstant   CreatePricePaymentTerm = "instant"
	CreatePricePaymentTermInArrears CreatePricePaymentTerm = "in_arrears"
	CreatePricePaymentTermInAdvance CreatePricePaymentTerm = "in_advance"
)

func (e CreatePricePaymentTerm) ToPointer() *CreatePricePaymentTerm {
	return &e
}
func (e *CreatePricePaymentTerm) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "instant":
		fallthrough
	case "in_arrears":
		fallthrough
	case "in_advance":
		*e = CreatePricePaymentTerm(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreatePricePaymentTerm: %v", v)
	}
}

type CreatePriceRequest struct {
	// Unique identifier for a billable metric
	BillableMetricID *string `json:"billableMetricId,omitzero"`
	// The unique identifier for the fee referred to by this price. Either billableMetricId or feeId must be provided.
	FeeID *string `json:"feeId,omitzero"`
	// Pricing calculation model. Required for billable metrics, optional for fees (defaults to 'standard').
	Model *CreatePriceModel `json:"model,omitzero"`
	// Line item label shown on customer invoices. Sample values: 'Claude Token Consumption', 'Storage Usage (GB)', 'Inference API Calls', 'Image Generation Count', 'Training Compute Hours', 'Data Transfer (TB)'
	InvoiceDisplayName string `json:"invoiceDisplayName"`
	// Billing timing preference. For billable metrics: 'instant' (charges immediately) or 'in_arrears' (charges at period end). For fees: 'in_advance' (charges upfront) or 'in_arrears' (charges at period end).
	PaymentTerm CreatePricePaymentTerm `json:"paymentTerm"`
	// ISO 8601 duration for recurring charges (e.g., 'P1M' for monthly, 'P1Y' for yearly) or 'P0D' for one-time charges. Required for fees, optional for billable metrics. Sample values: 'P0D' for one-time, 'P1M' for monthly recurring, 'P1Y' for yearly recurring
	BillingCadence optionalnullable.OptionalNullable[string] `json:"billingCadence,omitzero"`
	Properties     components.PricePropertiesUnion           `json:"properties"`
	Feature        *components.PriceFeatureInput             `json:"feature,omitzero"`
	// When true, grants applied to a subscription will discount usage charged by this price. Only supported for standard metered prices.
	GrantDiscountEnabled *bool `default:"false" json:"grantDiscountEnabled"`
}

func (c CreatePriceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePriceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatePriceRequest) GetBillableMetricID() *string {
	if c == nil {
		return nil
	}
	return c.BillableMetricID
}

func (c *CreatePriceRequest) GetFeeID() *string {
	if c == nil {
		return nil
	}
	return c.FeeID
}

func (c *CreatePriceRequest) GetModel() *CreatePriceModel {
	if c == nil {
		return nil
	}
	return c.Model
}

func (c *CreatePriceRequest) GetInvoiceDisplayName() string {
	if c == nil {
		return ""
	}
	return c.InvoiceDisplayName
}

func (c *CreatePriceRequest) GetPaymentTerm() CreatePricePaymentTerm {
	if c == nil {
		return CreatePricePaymentTerm("")
	}
	return c.PaymentTerm
}

func (c *CreatePriceRequest) GetBillingCadence() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.BillingCadence
}

func (c *CreatePriceRequest) GetProperties() components.PricePropertiesUnion {
	if c == nil {
		return components.PricePropertiesUnion{}
	}
	return c.Properties
}

func (c *CreatePriceRequest) GetFeature() *components.PriceFeatureInput {
	if c == nil {
		return nil
	}
	return c.Feature
}

func (c *CreatePriceRequest) GetGrantDiscountEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.GrantDiscountEnabled
}
