// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/internal/utils"
)

type CreateItemRequest struct {
	MerchantID string `json:"merchantId"`
	// Canonical sellable name for the Item
	Name string `json:"name"`
	// Unique identifier for a product
	CatalogID *string `json:"catalogId,omitzero"`
	// Optional key-value metadata
	Metadata map[string]any `json:"metadata,omitzero"`
}

func (c CreateItemRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateItemRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateItemRequest) GetMerchantID() string {
	if c == nil {
		return ""
	}
	return c.MerchantID
}

func (c *CreateItemRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateItemRequest) GetCatalogID() *string {
	if c == nil {
		return nil
	}
	return c.CatalogID
}

func (c *CreateItemRequest) GetMetadata() map[string]any {
	if c == nil {
		return nil
	}
	return c.Metadata
}
