// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

type CreateTestClockRequest struct {
	// Initial time for the test clock (defaults to current time). Cannot be more than 1 hour in the past to prevent accidental backdating. The 1-hour buffer accounts for clock drift and network delays.
	CurrentTime *time.Time `json:"currentTime,omitzero"`
	// Description of the test clock's purpose
	Description *string `json:"description,omitzero"`
	// The merchant organization that will own this test clock. If not provided, will be extracted from authenticated user's context.
	MerchantID *string `json:"merchantId,omitzero"`
	// Name of the test clock
	Name *string `json:"name,omitzero"`
}

func (c CreateTestClockRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTestClockRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateTestClockRequest) GetCurrentTime() *time.Time {
	if c == nil {
		return nil
	}
	return c.CurrentTime
}

func (c *CreateTestClockRequest) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateTestClockRequest) GetMerchantID() *string {
	if c == nil {
		return nil
	}
	return c.MerchantID
}

func (c *CreateTestClockRequest) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}
