// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/models/components"
)

type CreateEntitlementGrantRequest struct {
	// The unique identifier of the entitlement to grant credits to.
	EntitlementID string                        `pathParam:"style=simple,explode=false,name=entitlementId"`
	Body          components.CreateGrantRequest `request:"mediaType=application/json"`
}

func (c *CreateEntitlementGrantRequest) GetEntitlementID() string {
	if c == nil {
		return ""
	}
	return c.EntitlementID
}

func (c *CreateEntitlementGrantRequest) GetBody() components.CreateGrantRequest {
	if c == nil {
		return components.CreateGrantRequest{}
	}
	return c.Body
}
