// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/internal/utils"
)

// Metadata - Optional key-value metadata storage for product information. Sample values: {"category": "ai_services", "tier": "enterprise"}, {"region": "global", "support_level": "premium"}
type Metadata struct {
}

type CreateProductRequest struct {
	// Customer-visible product summary explaining capabilities and use cases. Sample values: 'Enterprise access to advanced language models for natural language tasks', 'Scalable data warehousing with real-time query capabilities', 'On-demand AI image generation using diffusion models', 'Distributed computing infrastructure for training deep learning models', 'High-performance vector similarity search database', 'Production-ready speech-to-text conversion service'
	Description string `json:"description"`
	// Unique identifier for an organization
	MerchantID string `json:"merchantId"`
	// Optional key-value metadata storage for product information. Sample values: {"category": "ai_services", "tier": "enterprise"}, {"region": "global", "support_level": "premium"}
	Metadata *Metadata `json:"metadata,omitzero"`
	// Customer-facing product title shown in invoices and dashboards. Sample values: 'Large Language Model Service', 'Cloud Data Warehouse', 'AI Image Creator', 'Neural Network Training Platform', 'Vector Database', 'Speech Recognition API'
	Name string `json:"name"`
}

func (c CreateProductRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateProductRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateProductRequest) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *CreateProductRequest) GetMerchantID() string {
	if c == nil {
		return ""
	}
	return c.MerchantID
}

func (c *CreateProductRequest) GetMetadata() *Metadata {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateProductRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}
