// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
)

// Currency - ISO 4217 currency code.
type Currency string

const (
	CurrencyUsd Currency = "USD"
	CurrencyEur Currency = "EUR"
	CurrencyGbp Currency = "GBP"
	CurrencyAud Currency = "AUD"
)

func (e Currency) ToPointer() *Currency {
	return &e
}
func (e *Currency) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "USD":
		fallthrough
	case "EUR":
		fallthrough
	case "GBP":
		fallthrough
	case "AUD":
		*e = Currency(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Currency: %v", v)
	}
}

type LineItem struct {
	// Line item description.
	Description string `json:"description"`
	// Line item amount in decimal format (e.g. '5.00').
	Amount string `json:"amount"`
	// Quantity of this line item. Defaults to 1.
	Quantity *int64 `default:"1" json:"quantity"`
}

func (l LineItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LineItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LineItem) GetDescription() string {
	if l == nil {
		return ""
	}
	return l.Description
}

func (l *LineItem) GetAmount() string {
	if l == nil {
		return ""
	}
	return l.Amount
}

func (l *LineItem) GetQuantity() *int64 {
	if l == nil {
		return nil
	}
	return l.Quantity
}

type CreatePaymentRequest struct {
	// Payment amount in decimal format (e.g. '10.50'). Minimum 1.00, maximum 5,000.00. Contact support for higher limits.
	Amount string `json:"amount"`
	// ISO 4217 currency code.
	Currency Currency `json:"currency"`
	// Merchant organization ID. Required when using an API key that is not scoped to a single merchant.
	MerchantID *string `json:"merchantId,omitzero"`
	// Optional customer ID. Must belong to this merchant.
	CustomerID *string `json:"customerId,omitzero"`
	// Client-provided key for safe retries. If a payment with the same key already exists, the existing payment is returned.
	IdempotencyKey *string `json:"idempotencyKey,omitzero"`
	// Merchant-defined reference for this payment (e.g. order ID, invoice number).
	Reference *string `json:"reference,omitzero"`
	// Arbitrary key-value string pairs to attach to the payment.
	Metadata map[string]string `json:"metadata,omitzero"`
	// Optional breakdown of what the customer is being charged for.
	LineItems []LineItem `json:"lineItems,omitzero"`
	// URL to redirect the customer to after a successful payment.
	SuccessRedirectURL *string `json:"successRedirectUrl,omitzero"`
	// URL to redirect the customer to after a failed payment.
	FailureRedirectURL *string `json:"failureRedirectUrl,omitzero"`
	// Whether to save the customer's payment method for future use. Defaults to false.
	SavePaymentMethod *bool `default:"false" json:"savePaymentMethod"`
	// ISO 8601 duration for the payment lifetime. Defaults to P30D (30 days). Maximum is P31D (31 days). Examples: PT1H, P1D, P7D, P30D.
	ExpiresIn *string `json:"expiresIn,omitzero"`
}

func (c CreatePaymentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePaymentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatePaymentRequest) GetAmount() string {
	if c == nil {
		return ""
	}
	return c.Amount
}

func (c *CreatePaymentRequest) GetCurrency() Currency {
	if c == nil {
		return Currency("")
	}
	return c.Currency
}

func (c *CreatePaymentRequest) GetMerchantID() *string {
	if c == nil {
		return nil
	}
	return c.MerchantID
}

func (c *CreatePaymentRequest) GetCustomerID() *string {
	if c == nil {
		return nil
	}
	return c.CustomerID
}

func (c *CreatePaymentRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreatePaymentRequest) GetReference() *string {
	if c == nil {
		return nil
	}
	return c.Reference
}

func (c *CreatePaymentRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreatePaymentRequest) GetLineItems() []LineItem {
	if c == nil {
		return nil
	}
	return c.LineItems
}

func (c *CreatePaymentRequest) GetSuccessRedirectURL() *string {
	if c == nil {
		return nil
	}
	return c.SuccessRedirectURL
}

func (c *CreatePaymentRequest) GetFailureRedirectURL() *string {
	if c == nil {
		return nil
	}
	return c.FailureRedirectURL
}

func (c *CreatePaymentRequest) GetSavePaymentMethod() *bool {
	if c == nil {
		return nil
	}
	return c.SavePaymentMethod
}

func (c *CreatePaymentRequest) GetExpiresIn() *string {
	if c == nil {
		return nil
	}
	return c.ExpiresIn
}
