// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteOrderLineItemRequest struct {
	OrderID string `pathParam:"style=simple,explode=false,name=orderId"`
	ID      string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteOrderLineItemRequest) GetOrderID() string {
	if d == nil {
		return ""
	}
	return d.OrderID
}

func (d *DeleteOrderLineItemRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}
