// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteTestClockRequest struct {
	// Test clock ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteTestClockRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}
