// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DisconnectMerchantIntegrationRequest struct {
	// The unique identifier of the merchant integration
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DisconnectMerchantIntegrationRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}
