// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/models/components"
)

type GenerateScheduleInvoicesRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GenerateScheduleInvoicesRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GenerateScheduleInvoicesObject string

const (
	GenerateScheduleInvoicesObjectList GenerateScheduleInvoicesObject = "list"
)

func (e GenerateScheduleInvoicesObject) ToPointer() *GenerateScheduleInvoicesObject {
	return &e
}
func (e *GenerateScheduleInvoicesObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = GenerateScheduleInvoicesObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GenerateScheduleInvoicesObject: %v", v)
	}
}

// GenerateScheduleInvoicesResponse - Staged invoices generated
type GenerateScheduleInvoicesResponse struct {
	Object GenerateScheduleInvoicesObject `json:"object"`
	Data   []components.ScheduleInvoice   `json:"data"`
	// Offset-based pagination response.
	Pagination components.OffsetPagination `json:"pagination"`
}

func (g *GenerateScheduleInvoicesResponse) GetObject() GenerateScheduleInvoicesObject {
	if g == nil {
		return GenerateScheduleInvoicesObject("")
	}
	return g.Object
}

func (g *GenerateScheduleInvoicesResponse) GetData() []components.ScheduleInvoice {
	if g == nil {
		return []components.ScheduleInvoice{}
	}
	return g.Data
}

func (g *GenerateScheduleInvoicesResponse) GetPagination() components.OffsetPagination {
	if g == nil {
		return components.OffsetPagination{}
	}
	return g.Pagination
}
