// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetEntitlementGrantRequest struct {
	// The unique identifier of the entitlement.
	EntitlementID string `pathParam:"style=simple,explode=false,name=entitlementId"`
	// The unique identifier of the grant.
	GrantID string `pathParam:"style=simple,explode=false,name=grantId"`
}

func (g *GetEntitlementGrantRequest) GetEntitlementID() string {
	if g == nil {
		return ""
	}
	return g.EntitlementID
}

func (g *GetEntitlementGrantRequest) GetGrantID() string {
	if g == nil {
		return ""
	}
	return g.GrantID
}
