// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetFeeRequest struct {
	// The unique identifier of the fee
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetFeeRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}
