// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetFeePriceRequest struct {
	// The unique identifier of the fee.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The unique identifier of the subscription.
	SubscriptionID string `pathParam:"style=simple,explode=false,name=subscriptionId"`
}

func (g *GetFeePriceRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetFeePriceRequest) GetSubscriptionID() string {
	if g == nil {
		return ""
	}
	return g.SubscriptionID
}
