// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetPriceRequest struct {
	// The unique identifier of the price
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetPriceRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}
