// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetSourceRequest struct {
	// The unique identifier of the source
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetSourceRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}
