// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
)

// ListPaymentsStatus - Filter by payment status.
type ListPaymentsStatus string

const (
	ListPaymentsStatusPending    ListPaymentsStatus = "pending"
	ListPaymentsStatusProcessing ListPaymentsStatus = "processing"
	ListPaymentsStatusCompleted  ListPaymentsStatus = "completed"
	ListPaymentsStatusExpired    ListPaymentsStatus = "expired"
	ListPaymentsStatusCancelled  ListPaymentsStatus = "cancelled"
)

func (e ListPaymentsStatus) ToPointer() *ListPaymentsStatus {
	return &e
}
func (e *ListPaymentsStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "processing":
		fallthrough
	case "completed":
		fallthrough
	case "expired":
		fallthrough
	case "cancelled":
		*e = ListPaymentsStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListPaymentsStatus: %v", v)
	}
}

type ListPaymentsRequest struct {
	// Merchant organization ID. Required when using an API key that is not scoped to a single merchant.
	MerchantID *string `queryParam:"style=form,explode=true,name=merchantId"`
	// Filter by payment status.
	Status *ListPaymentsStatus `queryParam:"style=form,explode=true,name=status"`
	// Filter by customer ID.
	CustomerID *string `queryParam:"style=form,explode=true,name=customerId"`
	// Number of payments to return.
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Number of payments to skip.
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListPaymentsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPaymentsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListPaymentsRequest) GetMerchantID() *string {
	if l == nil {
		return nil
	}
	return l.MerchantID
}

func (l *ListPaymentsRequest) GetStatus() *ListPaymentsStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListPaymentsRequest) GetCustomerID() *string {
	if l == nil {
		return nil
	}
	return l.CustomerID
}

func (l *ListPaymentsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListPaymentsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

type ListPaymentsObject string

const (
	ListPaymentsObjectList ListPaymentsObject = "list"
)

func (e ListPaymentsObject) ToPointer() *ListPaymentsObject {
	return &e
}
func (e *ListPaymentsObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ListPaymentsObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListPaymentsObject: %v", v)
	}
}

// ListPaymentsResponse - List of payments
type ListPaymentsResponse struct {
	Object ListPaymentsObject   `json:"object"`
	Data   []components.Payment `json:"data"`
	// Offset-based pagination response.
	Pagination components.OffsetPagination `json:"pagination"`
}

func (l *ListPaymentsResponse) GetObject() ListPaymentsObject {
	if l == nil {
		return ListPaymentsObject("")
	}
	return l.Object
}

func (l *ListPaymentsResponse) GetData() []components.Payment {
	if l == nil {
		return []components.Payment{}
	}
	return l.Data
}

func (l *ListPaymentsResponse) GetPagination() components.OffsetPagination {
	if l == nil {
		return components.OffsetPagination{}
	}
	return l.Pagination
}
