// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
	"time"
)

type ListUsageEventsRequest struct {
	// Filter by consumer ID. This is only available if the caller is member of the consumer organization.
	ConsumerID *string `queryParam:"style=form,explode=true,name=consumerId"`
	// Filter by customer ID. This is only available if the caller is member of the merchant organization owning this customer.
	CustomerID *string `queryParam:"style=form,explode=true,name=customerId"`
	// ISO 8601 date-time string filtering events up to this timestamp. Sample values: '2024-01-31T23:59:59Z', '2024-02-28T12:00:00Z'
	EndTime time.Time `queryParam:"style=form,explode=true,name=endTime"`
	// Number of usage events to return
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Filter by merchant ID. This is only available if the caller is member of the merchant organization.
	MerchantID *string `queryParam:"style=form,explode=true,name=merchantId"`
	// Number of usage events to skip
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// ISO 8601 date-time string filtering events from this timestamp onward. Sample values: '2024-01-15T00:00:00Z', '2024-02-01T10:30:00Z'
	StartTime time.Time `queryParam:"style=form,explode=true,name=startTime"`
	// Filter by subscription ID. This is only available if the caller is member of the consumer or merchant organization owning this subscription.
	SubscriptionID *string `queryParam:"style=form,explode=true,name=subscriptionId"`
}

func (l ListUsageEventsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListUsageEventsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListUsageEventsRequest) GetConsumerID() *string {
	if l == nil {
		return nil
	}
	return l.ConsumerID
}

func (l *ListUsageEventsRequest) GetCustomerID() *string {
	if l == nil {
		return nil
	}
	return l.CustomerID
}

func (l *ListUsageEventsRequest) GetEndTime() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.EndTime
}

func (l *ListUsageEventsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListUsageEventsRequest) GetMerchantID() *string {
	if l == nil {
		return nil
	}
	return l.MerchantID
}

func (l *ListUsageEventsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListUsageEventsRequest) GetStartTime() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.StartTime
}

func (l *ListUsageEventsRequest) GetSubscriptionID() *string {
	if l == nil {
		return nil
	}
	return l.SubscriptionID
}

type ListUsageEventsObject string

const (
	ListUsageEventsObjectList ListUsageEventsObject = "list"
)

func (e ListUsageEventsObject) ToPointer() *ListUsageEventsObject {
	return &e
}
func (e *ListUsageEventsObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ListUsageEventsObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListUsageEventsObject: %v", v)
	}
}

// ListUsageEventsResponse - List of usage events
type ListUsageEventsResponse struct {
	Object *ListUsageEventsObject  `json:"object,omitzero"`
	Data   []components.UsageEvent `json:"data,omitzero"`
	// Offset-based pagination response.
	Pagination *components.OffsetPagination `json:"pagination,omitzero"`
}

func (l ListUsageEventsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListUsageEventsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListUsageEventsResponse) GetObject() *ListUsageEventsObject {
	if l == nil {
		return nil
	}
	return l.Object
}

func (l *ListUsageEventsResponse) GetData() []components.UsageEvent {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListUsageEventsResponse) GetPagination() *components.OffsetPagination {
	if l == nil {
		return nil
	}
	return l.Pagination
}
