// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
)

// ListDisputesStatus - Filter by dispute status
type ListDisputesStatus string

const (
	ListDisputesStatusPending  ListDisputesStatus = "pending"
	ListDisputesStatusAccepted ListDisputesStatus = "accepted"
	ListDisputesStatusDeclined ListDisputesStatus = "declined"
)

func (e ListDisputesStatus) ToPointer() *ListDisputesStatus {
	return &e
}
func (e *ListDisputesStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "accepted":
		fallthrough
	case "declined":
		*e = ListDisputesStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListDisputesStatus: %v", v)
	}
}

type ListDisputesRequest struct {
	// Filter disputes for a specific consumer. At least one of merchantId, customerId, or consumerId must be provided.
	ConsumerID *string `queryParam:"style=form,explode=true,name=consumerId"`
	// Filter disputes for a specific customer. At least one of merchantId, customerId, or consumerId must be provided.
	CustomerID *string `queryParam:"style=form,explode=true,name=customerId"`
	// Number of disputes to return
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Filter disputes for a specific merchant. At least one of merchantId, customerId, or consumerId must be provided.
	MerchantID *string `queryParam:"style=form,explode=true,name=merchantId"`
	// Number of disputes to skip
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// Filter by dispute status
	Status *ListDisputesStatus `queryParam:"style=form,explode=true,name=status"`
}

func (l ListDisputesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListDisputesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListDisputesRequest) GetConsumerID() *string {
	if l == nil {
		return nil
	}
	return l.ConsumerID
}

func (l *ListDisputesRequest) GetCustomerID() *string {
	if l == nil {
		return nil
	}
	return l.CustomerID
}

func (l *ListDisputesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListDisputesRequest) GetMerchantID() *string {
	if l == nil {
		return nil
	}
	return l.MerchantID
}

func (l *ListDisputesRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListDisputesRequest) GetStatus() *ListDisputesStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

type ListDisputesObject string

const (
	ListDisputesObjectList ListDisputesObject = "list"
)

func (e ListDisputesObject) ToPointer() *ListDisputesObject {
	return &e
}
func (e *ListDisputesObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ListDisputesObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListDisputesObject: %v", v)
	}
}

type ListDisputesPagination struct {
	Limit   int64 `json:"limit"`
	Offset  int64 `json:"offset"`
	Total   int64 `json:"total"`
	HasMore bool  `json:"hasMore"`
}

func (l *ListDisputesPagination) GetLimit() int64 {
	if l == nil {
		return 0
	}
	return l.Limit
}

func (l *ListDisputesPagination) GetOffset() int64 {
	if l == nil {
		return 0
	}
	return l.Offset
}

func (l *ListDisputesPagination) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListDisputesPagination) GetHasMore() bool {
	if l == nil {
		return false
	}
	return l.HasMore
}

// ListDisputesResponse - Disputes retrieved successfully
type ListDisputesResponse struct {
	Object     ListDisputesObject               `json:"object"`
	Data       []components.DisputeWithCustomer `json:"data"`
	Pagination ListDisputesPagination           `json:"pagination"`
}

func (l *ListDisputesResponse) GetObject() ListDisputesObject {
	if l == nil {
		return ListDisputesObject("")
	}
	return l.Object
}

func (l *ListDisputesResponse) GetData() []components.DisputeWithCustomer {
	if l == nil {
		return []components.DisputeWithCustomer{}
	}
	return l.Data
}

func (l *ListDisputesResponse) GetPagination() ListDisputesPagination {
	if l == nil {
		return ListDisputesPagination{}
	}
	return l.Pagination
}
