// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
	"time"
)

type ListSubscriptionsStatus string

const (
	ListSubscriptionsStatusActive         ListSubscriptionsStatus = "active"
	ListSubscriptionsStatusTerminated     ListSubscriptionsStatus = "terminated"
	ListSubscriptionsStatusPendingPayment ListSubscriptionsStatus = "pending_payment"
)

func (e ListSubscriptionsStatus) ToPointer() *ListSubscriptionsStatus {
	return &e
}
func (e *ListSubscriptionsStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "active":
		fallthrough
	case "terminated":
		fallthrough
	case "pending_payment":
		*e = ListSubscriptionsStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListSubscriptionsStatus: %v", v)
	}
}

// Include related resources. When 'customer' is specified, each subscription includes merchant and consumer details.
type Include string

const (
	IncludeCustomer Include = "customer"
)

func (e Include) ToPointer() *Include {
	return &e
}
func (e *Include) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "customer":
		*e = Include(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Include: %v", v)
	}
}

type ListSubscriptionsRequest struct {
	ConsumerID *string `queryParam:"style=form,explode=true,name=consumerId"`
	CustomerID *string `queryParam:"style=form,explode=true,name=customerId"`
	// Number of subscriptions to return
	Limit      *string `default:"10" queryParam:"style=form,explode=true,name=limit"`
	MerchantID *string `queryParam:"style=form,explode=true,name=merchantId"`
	// Number of subscriptions to skip
	Offset *string                  `default:"0" queryParam:"style=form,explode=true,name=offset"`
	Status *ListSubscriptionsStatus `queryParam:"style=form,explode=true,name=status"`
	// Filter subscriptions started at or before this ISO 8601 date-time
	StartedBefore *time.Time `queryParam:"style=form,explode=true,name=startedBefore"`
	// Include related resources. When 'customer' is specified, each subscription includes merchant and consumer details.
	Include *Include `queryParam:"style=form,explode=true,name=include"`
}

func (l ListSubscriptionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSubscriptionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSubscriptionsRequest) GetConsumerID() *string {
	if l == nil {
		return nil
	}
	return l.ConsumerID
}

func (l *ListSubscriptionsRequest) GetCustomerID() *string {
	if l == nil {
		return nil
	}
	return l.CustomerID
}

func (l *ListSubscriptionsRequest) GetLimit() *string {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListSubscriptionsRequest) GetMerchantID() *string {
	if l == nil {
		return nil
	}
	return l.MerchantID
}

func (l *ListSubscriptionsRequest) GetOffset() *string {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListSubscriptionsRequest) GetStatus() *ListSubscriptionsStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListSubscriptionsRequest) GetStartedBefore() *time.Time {
	if l == nil {
		return nil
	}
	return l.StartedBefore
}

func (l *ListSubscriptionsRequest) GetInclude() *Include {
	if l == nil {
		return nil
	}
	return l.Include
}

// ListSubscriptionsResponse - List of subscriptions
type ListSubscriptionsResponse struct {
	Data []components.Subscription `json:"data,omitzero"`
	// Offset-based pagination response.
	Pagination *components.OffsetPagination `json:"pagination,omitzero"`
}

func (l ListSubscriptionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSubscriptionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSubscriptionsResponse) GetData() []components.Subscription {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListSubscriptionsResponse) GetPagination() *components.OffsetPagination {
	if l == nil {
		return nil
	}
	return l.Pagination
}
