// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/internal/utils"
)

type ListSubscriptionIntervalChangesRequest struct {
	// The subscription ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Number of interval changes to return
	Limit *string `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Number of interval changes to skip
	Offset *string `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListSubscriptionIntervalChangesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSubscriptionIntervalChangesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSubscriptionIntervalChangesRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListSubscriptionIntervalChangesRequest) GetLimit() *string {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListSubscriptionIntervalChangesRequest) GetOffset() *string {
	if l == nil {
		return nil
	}
	return l.Offset
}
