// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
)

type ListFeaturesRequest struct {
	// The product ID to filter features by
	ProductID string `queryParam:"style=form,explode=true,name=productId"`
	// Optional feature key to filter by. If provided, returns only the feature matching both productId and key
	Key *string `queryParam:"style=form,explode=true,name=key"`
	// Number of features to return.
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Number of features to skip.
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListFeaturesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListFeaturesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListFeaturesRequest) GetProductID() string {
	if l == nil {
		return ""
	}
	return l.ProductID
}

func (l *ListFeaturesRequest) GetKey() *string {
	if l == nil {
		return nil
	}
	return l.Key
}

func (l *ListFeaturesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListFeaturesRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

type ListFeaturesObject string

const (
	ListFeaturesObjectList ListFeaturesObject = "list"
)

func (e ListFeaturesObject) ToPointer() *ListFeaturesObject {
	return &e
}
func (e *ListFeaturesObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ListFeaturesObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListFeaturesObject: %v", v)
	}
}

type ListFeaturesPagination struct {
	// Number of items requested
	Limit int64 `json:"limit"`
	// Number of items skipped
	Offset int64 `json:"offset"`
	// Total number of items matching the query
	Total int64 `json:"total"`
}

func (l *ListFeaturesPagination) GetLimit() int64 {
	if l == nil {
		return 0
	}
	return l.Limit
}

func (l *ListFeaturesPagination) GetOffset() int64 {
	if l == nil {
		return 0
	}
	return l.Offset
}

func (l *ListFeaturesPagination) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}

// ListFeaturesResponse - List of features
type ListFeaturesResponse struct {
	Object     ListFeaturesObject     `json:"object"`
	Data       []components.Feature   `json:"data"`
	Pagination ListFeaturesPagination `json:"pagination"`
}

func (l *ListFeaturesResponse) GetObject() ListFeaturesObject {
	if l == nil {
		return ListFeaturesObject("")
	}
	return l.Object
}

func (l *ListFeaturesResponse) GetData() []components.Feature {
	if l == nil {
		return []components.Feature{}
	}
	return l.Data
}

func (l *ListFeaturesResponse) GetPagination() ListFeaturesPagination {
	if l == nil {
		return ListFeaturesPagination{}
	}
	return l.Pagination
}
