// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
)

type ListItemsRequest struct {
	// Filter items by merchant organization id
	MerchantID *string `queryParam:"style=form,explode=true,name=merchantId"`
	// Filter items by the product they are filed under
	CatalogID *string `queryParam:"style=form,explode=true,name=catalogId"`
	// Provider whose external code to resolve (e.g. `salesforce`, `netsuite`). Must be supplied together with `externalId`.
	Provider *string `queryParam:"style=form,explode=true,name=provider"`
	// Resolve every live Item mapped to this `(provider, externalId)` — the canonical primary plus any non-primary aliases. The primary Item is returned first and is identifiable by its matching reference's `isPrimary: true`. Empty list on no match. Must be supplied together with `provider`.
	ExternalID *string `queryParam:"style=form,explode=true,name=externalId"`
	// Maximum items to return. In resolution mode (`provider`+`externalId` supplied) pagination is over the de-duplicated resolved Item set, primary Item first.
	Limit *int64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Zero-based offset for pagination. In resolution mode this paginates the de-duplicated resolved Item set.
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// Include archived items in the results. By default, archived items are omitted. This is ignored when resolving by `provider` and `externalId`, which always returns the matching item regardless of archived status.
	IncludeArchived *bool `default:"false" queryParam:"style=form,explode=true,name=includeArchived"`
}

func (l ListItemsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListItemsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListItemsRequest) GetMerchantID() *string {
	if l == nil {
		return nil
	}
	return l.MerchantID
}

func (l *ListItemsRequest) GetCatalogID() *string {
	if l == nil {
		return nil
	}
	return l.CatalogID
}

func (l *ListItemsRequest) GetProvider() *string {
	if l == nil {
		return nil
	}
	return l.Provider
}

func (l *ListItemsRequest) GetExternalID() *string {
	if l == nil {
		return nil
	}
	return l.ExternalID
}

func (l *ListItemsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListItemsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListItemsRequest) GetIncludeArchived() *bool {
	if l == nil {
		return nil
	}
	return l.IncludeArchived
}

// ListItemsResponse - List of items
type ListItemsResponse struct {
	Data []components.Item `json:"data"`
	// Offset-based pagination response.
	Pagination components.OffsetPagination `json:"pagination"`
}

func (l *ListItemsResponse) GetData() []components.Item {
	if l == nil {
		return []components.Item{}
	}
	return l.Data
}

func (l *ListItemsResponse) GetPagination() components.OffsetPagination {
	if l == nil {
		return components.OffsetPagination{}
	}
	return l.Pagination
}
