// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
	"time"
)

type ListIntervalChangesRequest struct {
	// Number of interval changes to return
	Limit *string `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Number of interval changes to skip
	Offset *string `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// Only return changes recorded at or after this time
	From *time.Time `queryParam:"style=form,explode=true,name=from"`
	// Only return changes recorded before this time
	To *time.Time `queryParam:"style=form,explode=true,name=to"`
	// Only return changes with this reason.
	ChangeReason *components.ChangeReason `queryParam:"style=form,explode=true,name=changeReason"`
}

func (l ListIntervalChangesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListIntervalChangesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListIntervalChangesRequest) GetLimit() *string {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListIntervalChangesRequest) GetOffset() *string {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListIntervalChangesRequest) GetFrom() *time.Time {
	if l == nil {
		return nil
	}
	return l.From
}

func (l *ListIntervalChangesRequest) GetTo() *time.Time {
	if l == nil {
		return nil
	}
	return l.To
}

func (l *ListIntervalChangesRequest) GetChangeReason() *components.ChangeReason {
	if l == nil {
		return nil
	}
	return l.ChangeReason
}
