// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
)

type ListPlanVersionsRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Maximum number of versions to return
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Number of versions to skip
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListPlanVersionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPlanVersionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListPlanVersionsRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListPlanVersionsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListPlanVersionsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

type ListPlanVersionsObject string

const (
	ListPlanVersionsObjectList ListPlanVersionsObject = "list"
)

func (e ListPlanVersionsObject) ToPointer() *ListPlanVersionsObject {
	return &e
}
func (e *ListPlanVersionsObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ListPlanVersionsObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListPlanVersionsObject: %v", v)
	}
}

// ListPlanVersionsResponse - List of plan versions
type ListPlanVersionsResponse struct {
	Object ListPlanVersionsObject          `json:"object"`
	Data   []components.PlanVersionSummary `json:"data"`
	// Offset-based pagination response.
	Pagination components.OffsetPagination `json:"pagination"`
}

func (l *ListPlanVersionsResponse) GetObject() ListPlanVersionsObject {
	if l == nil {
		return ListPlanVersionsObject("")
	}
	return l.Object
}

func (l *ListPlanVersionsResponse) GetData() []components.PlanVersionSummary {
	if l == nil {
		return []components.PlanVersionSummary{}
	}
	return l.Data
}

func (l *ListPlanVersionsResponse) GetPagination() components.OffsetPagination {
	if l == nil {
		return components.OffsetPagination{}
	}
	return l.Pagination
}
