// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
)

type ListBillableMetricsRequest struct {
	// Number of billable metrics to return.
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Filter billable metrics by merchant organization ID.
	MerchantID string `queryParam:"style=form,explode=true,name=merchantId"`
	// Number of billable metrics to skip.
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// Filter billable metrics by product ID.
	ProductID *string `queryParam:"style=form,explode=true,name=productId"`
}

func (l ListBillableMetricsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListBillableMetricsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListBillableMetricsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListBillableMetricsRequest) GetMerchantID() string {
	if l == nil {
		return ""
	}
	return l.MerchantID
}

func (l *ListBillableMetricsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListBillableMetricsRequest) GetProductID() *string {
	if l == nil {
		return nil
	}
	return l.ProductID
}

type ListBillableMetricsObject string

const (
	ListBillableMetricsObjectList ListBillableMetricsObject = "list"
)

func (e ListBillableMetricsObject) ToPointer() *ListBillableMetricsObject {
	return &e
}
func (e *ListBillableMetricsObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ListBillableMetricsObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListBillableMetricsObject: %v", v)
	}
}

type ListBillableMetricsPagination struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
	Total  int64 `json:"total"`
}

func (l *ListBillableMetricsPagination) GetLimit() int64 {
	if l == nil {
		return 0
	}
	return l.Limit
}

func (l *ListBillableMetricsPagination) GetOffset() int64 {
	if l == nil {
		return 0
	}
	return l.Offset
}

func (l *ListBillableMetricsPagination) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}

// ListBillableMetricsResponse - List of billable metrics
type ListBillableMetricsResponse struct {
	Object     ListBillableMetricsObject     `json:"object"`
	Data       []components.BillableMetric   `json:"data"`
	Pagination ListBillableMetricsPagination `json:"pagination"`
}

func (l *ListBillableMetricsResponse) GetObject() ListBillableMetricsObject {
	if l == nil {
		return ListBillableMetricsObject("")
	}
	return l.Object
}

func (l *ListBillableMetricsResponse) GetData() []components.BillableMetric {
	if l == nil {
		return []components.BillableMetric{}
	}
	return l.Data
}

func (l *ListBillableMetricsResponse) GetPagination() ListBillableMetricsPagination {
	if l == nil {
		return ListBillableMetricsPagination{}
	}
	return l.Pagination
}
