// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
)

type ListFeesRequest struct {
	// Number of fees to return.
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Filter fees by merchant organization ID.
	MerchantID string `queryParam:"style=form,explode=true,name=merchantId"`
	// Number of fees to skip.
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// Filter fees by product ID.
	ProductID *string `queryParam:"style=form,explode=true,name=productId"`
}

func (l ListFeesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListFeesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListFeesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListFeesRequest) GetMerchantID() string {
	if l == nil {
		return ""
	}
	return l.MerchantID
}

func (l *ListFeesRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListFeesRequest) GetProductID() *string {
	if l == nil {
		return nil
	}
	return l.ProductID
}

type ListFeesObject string

const (
	ListFeesObjectList ListFeesObject = "list"
)

func (e ListFeesObject) ToPointer() *ListFeesObject {
	return &e
}
func (e *ListFeesObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ListFeesObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListFeesObject: %v", v)
	}
}

type ListFeesPagination struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
	Total  int64 `json:"total"`
}

func (l *ListFeesPagination) GetLimit() int64 {
	if l == nil {
		return 0
	}
	return l.Limit
}

func (l *ListFeesPagination) GetOffset() int64 {
	if l == nil {
		return 0
	}
	return l.Offset
}

func (l *ListFeesPagination) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}

// ListFeesResponse - List of fees
type ListFeesResponse struct {
	Object     ListFeesObject     `json:"object"`
	Data       []components.Fee   `json:"data"`
	Pagination ListFeesPagination `json:"pagination"`
}

func (l *ListFeesResponse) GetObject() ListFeesObject {
	if l == nil {
		return ListFeesObject("")
	}
	return l.Object
}

func (l *ListFeesResponse) GetData() []components.Fee {
	if l == nil {
		return []components.Fee{}
	}
	return l.Data
}

func (l *ListFeesResponse) GetPagination() ListFeesPagination {
	if l == nil {
		return ListFeesPagination{}
	}
	return l.Pagination
}
