// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/models/components"
)

type ListScheduleInvoicesRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (l *ListScheduleInvoicesRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

type ListScheduleInvoicesObject string

const (
	ListScheduleInvoicesObjectList ListScheduleInvoicesObject = "list"
)

func (e ListScheduleInvoicesObject) ToPointer() *ListScheduleInvoicesObject {
	return &e
}
func (e *ListScheduleInvoicesObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ListScheduleInvoicesObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListScheduleInvoicesObject: %v", v)
	}
}

// ListScheduleInvoicesResponse - List of staged invoices
type ListScheduleInvoicesResponse struct {
	Object ListScheduleInvoicesObject   `json:"object"`
	Data   []components.ScheduleInvoice `json:"data"`
	// Offset-based pagination response.
	Pagination components.OffsetPagination `json:"pagination"`
}

func (l *ListScheduleInvoicesResponse) GetObject() ListScheduleInvoicesObject {
	if l == nil {
		return ListScheduleInvoicesObject("")
	}
	return l.Object
}

func (l *ListScheduleInvoicesResponse) GetData() []components.ScheduleInvoice {
	if l == nil {
		return []components.ScheduleInvoice{}
	}
	return l.Data
}

func (l *ListScheduleInvoicesResponse) GetPagination() components.OffsetPagination {
	if l == nil {
		return components.OffsetPagination{}
	}
	return l.Pagination
}
