// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
)

type ListExternalReferencesRequest struct {
	// Restrict results to a specific merchant. All active filters AND together.
	MerchantID *string `queryParam:"style=form,explode=true,name=merchantId"`
	// Filter by the Paygentic entity type the reference points at (e.g. `item`). All active filters AND together.
	EntityType *components.EntityType `queryParam:"style=form,explode=true,name=entityType"`
	// Filter by the Paygentic entity id (e.g. `itm_xxx`). This is the inverse of the `GET /v0/items?provider=&externalId=` resolution endpoint — look up references from the Paygentic side. All active filters AND together.
	EntityID *string `queryParam:"style=form,explode=true,name=entityId"`
	// Filter by provider (e.g. `salesforce`, `netsuite`). All active filters AND together.
	Provider *string `queryParam:"style=form,explode=true,name=provider"`
	// Filter by the external system's record id. Pair with `provider` to look up all Paygentic entities that carry a given external reference. All active filters AND together.
	ExternalID *string `queryParam:"style=form,explode=true,name=externalId"`
	Limit      *int64  `default:"50" queryParam:"style=form,explode=true,name=limit"`
	Offset     *int64  `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListExternalReferencesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListExternalReferencesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListExternalReferencesRequest) GetMerchantID() *string {
	if l == nil {
		return nil
	}
	return l.MerchantID
}

func (l *ListExternalReferencesRequest) GetEntityType() *components.EntityType {
	if l == nil {
		return nil
	}
	return l.EntityType
}

func (l *ListExternalReferencesRequest) GetEntityID() *string {
	if l == nil {
		return nil
	}
	return l.EntityID
}

func (l *ListExternalReferencesRequest) GetProvider() *string {
	if l == nil {
		return nil
	}
	return l.Provider
}

func (l *ListExternalReferencesRequest) GetExternalID() *string {
	if l == nil {
		return nil
	}
	return l.ExternalID
}

func (l *ListExternalReferencesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListExternalReferencesRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

// ListExternalReferencesResponse - List of external references
type ListExternalReferencesResponse struct {
	Data []components.ExternalReference `json:"data"`
	// Offset-based pagination response.
	Pagination components.OffsetPagination `json:"pagination"`
}

func (l *ListExternalReferencesResponse) GetData() []components.ExternalReference {
	if l == nil {
		return []components.ExternalReference{}
	}
	return l.Data
}

func (l *ListExternalReferencesResponse) GetPagination() components.OffsetPagination {
	if l == nil {
		return components.OffsetPagination{}
	}
	return l.Pagination
}
