// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
)

type ListCostsRequest struct {
	// Filter costs by merchant organization ID. If omitted, defaults to the merchant associated with the authenticated API key.
	MerchantID *string `queryParam:"style=form,explode=true,name=merchantId"`
	// Filter costs by product ID.
	ProductID *string `queryParam:"style=form,explode=true,name=productId"`
	// Number of costs to return.
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Number of costs to skip.
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListCostsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCostsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCostsRequest) GetMerchantID() *string {
	if l == nil {
		return nil
	}
	return l.MerchantID
}

func (l *ListCostsRequest) GetProductID() *string {
	if l == nil {
		return nil
	}
	return l.ProductID
}

func (l *ListCostsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListCostsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

type ListCostsObject string

const (
	ListCostsObjectList ListCostsObject = "list"
)

func (e ListCostsObject) ToPointer() *ListCostsObject {
	return &e
}
func (e *ListCostsObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ListCostsObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListCostsObject: %v", v)
	}
}

type ListCostsPagination struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
	Total  int64 `json:"total"`
}

func (l *ListCostsPagination) GetLimit() int64 {
	if l == nil {
		return 0
	}
	return l.Limit
}

func (l *ListCostsPagination) GetOffset() int64 {
	if l == nil {
		return 0
	}
	return l.Offset
}

func (l *ListCostsPagination) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}

// ListCostsResponse - List of costs
type ListCostsResponse struct {
	Object     ListCostsObject     `json:"object"`
	Data       []components.Cost   `json:"data"`
	Pagination ListCostsPagination `json:"pagination"`
}

func (l *ListCostsResponse) GetObject() ListCostsObject {
	if l == nil {
		return ListCostsObject("")
	}
	return l.Object
}

func (l *ListCostsResponse) GetData() []components.Cost {
	if l == nil {
		return []components.Cost{}
	}
	return l.Data
}

func (l *ListCostsResponse) GetPagination() ListCostsPagination {
	if l == nil {
		return ListCostsPagination{}
	}
	return l.Pagination
}
