// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
)

// ListLineItemsStatus - Filter by line item status. 'pending' returns items not yet on an invoice, 'invoiced' returns items already assigned to an invoice. Omit to return both. Cannot be combined with invoiceId — when filtering by invoice ID all statuses are returned.
type ListLineItemsStatus string

const (
	ListLineItemsStatusPending  ListLineItemsStatus = "pending"
	ListLineItemsStatusInvoiced ListLineItemsStatus = "invoiced"
)

func (e ListLineItemsStatus) ToPointer() *ListLineItemsStatus {
	return &e
}
func (e *ListLineItemsStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "invoiced":
		*e = ListLineItemsStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListLineItemsStatus: %v", v)
	}
}

type ListLineItemsRequest struct {
	// Filter by subscription ID. At least one of subscriptionId or invoiceId must be provided.
	SubscriptionID *string `queryParam:"style=form,explode=true,name=subscriptionId"`
	// Filter by line item status. 'pending' returns items not yet on an invoice, 'invoiced' returns items already assigned to an invoice. Omit to return both. Cannot be combined with invoiceId — when filtering by invoice ID all statuses are returned.
	Status *ListLineItemsStatus `queryParam:"style=form,explode=true,name=status"`
	// Filter by invoice ID. When provided without subscriptionId, returns all line items for that invoice. At least one of subscriptionId or invoiceId must be provided.
	InvoiceID *string `queryParam:"style=form,explode=true,name=invoiceId"`
	// Maximum number of line items to return
	Limit *int64 `default:"100" queryParam:"style=form,explode=true,name=limit"`
	// Number of line items to skip for pagination
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListLineItemsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListLineItemsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListLineItemsRequest) GetSubscriptionID() *string {
	if l == nil {
		return nil
	}
	return l.SubscriptionID
}

func (l *ListLineItemsRequest) GetStatus() *ListLineItemsStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListLineItemsRequest) GetInvoiceID() *string {
	if l == nil {
		return nil
	}
	return l.InvoiceID
}

func (l *ListLineItemsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListLineItemsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}
