// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
	"time"
)

type ListEntitlementsRequest struct {
	// The unique identifier of the customer to retrieve entitlements for.
	CustomerID string `queryParam:"style=form,explode=true,name=customerId"`
	// Filter results to a specific feature by its key. When specified, `productId` is also required. Use this to check access to a single feature.
	FeatureKey *string `queryParam:"style=form,explode=true,name=featureKey"`
	// Filter results to entitlements for a specific product. Required when `featureKey` is specified since feature keys are scoped to products.
	ProductID *string `queryParam:"style=form,explode=true,name=productId"`
	// Filter results to entitlements for a specific subscription.
	SubscriptionID *string `queryParam:"style=form,explode=true,name=subscriptionId"`
	// Maximum number of entitlements to return per page. Use with `offset` for pagination.
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Number of entitlements to skip. Use with `limit` for pagination through large result sets.
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// Evaluate balance and access at this point in time (RFC 3339 datetime with any UTC offset, e.g. 2024-01-15T10:30:00Z or 2024-01-15T15:30:00+05:30). Defaults to current time.
	At *time.Time `queryParam:"style=form,explode=true,name=at"`
}

func (l ListEntitlementsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEntitlementsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListEntitlementsRequest) GetCustomerID() string {
	if l == nil {
		return ""
	}
	return l.CustomerID
}

func (l *ListEntitlementsRequest) GetFeatureKey() *string {
	if l == nil {
		return nil
	}
	return l.FeatureKey
}

func (l *ListEntitlementsRequest) GetProductID() *string {
	if l == nil {
		return nil
	}
	return l.ProductID
}

func (l *ListEntitlementsRequest) GetSubscriptionID() *string {
	if l == nil {
		return nil
	}
	return l.SubscriptionID
}

func (l *ListEntitlementsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListEntitlementsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListEntitlementsRequest) GetAt() *time.Time {
	if l == nil {
		return nil
	}
	return l.At
}

type ListEntitlementsObject string

const (
	ListEntitlementsObjectList ListEntitlementsObject = "list"
)

func (e ListEntitlementsObject) ToPointer() *ListEntitlementsObject {
	return &e
}
func (e *ListEntitlementsObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ListEntitlementsObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListEntitlementsObject: %v", v)
	}
}

// ListEntitlementsResponse - Successfully retrieved the list of entitlements for the customer.
type ListEntitlementsResponse struct {
	Object *ListEntitlementsObject `default:"list" json:"object"`
	// Array of entitlement access results.
	Data []components.EntitlementAccessResult `json:"data"`
	// Offset-based pagination response.
	Pagination components.OffsetPagination `json:"pagination"`
}

func (l ListEntitlementsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEntitlementsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListEntitlementsResponse) GetObject() *ListEntitlementsObject {
	if l == nil {
		return nil
	}
	return l.Object
}

func (l *ListEntitlementsResponse) GetData() []components.EntitlementAccessResult {
	if l == nil {
		return []components.EntitlementAccessResult{}
	}
	return l.Data
}

func (l *ListEntitlementsResponse) GetPagination() components.OffsetPagination {
	if l == nil {
		return components.OffsetPagination{}
	}
	return l.Pagination
}
