// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
)

type ListEntitlementGrantsRequest struct {
	// The unique identifier of the entitlement.
	EntitlementID string `pathParam:"style=simple,explode=false,name=entitlementId"`
	// Maximum number of grants to return per page.
	Limit *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
	// Number of grants to skip.
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// When true, voided grants are included in the response.
	IncludeVoided *bool `default:"false" queryParam:"style=form,explode=true,name=includeVoided"`
}

func (l ListEntitlementGrantsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEntitlementGrantsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListEntitlementGrantsRequest) GetEntitlementID() string {
	if l == nil {
		return ""
	}
	return l.EntitlementID
}

func (l *ListEntitlementGrantsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListEntitlementGrantsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListEntitlementGrantsRequest) GetIncludeVoided() *bool {
	if l == nil {
		return nil
	}
	return l.IncludeVoided
}

type ListEntitlementGrantsObject string

const (
	ListEntitlementGrantsObjectList ListEntitlementGrantsObject = "list"
)

func (e ListEntitlementGrantsObject) ToPointer() *ListEntitlementGrantsObject {
	return &e
}
func (e *ListEntitlementGrantsObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ListEntitlementGrantsObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListEntitlementGrantsObject: %v", v)
	}
}

// ListEntitlementGrantsResponse - Successfully retrieved the list of grants.
type ListEntitlementGrantsResponse struct {
	Object *ListEntitlementGrantsObject `default:"list" json:"object"`
	Data   []components.Grant           `json:"data"`
	// Offset-based pagination response.
	Pagination components.OffsetPagination `json:"pagination"`
}

func (l ListEntitlementGrantsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEntitlementGrantsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListEntitlementGrantsResponse) GetObject() *ListEntitlementGrantsObject {
	if l == nil {
		return nil
	}
	return l.Object
}

func (l *ListEntitlementGrantsResponse) GetData() []components.Grant {
	if l == nil {
		return []components.Grant{}
	}
	return l.Data
}

func (l *ListEntitlementGrantsResponse) GetPagination() components.OffsetPagination {
	if l == nil {
		return components.OffsetPagination{}
	}
	return l.Pagination
}
