// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/models/components"
)

type MintPlanVersionRequest struct {
	ID   string                            `pathParam:"style=simple,explode=false,name=id"`
	Body components.MintPlanVersionRequest `request:"mediaType=application/json"`
}

func (m *MintPlanVersionRequest) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *MintPlanVersionRequest) GetBody() components.MintPlanVersionRequest {
	if m == nil {
		return components.MintPlanVersionRequest{}
	}
	return m.Body
}
