// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type RejectSourceEventRequest struct {
	ID      string `pathParam:"style=simple,explode=false,name=id"`
	EventID string `pathParam:"style=simple,explode=false,name=eventId"`
}

func (r *RejectSourceEventRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RejectSourceEventRequest) GetEventID() string {
	if r == nil {
		return ""
	}
	return r.EventID
}
