// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/models/components"
)

type ReplaceScheduleIntervalsRequest struct {
	ID   string                                     `pathParam:"style=simple,explode=false,name=id"`
	Body components.ReplaceScheduleIntervalsRequest `request:"mediaType=application/json"`
}

func (r *ReplaceScheduleIntervalsRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *ReplaceScheduleIntervalsRequest) GetBody() components.ReplaceScheduleIntervalsRequest {
	if r == nil {
		return components.ReplaceScheduleIntervalsRequest{}
	}
	return r.Body
}

type ReplaceScheduleIntervalsObject string

const (
	ReplaceScheduleIntervalsObjectList ReplaceScheduleIntervalsObject = "list"
)

func (e ReplaceScheduleIntervalsObject) ToPointer() *ReplaceScheduleIntervalsObject {
	return &e
}
func (e *ReplaceScheduleIntervalsObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ReplaceScheduleIntervalsObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReplaceScheduleIntervalsObject: %v", v)
	}
}

// ReplaceScheduleIntervalsResponse - Intervals replaced
type ReplaceScheduleIntervalsResponse struct {
	Object ReplaceScheduleIntervalsObject `json:"object"`
	Data   []components.ScheduleInterval  `json:"data"`
	// Offset-based pagination response.
	Pagination components.OffsetPagination `json:"pagination"`
}

func (r *ReplaceScheduleIntervalsResponse) GetObject() ReplaceScheduleIntervalsObject {
	if r == nil {
		return ReplaceScheduleIntervalsObject("")
	}
	return r.Object
}

func (r *ReplaceScheduleIntervalsResponse) GetData() []components.ScheduleInterval {
	if r == nil {
		return []components.ScheduleInterval{}
	}
	return r.Data
}

func (r *ReplaceScheduleIntervalsResponse) GetPagination() components.OffsetPagination {
	if r == nil {
		return components.OffsetPagination{}
	}
	return r.Pagination
}
