// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
)

// UpdateCostAggregation - Updated aggregation method (metered costs only).
type UpdateCostAggregation string

const (
	UpdateCostAggregationSum         UpdateCostAggregation = "SUM"
	UpdateCostAggregationCount       UpdateCostAggregation = "COUNT"
	UpdateCostAggregationAvg         UpdateCostAggregation = "AVG"
	UpdateCostAggregationMin         UpdateCostAggregation = "MIN"
	UpdateCostAggregationMax         UpdateCostAggregation = "MAX"
	UpdateCostAggregationUniqueCount UpdateCostAggregation = "UNIQUE_COUNT"
	UpdateCostAggregationLatest      UpdateCostAggregation = "LATEST"
)

func (e UpdateCostAggregation) ToPointer() *UpdateCostAggregation {
	return &e
}
func (e *UpdateCostAggregation) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SUM":
		fallthrough
	case "COUNT":
		fallthrough
	case "AVG":
		fallthrough
	case "MIN":
		fallthrough
	case "MAX":
		fallthrough
	case "UNIQUE_COUNT":
		fallthrough
	case "LATEST":
		*e = UpdateCostAggregation(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateCostAggregation: %v", v)
	}
}

type UpdateCostRequestBody struct {
	// Updated name for the cost.
	Name *string `json:"name,omitzero"`
	// Updated unit cost.
	UnitCost *float64 `json:"unitCost,omitzero"`
	// Updated ISO 4217 currency code.
	Currency *string `json:"currency,omitzero"`
	// Updated unit label (metered costs only).
	Unit optionalnullable.OptionalNullable[string] `json:"unit,omitzero"`
	// Updated aggregation method (metered costs only).
	Aggregation optionalnullable.OptionalNullable[UpdateCostAggregation] `json:"aggregation,omitzero"`
	// Updated CloudEvents type (metered costs only).
	EventType optionalnullable.OptionalNullable[string] `json:"eventType,omitzero"`
	// Updated JSONPath for value extraction (metered costs only).
	ValueProperty optionalnullable.OptionalNullable[string] `json:"valueProperty,omitzero"`
	// Updated group-by dimension map (metered costs only).
	GroupBy optionalnullable.OptionalNullable[map[string]string] `json:"groupBy,omitzero"`
}

func (u UpdateCostRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateCostRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateCostRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateCostRequestBody) GetUnitCost() *float64 {
	if u == nil {
		return nil
	}
	return u.UnitCost
}

func (u *UpdateCostRequestBody) GetCurrency() *string {
	if u == nil {
		return nil
	}
	return u.Currency
}

func (u *UpdateCostRequestBody) GetUnit() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Unit
}

func (u *UpdateCostRequestBody) GetAggregation() optionalnullable.OptionalNullable[UpdateCostAggregation] {
	if u == nil {
		return nil
	}
	return u.Aggregation
}

func (u *UpdateCostRequestBody) GetEventType() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.EventType
}

func (u *UpdateCostRequestBody) GetValueProperty() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.ValueProperty
}

func (u *UpdateCostRequestBody) GetGroupBy() optionalnullable.OptionalNullable[map[string]string] {
	if u == nil {
		return nil
	}
	return u.GroupBy
}

type UpdateCostRequest struct {
	// The unique identifier of the cost
	ID   string                `pathParam:"style=simple,explode=false,name=id"`
	Body UpdateCostRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateCostRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateCostRequest) GetBody() UpdateCostRequestBody {
	if u == nil {
		return UpdateCostRequestBody{}
	}
	return u.Body
}
