// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/models/components"
)

type UpdateApprovalRequest struct {
	ID   string                           `pathParam:"style=simple,explode=false,name=id"`
	Body components.UpdateApprovalRequest `request:"mediaType=application/json"`
}

func (u *UpdateApprovalRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateApprovalRequest) GetBody() components.UpdateApprovalRequest {
	if u == nil {
		return components.UpdateApprovalRequest{}
	}
	return u.Body
}
