// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
)

// UpdateSourceProcessingMode - How events are processed - automatic (immediate) or manual (requires approval)
type UpdateSourceProcessingMode string

const (
	UpdateSourceProcessingModeAutomatic UpdateSourceProcessingMode = "automatic"
	UpdateSourceProcessingModeManual    UpdateSourceProcessingMode = "manual"
)

func (e UpdateSourceProcessingMode) ToPointer() *UpdateSourceProcessingMode {
	return &e
}
func (e *UpdateSourceProcessingMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "automatic":
		fallthrough
	case "manual":
		*e = UpdateSourceProcessingMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateSourceProcessingMode: %v", v)
	}
}

type UpdateSourceRequestBody struct {
	// Configuration specific to the source type
	Config map[string]any `json:"config,omitzero"`
	// Description of the source
	Description *string `json:"description,omitzero"`
	// Whether the source is enabled
	Enabled *bool `json:"enabled,omitzero"`
	// Metadata for the source
	Metadata map[string]any `json:"metadata,omitzero"`
	// Display name for the source
	Name *string `json:"name,omitzero"`
	// How events are processed - automatic (immediate) or manual (requires approval)
	ProcessingMode *UpdateSourceProcessingMode `json:"processingMode,omitzero"`
}

func (u UpdateSourceRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSourceRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSourceRequestBody) GetConfig() map[string]any {
	if u == nil {
		return nil
	}
	return u.Config
}

func (u *UpdateSourceRequestBody) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateSourceRequestBody) GetEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.Enabled
}

func (u *UpdateSourceRequestBody) GetMetadata() map[string]any {
	if u == nil {
		return nil
	}
	return u.Metadata
}

func (u *UpdateSourceRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateSourceRequestBody) GetProcessingMode() *UpdateSourceProcessingMode {
	if u == nil {
		return nil
	}
	return u.ProcessingMode
}

type UpdateSourceRequest struct {
	// The unique identifier of the source
	ID   string                  `pathParam:"style=simple,explode=false,name=id"`
	Body UpdateSourceRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateSourceRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateSourceRequest) GetBody() UpdateSourceRequestBody {
	if u == nil {
		return UpdateSourceRequestBody{}
	}
	return u.Body
}
