// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/optionalnullable"
)

type UpdateFeeRequestBody struct {
	// Revised explanation of what the fee represents.
	Description *string `json:"description,omitzero"`
	// Updated label for the fee.
	Name *string `json:"name,omitzero"`
	// Optional item tag, used to map this fee's invoice lines to an external accounting/tax identity. Send a new id to re-tag — `productId` is re-derived from that item's catalog, and an archived item is rejected. Send `null` to untag.
	ItemID optionalnullable.OptionalNullable[string] `json:"itemId,omitzero"`
}

func (u *UpdateFeeRequestBody) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateFeeRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateFeeRequestBody) GetItemID() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.ItemID
}

type UpdateFeeRequest struct {
	// The unique identifier of the fee
	ID   string               `pathParam:"style=simple,explode=false,name=id"`
	Body UpdateFeeRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateFeeRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateFeeRequest) GetBody() UpdateFeeRequestBody {
	if u == nil {
		return UpdateFeeRequestBody{}
	}
	return u.Body
}
