// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type UpdateFeeRequestBody struct {
	// Revised explanation of what the fee represents.
	Description *string `json:"description,omitzero"`
	// Updated label for the fee.
	Name *string `json:"name,omitzero"`
}

func (u *UpdateFeeRequestBody) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateFeeRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

type UpdateFeeRequest struct {
	// The unique identifier of the fee
	ID   string               `pathParam:"style=simple,explode=false,name=id"`
	Body UpdateFeeRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateFeeRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateFeeRequest) GetBody() UpdateFeeRequestBody {
	if u == nil {
		return UpdateFeeRequestBody{}
	}
	return u.Body
}
