// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
)

type TaxRatesType string

const (
	TaxRatesTypeNumber        TaxRatesType = "number"
	TaxRatesTypeMapOfTaxRates TaxRatesType = "mapOfTaxRates"
)

type TaxRates struct {
	Number        *float64           `queryParam:"inline" union:"member"`
	MapOfTaxRates map[string]float64 `queryParam:"inline" union:"member"`

	Type TaxRatesType
}

func CreateTaxRatesNumber(number float64) TaxRates {
	typ := TaxRatesTypeNumber

	return TaxRates{
		Number: &number,
		Type:   typ,
	}
}

func CreateTaxRatesMapOfTaxRates(mapOfTaxRates map[string]float64) TaxRates {
	typ := TaxRatesTypeMapOfTaxRates

	return TaxRates{
		MapOfTaxRates: mapOfTaxRates,
		Type:          typ,
	}
}

func (u *TaxRates) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TaxRatesTypeNumber,
			Value: &number,
		})
	}

	var mapOfTaxRates map[string]float64 = map[string]float64{}
	if err := utils.UnmarshalJSON(data, &mapOfTaxRates, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TaxRatesTypeMapOfTaxRates,
			Value: mapOfTaxRates,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for TaxRates", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for TaxRates", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(TaxRatesType)
	switch best.Type {
	case TaxRatesTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case TaxRatesTypeMapOfTaxRates:
		u.MapOfTaxRates = best.Value.(map[string]float64)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for TaxRates", string(data))
}

func (u TaxRates) MarshalJSON() ([]byte, error) {
	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.MapOfTaxRates != nil {
		return utils.MarshalJSON(u.MapOfTaxRates, "", true)
	}

	return nil, errors.New("could not marshal union type TaxRates: all fields are null")
}

// NotificationSettings - Notification preferences for this customer. Only provided fields are updated.
type NotificationSettings struct {
	// Whether to send invoice issued emails to this customer.
	InvoiceIssued *bool `json:"invoiceIssued,omitzero"`
	// Whether to send invoice paid emails to this customer.
	InvoicePaid *bool `json:"invoicePaid,omitzero"`
	// Whether to send renewal reminder emails to this customer.
	RenewalReminder *bool `json:"renewalReminder,omitzero"`
}

func (n *NotificationSettings) GetInvoiceIssued() *bool {
	if n == nil {
		return nil
	}
	return n.InvoiceIssued
}

func (n *NotificationSettings) GetInvoicePaid() *bool {
	if n == nil {
		return nil
	}
	return n.InvoicePaid
}

func (n *NotificationSettings) GetRenewalReminder() *bool {
	if n == nil {
		return nil
	}
	return n.RenewalReminder
}

type UpdateCustomerRequestBody struct {
	// Business tax registration identifier. Sample values: 'GB123456789' for UK VAT, 'DE123456789' for German VAT, 'FR12345678901' for French VAT. Enables inter-company tax handling and exemption from standard tax collection. Assign null to delete the identifier.
	TaxID optionalnullable.OptionalNullable[string] `json:"taxId,omitzero"`
	// Merchant-defined identifier for this customer in their own system. Set to null to clear.
	ExternalID optionalnullable.OptionalNullable[string] `json:"externalId,omitzero"`
	TaxRates   *TaxRates                                 `json:"taxRates,omitzero"`
	// Notification preferences for this customer. Only provided fields are updated.
	NotificationSettings *NotificationSettings `json:"notificationSettings,omitzero"`
}

func (u UpdateCustomerRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateCustomerRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateCustomerRequestBody) GetTaxID() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.TaxID
}

func (u *UpdateCustomerRequestBody) GetExternalID() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.ExternalID
}

func (u *UpdateCustomerRequestBody) GetTaxRates() *TaxRates {
	if u == nil {
		return nil
	}
	return u.TaxRates
}

func (u *UpdateCustomerRequestBody) GetNotificationSettings() *NotificationSettings {
	if u == nil {
		return nil
	}
	return u.NotificationSettings
}

type UpdateCustomerRequest struct {
	// The unique identifier of the customer.
	ID   string                    `pathParam:"style=simple,explode=false,name=id"`
	Body UpdateCustomerRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateCustomerRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateCustomerRequest) GetBody() UpdateCustomerRequestBody {
	if u == nil {
		return UpdateCustomerRequestBody{}
	}
	return u.Body
}
