// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/models/components"
)

type UpdateOrderRequest struct {
	ID   string                        `pathParam:"style=simple,explode=false,name=id"`
	Body components.UpdateOrderRequest `request:"mediaType=application/json"`
}

func (u *UpdateOrderRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateOrderRequest) GetBody() components.UpdateOrderRequest {
	if u == nil {
		return components.UpdateOrderRequest{}
	}
	return u.Body
}
