// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type UpdateBillableMetricRequestBody struct {
	// Revised explanation of what the metric represents. Sample values: 'Language model token consumption', 'Database storage capacity used', 'Machine learning prediction API calls', 'AI-generated content items'
	Description *string `json:"description,omitzero"`
	// Updated label for the metric. Sample values: 'LLM Tokens', 'Database Storage', 'Prediction Requests', 'Content Generations'
	Name *string `json:"name,omitzero"`
	// Updated measurement unit. Common examples: 'tokens', 'GB', 'requests', 'items', 'hours'
	Unit *string `json:"unit,omitzero"`
	// Optional item tag, used to map this metric's invoice lines to an external accounting/tax identity. Send a new id to re-tag — the item must be filed under this charge's own product, and an archived item is rejected. An item from another product is refused with `ITEM_PRODUCT_MISMATCH`: a tag is an accounting grouping and does not move the charge between products, and no field here could move it back. Re-file the item to move every charge anchored to it together. Send `null` to untag. Every line item whose invoice has not closed reports this charge's current tag, so a re-tag takes effect on the bill in progress and on any generated ahead of it — no further action, and no window to wait for. Lines on a closed invoice keep the item recorded at close and never move. Un-tagging works the same way: those lines report no item.
	ItemID optionalnullable.OptionalNullable[string] `json:"itemId,omitzero"`
	// CloudEvents type for meter routing.
	EventType optionalnullable.OptionalNullable[string] `json:"eventType,omitzero"`
	// JSONPath to extract a numeric value from event data. Must start with `$.` (example: `$.amount` or `$.payload.bytes`).
	ValueProperty optionalnullable.OptionalNullable[string] `json:"valueProperty,omitzero"`
	// Map of dimension name to JSONPath for group-by queries. Each value must start with `$.` (example: `$.region`).
	GroupBy optionalnullable.OptionalNullable[map[string]string] `json:"groupBy,omitzero"`
	// Only count events after this timestamp.
	EventFrom optionalnullable.OptionalNullable[time.Time] `json:"eventFrom,omitzero"`
}

func (u UpdateBillableMetricRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateBillableMetricRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateBillableMetricRequestBody) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateBillableMetricRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateBillableMetricRequestBody) GetUnit() *string {
	if u == nil {
		return nil
	}
	return u.Unit
}

func (u *UpdateBillableMetricRequestBody) GetItemID() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.ItemID
}

func (u *UpdateBillableMetricRequestBody) GetEventType() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.EventType
}

func (u *UpdateBillableMetricRequestBody) GetValueProperty() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.ValueProperty
}

func (u *UpdateBillableMetricRequestBody) GetGroupBy() optionalnullable.OptionalNullable[map[string]string] {
	if u == nil {
		return nil
	}
	return u.GroupBy
}

func (u *UpdateBillableMetricRequestBody) GetEventFrom() optionalnullable.OptionalNullable[time.Time] {
	if u == nil {
		return nil
	}
	return u.EventFrom
}

type UpdateBillableMetricRequest struct {
	ID   string                          `pathParam:"style=simple,explode=false,name=id"`
	Body UpdateBillableMetricRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateBillableMetricRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateBillableMetricRequest) GetBody() UpdateBillableMetricRequestBody {
	if u == nil {
		return UpdateBillableMetricRequestBody{}
	}
	return u.Body
}
