// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/internal/utils"
)

type UpdateItemRequestBody struct {
	Name     *string        `json:"name,omitzero"`
	Metadata map[string]any `json:"metadata,omitzero"`
}

func (u UpdateItemRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateItemRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateItemRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateItemRequestBody) GetMetadata() map[string]any {
	if u == nil {
		return nil
	}
	return u.Metadata
}

type UpdateItemRequest struct {
	// The unique identifier of the item
	ID   string                `pathParam:"style=simple,explode=false,name=id"`
	Body UpdateItemRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateItemRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateItemRequest) GetBody() UpdateItemRequestBody {
	if u == nil {
		return UpdateItemRequestBody{}
	}
	return u.Body
}
