// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/models/components"
	"github.com/paygentic/sdk-go/optionalnullable"
)

// UpdatePriceModel - The pricing model to be used, which can be standard, dynamic, volume-based, or percentage-based.
type UpdatePriceModel string

const (
	UpdatePriceModelStandard   UpdatePriceModel = "standard"
	UpdatePriceModelDynamic    UpdatePriceModel = "dynamic"
	UpdatePriceModelVolume     UpdatePriceModel = "volume"
	UpdatePriceModelPercentage UpdatePriceModel = "percentage"
)

func (e UpdatePriceModel) ToPointer() *UpdatePriceModel {
	return &e
}
func (e *UpdatePriceModel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "standard":
		fallthrough
	case "dynamic":
		fallthrough
	case "volume":
		fallthrough
	case "percentage":
		*e = UpdatePriceModel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdatePriceModel: %v", v)
	}
}

// UpdatePricePaymentTerm - Billing timing preference. For billable metrics: 'instant' (charges immediately) or 'in_arrears' (charges at period end). For fees: 'in_advance' (charges upfront) or 'in_arrears' (charges at period end).
type UpdatePricePaymentTerm string

const (
	UpdatePricePaymentTermInstant   UpdatePricePaymentTerm = "instant"
	UpdatePricePaymentTermInArrears UpdatePricePaymentTerm = "in_arrears"
	UpdatePricePaymentTermInAdvance UpdatePricePaymentTerm = "in_advance"
)

func (e UpdatePricePaymentTerm) ToPointer() *UpdatePricePaymentTerm {
	return &e
}
func (e *UpdatePricePaymentTerm) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "instant":
		fallthrough
	case "in_arrears":
		fallthrough
	case "in_advance":
		*e = UpdatePricePaymentTerm(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdatePricePaymentTerm: %v", v)
	}
}

type UpdatePriceRequestBody struct {
	// Unique identifier for a billable metric
	BillableMetricID *string `json:"billableMetricId,omitzero"`
	// Updated invoice line item label. Sample values: 'LLM Token Usage', 'Storage Charges', 'API Call Fees'
	InvoiceDisplayName *string `json:"invoiceDisplayName,omitzero"`
	// The pricing model to be used, which can be standard, dynamic, volume-based, or percentage-based.
	Model      *UpdatePriceModel                `json:"model,omitzero"`
	Properties *components.PricePropertiesUnion `json:"properties,omitzero"`
	// Billing timing preference. For billable metrics: 'instant' (charges immediately) or 'in_arrears' (charges at period end). For fees: 'in_advance' (charges upfront) or 'in_arrears' (charges at period end).
	PaymentTerm *UpdatePricePaymentTerm `json:"paymentTerm,omitzero"`
	// ISO 8601 duration for recurring fees (e.g., 'P1M' for monthly, 'P1Y' for yearly, or 'P0D' for one-time)
	BillingCadence optionalnullable.OptionalNullable[string] `json:"billingCadence,omitzero"`
	// Feature to associate. Set to null to remove existing feature. Omit to leave unchanged.
	Feature optionalnullable.OptionalNullable[components.PriceFeatureInput] `json:"feature,omitzero"`
	// When true, grants applied to a subscription will discount usage charged by this price. Only supported for standard metered prices.
	GrantDiscountEnabled *bool `json:"grantDiscountEnabled,omitzero"`
}

func (u UpdatePriceRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePriceRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePriceRequestBody) GetBillableMetricID() *string {
	if u == nil {
		return nil
	}
	return u.BillableMetricID
}

func (u *UpdatePriceRequestBody) GetInvoiceDisplayName() *string {
	if u == nil {
		return nil
	}
	return u.InvoiceDisplayName
}

func (u *UpdatePriceRequestBody) GetModel() *UpdatePriceModel {
	if u == nil {
		return nil
	}
	return u.Model
}

func (u *UpdatePriceRequestBody) GetProperties() *components.PricePropertiesUnion {
	if u == nil {
		return nil
	}
	return u.Properties
}

func (u *UpdatePriceRequestBody) GetPaymentTerm() *UpdatePricePaymentTerm {
	if u == nil {
		return nil
	}
	return u.PaymentTerm
}

func (u *UpdatePriceRequestBody) GetBillingCadence() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.BillingCadence
}

func (u *UpdatePriceRequestBody) GetFeature() optionalnullable.OptionalNullable[components.PriceFeatureInput] {
	if u == nil {
		return nil
	}
	return u.Feature
}

func (u *UpdatePriceRequestBody) GetGrantDiscountEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.GrantDiscountEnabled
}

type UpdatePriceRequest struct {
	// The unique identifier of the price
	ID   string                 `pathParam:"style=simple,explode=false,name=id"`
	Body UpdatePriceRequestBody `request:"mediaType=application/json"`
}

func (u *UpdatePriceRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdatePriceRequest) GetBody() UpdatePriceRequestBody {
	if u == nil {
		return UpdatePriceRequestBody{}
	}
	return u.Body
}
