// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
)

type UpdateExternalReferenceRequestBody struct {
	ExternalLabel optionalnullable.OptionalNullable[string] `json:"externalLabel,omitzero"`
	Metadata      map[string]any                            `json:"metadata,omitzero"`
	IsPrimary     *bool                                     `json:"isPrimary,omitzero"`
	IsDefault     *bool                                     `json:"isDefault,omitzero"`
}

func (u UpdateExternalReferenceRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateExternalReferenceRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateExternalReferenceRequestBody) GetExternalLabel() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.ExternalLabel
}

func (u *UpdateExternalReferenceRequestBody) GetMetadata() map[string]any {
	if u == nil {
		return nil
	}
	return u.Metadata
}

func (u *UpdateExternalReferenceRequestBody) GetIsPrimary() *bool {
	if u == nil {
		return nil
	}
	return u.IsPrimary
}

func (u *UpdateExternalReferenceRequestBody) GetIsDefault() *bool {
	if u == nil {
		return nil
	}
	return u.IsDefault
}

type UpdateExternalReferenceRequest struct {
	// The unique identifier of the external reference
	ID   string                             `pathParam:"style=simple,explode=false,name=id"`
	Body UpdateExternalReferenceRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateExternalReferenceRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateExternalReferenceRequest) GetBody() UpdateExternalReferenceRequestBody {
	if u == nil {
		return UpdateExternalReferenceRequestBody{}
	}
	return u.Body
}
