// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type UpdateProductRequestBody struct {
	// Revised product summary shown to customers. Sample values: 'Language model API access', 'Data processing and analytics service', 'AI-powered content creation platform'
	Description *string `json:"description,omitzero"`
	// Updated product title visible to customers. Sample values: 'LLM API Service', 'Data Platform', 'AI Content Generator'
	Name *string `json:"name,omitzero"`
}

func (u *UpdateProductRequestBody) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateProductRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

type UpdateProductRequest struct {
	// The unique identifier of the product
	ID   string                   `pathParam:"style=simple,explode=false,name=id"`
	Body UpdateProductRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateProductRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateProductRequest) GetBody() UpdateProductRequestBody {
	if u == nil {
		return UpdateProductRequestBody{}
	}
	return u.Body
}
