// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type VoidEntitlementGrantRequest struct {
	// The unique identifier of the entitlement.
	EntitlementID string `pathParam:"style=simple,explode=false,name=entitlementId"`
	// The unique identifier of the grant to void.
	GrantID string `pathParam:"style=simple,explode=false,name=grantId"`
}

func (v *VoidEntitlementGrantRequest) GetEntitlementID() string {
	if v == nil {
		return ""
	}
	return v.EntitlementID
}

func (v *VoidEntitlementGrantRequest) GetGrantID() string {
	if v == nil {
		return ""
	}
	return v.GrantID
}
