// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ApprovalListObject string

const (
	ApprovalListObjectList ApprovalListObject = "list"
)

func (e ApprovalListObject) ToPointer() *ApprovalListObject {
	return &e
}
func (e *ApprovalListObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ApprovalListObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ApprovalListObject: %v", v)
	}
}

type ApprovalList struct {
	Object ApprovalListObject `json:"object"`
	Data   []SchemasApproval  `json:"data"`
	// Offset-based pagination response.
	Pagination OffsetPagination `json:"pagination"`
}

func (a *ApprovalList) GetObject() ApprovalListObject {
	if a == nil {
		return ApprovalListObject("")
	}
	return a.Object
}

func (a *ApprovalList) GetData() []SchemasApproval {
	if a == nil {
		return []SchemasApproval{}
	}
	return a.Data
}

func (a *ApprovalList) GetPagination() OffsetPagination {
	if a == nil {
		return OffsetPagination{}
	}
	return a.Pagination
}
