// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type BatchUsageEventResponseObject string

const (
	BatchUsageEventResponseObjectBatchUsageEvents BatchUsageEventResponseObject = "batchUsageEvents"
)

func (e BatchUsageEventResponseObject) ToPointer() *BatchUsageEventResponseObject {
	return &e
}
func (e *BatchUsageEventResponseObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "batchUsageEvents":
		*e = BatchUsageEventResponseObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BatchUsageEventResponseObject: %v", v)
	}
}

type Failed struct {
	// Error message describing why the event failed
	Error string `json:"error"`
	// Idempotency key of the failed event for identification
	IdempotencyKey string `json:"idempotencyKey"`
	// Index of the failed event in the original request array
	Index int64 `json:"index"`
}

func (f *Failed) GetError() string {
	if f == nil {
		return ""
	}
	return f.Error
}

func (f *Failed) GetIdempotencyKey() string {
	if f == nil {
		return ""
	}
	return f.IdempotencyKey
}

func (f *Failed) GetIndex() int64 {
	if f == nil {
		return 0
	}
	return f.Index
}

// Summary of batch processing results
type Summary struct {
	// Number of events that failed to be created
	Failed int64 `json:"failed"`
	// Number of successfully created events
	Successful int64 `json:"successful"`
	// Total number of events in the batch
	Total int64 `json:"total"`
}

func (s *Summary) GetFailed() int64 {
	if s == nil {
		return 0
	}
	return s.Failed
}

func (s *Summary) GetSuccessful() int64 {
	if s == nil {
		return 0
	}
	return s.Successful
}

func (s *Summary) GetTotal() int64 {
	if s == nil {
		return 0
	}
	return s.Total
}

type BatchUsageEventResponse struct {
	Object BatchUsageEventResponseObject `json:"object"`
	// Array of events that failed to be created with error details
	Failed []Failed `json:"failed"`
	// Array of successfully created usage events
	Successful []UsageEvent `json:"successful"`
	// Summary of batch processing results
	Summary Summary `json:"summary"`
}

func (b *BatchUsageEventResponse) GetObject() BatchUsageEventResponseObject {
	if b == nil {
		return BatchUsageEventResponseObject("")
	}
	return b.Object
}

func (b *BatchUsageEventResponse) GetFailed() []Failed {
	if b == nil {
		return []Failed{}
	}
	return b.Failed
}

func (b *BatchUsageEventResponse) GetSuccessful() []UsageEvent {
	if b == nil {
		return []UsageEvent{}
	}
	return b.Successful
}

func (b *BatchUsageEventResponse) GetSummary() Summary {
	if b == nil {
		return Summary{}
	}
	return b.Summary
}
