// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type BillableMetricObject string

const (
	BillableMetricObjectBillableMetric BillableMetricObject = "billableMetric"
)

func (e BillableMetricObject) ToPointer() *BillableMetricObject {
	return &e
}
func (e *BillableMetricObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "billableMetric":
		*e = BillableMetricObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillableMetricObject: %v", v)
	}
}

type BillableMetricAggregation string

const (
	BillableMetricAggregationSum         BillableMetricAggregation = "SUM"
	BillableMetricAggregationCount       BillableMetricAggregation = "COUNT"
	BillableMetricAggregationAvg         BillableMetricAggregation = "AVG"
	BillableMetricAggregationMin         BillableMetricAggregation = "MIN"
	BillableMetricAggregationMax         BillableMetricAggregation = "MAX"
	BillableMetricAggregationUniqueCount BillableMetricAggregation = "UNIQUE_COUNT"
	BillableMetricAggregationLatest      BillableMetricAggregation = "LATEST"
)

func (e BillableMetricAggregation) ToPointer() *BillableMetricAggregation {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BillableMetricAggregation) IsExact() bool {
	if e != nil {
		switch *e {
		case "SUM", "COUNT", "AVG", "MIN", "MAX", "UNIQUE_COUNT", "LATEST":
			return true
		}
	}
	return false
}

type BillableMetric struct {
	// Unique identifier for a billable metric
	ID          string                    `json:"id"`
	Object      *BillableMetricObject     `default:"billableMetric" json:"object"`
	Aggregation BillableMetricAggregation `json:"aggregation"`
	CreatedAt   time.Time                 `json:"createdAt"`
	Description string                    `json:"description"`
	// Unique identifier for an organization
	MerchantID string `json:"merchantId"`
	Name       string `json:"name"`
	// Unique identifier for a product
	ProductID     string                                               `json:"productId"`
	Unit          string                                               `json:"unit"`
	UpdatedAt     time.Time                                            `json:"updatedAt"`
	EventType     optionalnullable.OptionalNullable[string]            `json:"eventType,omitzero"`
	ValueProperty optionalnullable.OptionalNullable[string]            `json:"valueProperty,omitzero"`
	GroupBy       optionalnullable.OptionalNullable[map[string]string] `json:"groupBy,omitzero"`
	EventFrom     optionalnullable.OptionalNullable[time.Time]         `json:"eventFrom,omitzero"`
}

func (b BillableMetric) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillableMetric) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BillableMetric) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BillableMetric) GetObject() *BillableMetricObject {
	if b == nil {
		return nil
	}
	return b.Object
}

func (b *BillableMetric) GetAggregation() BillableMetricAggregation {
	if b == nil {
		return BillableMetricAggregation("")
	}
	return b.Aggregation
}

func (b *BillableMetric) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}

func (b *BillableMetric) GetDescription() string {
	if b == nil {
		return ""
	}
	return b.Description
}

func (b *BillableMetric) GetMerchantID() string {
	if b == nil {
		return ""
	}
	return b.MerchantID
}

func (b *BillableMetric) GetName() string {
	if b == nil {
		return ""
	}
	return b.Name
}

func (b *BillableMetric) GetProductID() string {
	if b == nil {
		return ""
	}
	return b.ProductID
}

func (b *BillableMetric) GetUnit() string {
	if b == nil {
		return ""
	}
	return b.Unit
}

func (b *BillableMetric) GetUpdatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.UpdatedAt
}

func (b *BillableMetric) GetEventType() optionalnullable.OptionalNullable[string] {
	if b == nil {
		return nil
	}
	return b.EventType
}

func (b *BillableMetric) GetValueProperty() optionalnullable.OptionalNullable[string] {
	if b == nil {
		return nil
	}
	return b.ValueProperty
}

func (b *BillableMetric) GetGroupBy() optionalnullable.OptionalNullable[map[string]string] {
	if b == nil {
		return nil
	}
	return b.GroupBy
}

func (b *BillableMetric) GetEventFrom() optionalnullable.OptionalNullable[time.Time] {
	if b == nil {
		return nil
	}
	return b.EventFrom
}
