// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type CostObject string

const (
	CostObjectCost CostObject = "cost"
)

func (e CostObject) ToPointer() *CostObject {
	return &e
}
func (e *CostObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "cost":
		*e = CostObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CostObject: %v", v)
	}
}

type CostType string

const (
	CostTypeMetered CostType = "metered"
)

func (e CostType) ToPointer() *CostType {
	return &e
}
func (e *CostType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "metered":
		*e = CostType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CostType: %v", v)
	}
}

type CostAggregation string

const (
	CostAggregationSum         CostAggregation = "SUM"
	CostAggregationCount       CostAggregation = "COUNT"
	CostAggregationAvg         CostAggregation = "AVG"
	CostAggregationMin         CostAggregation = "MIN"
	CostAggregationMax         CostAggregation = "MAX"
	CostAggregationUniqueCount CostAggregation = "UNIQUE_COUNT"
	CostAggregationLatest      CostAggregation = "LATEST"
)

func (e CostAggregation) ToPointer() *CostAggregation {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CostAggregation) IsExact() bool {
	if e != nil {
		switch *e {
		case "SUM", "COUNT", "AVG", "MIN", "MAX", "UNIQUE_COUNT", "LATEST":
			return true
		}
	}
	return false
}

type Cost struct {
	// Unique identifier for a cost
	ID       string      `json:"id"`
	Object   *CostObject `default:"cost" json:"object"`
	Type     CostType    `json:"type"`
	Name     string      `json:"name"`
	Currency string      `json:"currency"`
	// Decimal as string to avoid floating point precision loss.
	UnitCost      string                                               `json:"unitCost"`
	Unit          optionalnullable.OptionalNullable[string]            `json:"unit,omitzero"`
	Aggregation   optionalnullable.OptionalNullable[CostAggregation]   `json:"aggregation,omitzero"`
	EventType     optionalnullable.OptionalNullable[string]            `json:"eventType,omitzero"`
	ValueProperty optionalnullable.OptionalNullable[string]            `json:"valueProperty,omitzero"`
	GroupBy       optionalnullable.OptionalNullable[map[string]string] `json:"groupBy,omitzero"`
	// Unique identifier for a product
	ProductID string `json:"productId"`
	// Unique identifier for an organization
	MerchantID string    `json:"merchantId"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
	// Soft-delete timestamp. Always null for active costs returned by the API.
	DeletedAt optionalnullable.OptionalNullable[time.Time] `json:"deletedAt,omitzero"`
}

func (c Cost) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Cost) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Cost) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *Cost) GetObject() *CostObject {
	if c == nil {
		return nil
	}
	return c.Object
}

func (c *Cost) GetType() CostType {
	if c == nil {
		return CostType("")
	}
	return c.Type
}

func (c *Cost) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *Cost) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *Cost) GetUnitCost() string {
	if c == nil {
		return ""
	}
	return c.UnitCost
}

func (c *Cost) GetUnit() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Unit
}

func (c *Cost) GetAggregation() optionalnullable.OptionalNullable[CostAggregation] {
	if c == nil {
		return nil
	}
	return c.Aggregation
}

func (c *Cost) GetEventType() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.EventType
}

func (c *Cost) GetValueProperty() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.ValueProperty
}

func (c *Cost) GetGroupBy() optionalnullable.OptionalNullable[map[string]string] {
	if c == nil {
		return nil
	}
	return c.GroupBy
}

func (c *Cost) GetProductID() string {
	if c == nil {
		return ""
	}
	return c.ProductID
}

func (c *Cost) GetMerchantID() string {
	if c == nil {
		return ""
	}
	return c.MerchantID
}

func (c *Cost) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *Cost) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *Cost) GetDeletedAt() optionalnullable.OptionalNullable[time.Time] {
	if c == nil {
		return nil
	}
	return c.DeletedAt
}
