// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

type CostReportResponseObject string

const (
	CostReportResponseObjectCostReport CostReportResponseObject = "cost_report"
)

func (e CostReportResponseObject) ToPointer() *CostReportResponseObject {
	return &e
}
func (e *CostReportResponseObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "cost_report":
		*e = CostReportResponseObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CostReportResponseObject: %v", v)
	}
}

type Period struct {
	From time.Time `json:"from"`
	To   time.Time `json:"to"`
}

func (p Period) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Period) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Period) GetFrom() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.From
}

func (p *Period) GetTo() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.To
}

type Pagination struct {
	Total  int64 `json:"total"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (p *Pagination) GetTotal() int64 {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *Pagination) GetLimit() int64 {
	if p == nil {
		return 0
	}
	return p.Limit
}

func (p *Pagination) GetOffset() int64 {
	if p == nil {
		return 0
	}
	return p.Offset
}

type CostReportResponse struct {
	Object *CostReportResponseObject `default:"cost_report" json:"object"`
	// ISO 4217 currency code for all monetary values in this response.
	Currency string `json:"currency"`
	Period   Period `json:"period"`
	// The active grouping dimension (e.g. 'cost', 'customer', or a dynamic dimension key).
	GroupBy string `json:"groupBy"`
	// Sum of cost across all groups (not just top N).
	TotalCost float64 `json:"totalCost"`
	// Sum of quantity across all groups.
	TotalQuantity float64 `json:"totalQuantity"`
	// Top N groups plus an 'Other' bucket aggregating the remainder.
	Groups []CostReportGroup `json:"groups"`
	// Time-bucketed breakdown per group. Keys in each window's 'groups' object correspond to CostReportGroup.key. The 'Other' bucket key is '__other__'.
	TimeSeries []CostReportTimeSeries `json:"timeSeries"`
	// Dimension keys available for further drill-down (populated when a single cost is filtered).
	AvailableDimensions []string `json:"availableDimensions"`
	// Non-fatal warnings, e.g. costs that could not be queried.
	Warnings   []string   `json:"warnings,omitzero"`
	Pagination Pagination `json:"pagination"`
}

func (c CostReportResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CostReportResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CostReportResponse) GetObject() *CostReportResponseObject {
	if c == nil {
		return nil
	}
	return c.Object
}

func (c *CostReportResponse) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *CostReportResponse) GetPeriod() Period {
	if c == nil {
		return Period{}
	}
	return c.Period
}

func (c *CostReportResponse) GetGroupBy() string {
	if c == nil {
		return ""
	}
	return c.GroupBy
}

func (c *CostReportResponse) GetTotalCost() float64 {
	if c == nil {
		return 0.0
	}
	return c.TotalCost
}

func (c *CostReportResponse) GetTotalQuantity() float64 {
	if c == nil {
		return 0.0
	}
	return c.TotalQuantity
}

func (c *CostReportResponse) GetGroups() []CostReportGroup {
	if c == nil {
		return []CostReportGroup{}
	}
	return c.Groups
}

func (c *CostReportResponse) GetTimeSeries() []CostReportTimeSeries {
	if c == nil {
		return []CostReportTimeSeries{}
	}
	return c.TimeSeries
}

func (c *CostReportResponse) GetAvailableDimensions() []string {
	if c == nil {
		return []string{}
	}
	return c.AvailableDimensions
}

func (c *CostReportResponse) GetWarnings() []string {
	if c == nil {
		return nil
	}
	return c.Warnings
}

func (c *CostReportResponse) GetPagination() Pagination {
	if c == nil {
		return Pagination{}
	}
	return c.Pagination
}
