// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type CreateBillingScheduleRequestAlignmentPolicy string

const (
	CreateBillingScheduleRequestAlignmentPolicyAnchor   CreateBillingScheduleRequestAlignmentPolicy = "anchor"
	CreateBillingScheduleRequestAlignmentPolicyCalendar CreateBillingScheduleRequestAlignmentPolicy = "calendar"
	CreateBillingScheduleRequestAlignmentPolicyCoterm   CreateBillingScheduleRequestAlignmentPolicy = "coterm"
)

func (e CreateBillingScheduleRequestAlignmentPolicy) ToPointer() *CreateBillingScheduleRequestAlignmentPolicy {
	return &e
}
func (e *CreateBillingScheduleRequestAlignmentPolicy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "anchor":
		fallthrough
	case "calendar":
		fallthrough
	case "coterm":
		*e = CreateBillingScheduleRequestAlignmentPolicy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateBillingScheduleRequestAlignmentPolicy: %v", v)
	}
}

type CreateBillingScheduleRequestProrationPolicy string

const (
	CreateBillingScheduleRequestProrationPolicyNone  CreateBillingScheduleRequestProrationPolicy = "none"
	CreateBillingScheduleRequestProrationPolicyDaily CreateBillingScheduleRequestProrationPolicy = "daily"
)

func (e CreateBillingScheduleRequestProrationPolicy) ToPointer() *CreateBillingScheduleRequestProrationPolicy {
	return &e
}
func (e *CreateBillingScheduleRequestProrationPolicy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "none":
		fallthrough
	case "daily":
		*e = CreateBillingScheduleRequestProrationPolicy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateBillingScheduleRequestProrationPolicy: %v", v)
	}
}

type CreateBillingScheduleRequestPeriodPreset string

const (
	CreateBillingScheduleRequestPeriodPresetSingle CreateBillingScheduleRequestPeriodPreset = "single"
	CreateBillingScheduleRequestPeriodPresetP1M    CreateBillingScheduleRequestPeriodPreset = "P1M"
	CreateBillingScheduleRequestPeriodPresetP3M    CreateBillingScheduleRequestPeriodPreset = "P3M"
	CreateBillingScheduleRequestPeriodPresetP6M    CreateBillingScheduleRequestPeriodPreset = "P6M"
	CreateBillingScheduleRequestPeriodPresetP1Y    CreateBillingScheduleRequestPeriodPreset = "P1Y"
	CreateBillingScheduleRequestPeriodPresetCustom CreateBillingScheduleRequestPeriodPreset = "custom"
)

func (e CreateBillingScheduleRequestPeriodPreset) ToPointer() *CreateBillingScheduleRequestPeriodPreset {
	return &e
}
func (e *CreateBillingScheduleRequestPeriodPreset) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "single":
		fallthrough
	case "P1M":
		fallthrough
	case "P3M":
		fallthrough
	case "P6M":
		fallthrough
	case "P1Y":
		fallthrough
	case "custom":
		*e = CreateBillingScheduleRequestPeriodPreset(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateBillingScheduleRequestPeriodPreset: %v", v)
	}
}

type CreateBillingScheduleRequest struct {
	OrderID             *string                                      `json:"orderId,omitzero"`
	SubscriptionID      *string                                      `json:"subscriptionId,omitzero"`
	StartDate           time.Time                                    `json:"startDate"`
	EndDate             time.Time                                    `json:"endDate"`
	BillingAnchor       time.Time                                    `json:"billingAnchor"`
	AlignmentPolicy     *CreateBillingScheduleRequestAlignmentPolicy `json:"alignmentPolicy,omitzero"`
	ProrationPolicy     *CreateBillingScheduleRequestProrationPolicy `json:"prorationPolicy,omitzero"`
	PaymentTermDays     optionalnullable.OptionalNullable[int64]     `json:"paymentTermDays,omitzero"`
	PeriodPreset        *CreateBillingScheduleRequestPeriodPreset    `json:"periodPreset,omitzero"`
	CustomPeriodWindows []any                                        `json:"customPeriodWindows,omitzero"`
	Metadata            map[string]any                               `json:"metadata,omitzero"`
}

func (c CreateBillingScheduleRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateBillingScheduleRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateBillingScheduleRequest) GetOrderID() *string {
	if c == nil {
		return nil
	}
	return c.OrderID
}

func (c *CreateBillingScheduleRequest) GetSubscriptionID() *string {
	if c == nil {
		return nil
	}
	return c.SubscriptionID
}

func (c *CreateBillingScheduleRequest) GetStartDate() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.StartDate
}

func (c *CreateBillingScheduleRequest) GetEndDate() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.EndDate
}

func (c *CreateBillingScheduleRequest) GetBillingAnchor() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.BillingAnchor
}

func (c *CreateBillingScheduleRequest) GetAlignmentPolicy() *CreateBillingScheduleRequestAlignmentPolicy {
	if c == nil {
		return nil
	}
	return c.AlignmentPolicy
}

func (c *CreateBillingScheduleRequest) GetProrationPolicy() *CreateBillingScheduleRequestProrationPolicy {
	if c == nil {
		return nil
	}
	return c.ProrationPolicy
}

func (c *CreateBillingScheduleRequest) GetPaymentTermDays() optionalnullable.OptionalNullable[int64] {
	if c == nil {
		return nil
	}
	return c.PaymentTermDays
}

func (c *CreateBillingScheduleRequest) GetPeriodPreset() *CreateBillingScheduleRequestPeriodPreset {
	if c == nil {
		return nil
	}
	return c.PeriodPreset
}

func (c *CreateBillingScheduleRequest) GetCustomPeriodWindows() []any {
	if c == nil {
		return nil
	}
	return c.CustomPeriodWindows
}

func (c *CreateBillingScheduleRequest) GetMetadata() map[string]any {
	if c == nil {
		return nil
	}
	return c.Metadata
}
