// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type CreateOrderLineItemRequest struct {
	ItemID             optionalnullable.OptionalNullable[string] `json:"itemId,omitzero"`
	Description        optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	Quantity           string                                    `json:"quantity"`
	ListUnitPrice      string                                    `json:"listUnitPrice"`
	DiscountUnitAmount *string                                   `json:"discountUnitAmount,omitzero"`
	UnitPrice          string                                    `json:"unitPrice"`
	TotalPrice         string                                    `json:"totalPrice"`
	Metadata           map[string]any                            `json:"metadata,omitzero"`
	TermStartDate      *time.Time                                `json:"termStartDate,omitzero"`
	TermEndDate        *time.Time                                `json:"termEndDate,omitzero"`
}

func (c CreateOrderLineItemRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrderLineItemRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrderLineItemRequest) GetItemID() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.ItemID
}

func (c *CreateOrderLineItemRequest) GetDescription() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateOrderLineItemRequest) GetQuantity() string {
	if c == nil {
		return ""
	}
	return c.Quantity
}

func (c *CreateOrderLineItemRequest) GetListUnitPrice() string {
	if c == nil {
		return ""
	}
	return c.ListUnitPrice
}

func (c *CreateOrderLineItemRequest) GetDiscountUnitAmount() *string {
	if c == nil {
		return nil
	}
	return c.DiscountUnitAmount
}

func (c *CreateOrderLineItemRequest) GetUnitPrice() string {
	if c == nil {
		return ""
	}
	return c.UnitPrice
}

func (c *CreateOrderLineItemRequest) GetTotalPrice() string {
	if c == nil {
		return ""
	}
	return c.TotalPrice
}

func (c *CreateOrderLineItemRequest) GetMetadata() map[string]any {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateOrderLineItemRequest) GetTermStartDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.TermStartDate
}

func (c *CreateOrderLineItemRequest) GetTermEndDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.TermEndDate
}
