// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateDisputeRequest struct {
	// Customer explanation for challenging the consumption event. Sample values: 'Token count appears incorrect for this request', 'Storage charges don't match actual usage', 'API call was made during maintenance window', 'Inference request failed but still charged'
	Message string `json:"message"`
	// Usage event identifier being challenged. Sample values: 'usg_abc123xyz', 'usg_789def456'
	UsageEventID string `json:"usageEventId"`
}

func (c *CreateDisputeRequest) GetMessage() string {
	if c == nil {
		return ""
	}
	return c.Message
}

func (c *CreateDisputeRequest) GetUsageEventID() string {
	if c == nil {
		return ""
	}
	return c.UsageEventID
}
