// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

type CreateUsageEventRequestProperty struct {
	// Identifier for the consumption metric being reported. Sample metrics: token consumption, storage capacity, inference requests, training hours, data transfer volume
	BillableMetricID string `json:"billableMetricId"`
	// Custom per-unit price in decimal format. The total charge is calculated as price × quantity. Sample values: '0.125' sets $0.125 per unit, '2.50' sets $2.50 per unit. Must be within the minPrice and maxPrice bounds defined for the dynamic price model.
	Price *string `json:"price,omitzero"`
	// Measured consumption amount for this metric. Must be a positive whole number. Sample values: 2500 tokens consumed, 42 gigabytes stored, 750 API calls executed, 8 compute hours utilized, 120 images generated
	Quantity int64 `json:"quantity"`
}

func (c *CreateUsageEventRequestProperty) GetBillableMetricID() string {
	if c == nil {
		return ""
	}
	return c.BillableMetricID
}

func (c *CreateUsageEventRequestProperty) GetPrice() *string {
	if c == nil {
		return nil
	}
	return c.Price
}

func (c *CreateUsageEventRequestProperty) GetQuantity() int64 {
	if c == nil {
		return 0
	}
	return c.Quantity
}

type CreateUsageEventRequest struct {
	// Customer identifier that generated this consumption event. Sample values: 'cus_abc123xyz', 'cus_789def456'
	CustomerID string `json:"customerId"`
	// Commitment identifier for this consumption event. Sample values: 'com_abc123xyz', 'com_789def456'
	EntitlementID *string `json:"entitlementId,omitzero"`
	// Unique deduplication key preventing duplicate event processing. Sample values: 'usg_2024_01_15_abc123', 'event_wallet_xyz789', 'consumption_ref_456def'
	IdempotencyKey string `json:"idempotencyKey"`
	// Merchant organization identifier owning this consumption event. Sample values: 'org_abc123xyz', 'org_789def456'
	MerchantID string `json:"merchantId"`
	// Custom key-value attributes providing context about the consumption event. Sample values: {"model_name": "claude-3-opus", "input_tokens": "1500", "output_tokens": "800"} or {"storage_tier": "premium", "data_center": "eu-west-1", "encryption": "enabled"} or {"image_resolution": "1024x1024", "generation_model": "stable-diffusion-xl"}
	Metadata   map[string]string                 `json:"metadata,omitzero"`
	Properties []CreateUsageEventRequestProperty `json:"properties"`
	// Actual occurrence timestamp for the consumption event in ISO 8601 format. Sample values: '2024-01-15T10:30:00Z', '2024-02-01T14:45:30Z'. Represents when the event occurred, not when Paygentic received it.
	Timestamp time.Time `json:"timestamp"`
}

func (c CreateUsageEventRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateUsageEventRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateUsageEventRequest) GetCustomerID() string {
	if c == nil {
		return ""
	}
	return c.CustomerID
}

func (c *CreateUsageEventRequest) GetEntitlementID() *string {
	if c == nil {
		return nil
	}
	return c.EntitlementID
}

func (c *CreateUsageEventRequest) GetIdempotencyKey() string {
	if c == nil {
		return ""
	}
	return c.IdempotencyKey
}

func (c *CreateUsageEventRequest) GetMerchantID() string {
	if c == nil {
		return ""
	}
	return c.MerchantID
}

func (c *CreateUsageEventRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateUsageEventRequest) GetProperties() []CreateUsageEventRequestProperty {
	if c == nil {
		return []CreateUsageEventRequestProperty{}
	}
	return c.Properties
}

func (c *CreateUsageEventRequest) GetTimestamp() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.Timestamp
}
