// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CurrencyBreakdownEntry struct {
	// ISO 4217 currency code (uppercase, e.g. USD, EUR, GBP)
	Currency string `json:"currency"`
	// Revenue in dollars for this currency, excluding tax: invoices issued in the period plus completed payments
	NetRevenue string         `json:"netRevenue"`
	Invoices   InvoiceSummary `json:"invoices"`
	Payments   PaymentSummary `json:"payments"`
	// Time-bucketed revenue trend data for this currency
	Trend []RevenueTrendBucket `json:"trend"`
}

func (c *CurrencyBreakdownEntry) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *CurrencyBreakdownEntry) GetNetRevenue() string {
	if c == nil {
		return ""
	}
	return c.NetRevenue
}

func (c *CurrencyBreakdownEntry) GetInvoices() InvoiceSummary {
	if c == nil {
		return InvoiceSummary{}
	}
	return c.Invoices
}

func (c *CurrencyBreakdownEntry) GetPayments() PaymentSummary {
	if c == nil {
		return PaymentSummary{}
	}
	return c.Payments
}

func (c *CurrencyBreakdownEntry) GetTrend() []RevenueTrendBucket {
	if c == nil {
		return []RevenueTrendBucket{}
	}
	return c.Trend
}
