// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type CustomerPaymentSessionObject string

const (
	CustomerPaymentSessionObjectPaymentSession CustomerPaymentSessionObject = "paymentSession"
)

func (e CustomerPaymentSessionObject) ToPointer() *CustomerPaymentSessionObject {
	return &e
}
func (e *CustomerPaymentSessionObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "paymentSession":
		*e = CustomerPaymentSessionObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomerPaymentSessionObject: %v", v)
	}
}

type Mode string

const (
	ModePayment Mode = "payment"
	ModeSetup   Mode = "setup"
)

func (e Mode) ToPointer() *Mode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Mode) IsExact() bool {
	if e != nil {
		switch *e {
		case "payment", "setup":
			return true
		}
	}
	return false
}

type CustomerPaymentSessionStatus string

const (
	CustomerPaymentSessionStatusPending    CustomerPaymentSessionStatus = "pending"
	CustomerPaymentSessionStatusProcessing CustomerPaymentSessionStatus = "processing"
	CustomerPaymentSessionStatusCompleted  CustomerPaymentSessionStatus = "completed"
	CustomerPaymentSessionStatusFailed     CustomerPaymentSessionStatus = "failed"
	CustomerPaymentSessionStatusExpired    CustomerPaymentSessionStatus = "expired"
	CustomerPaymentSessionStatusCancelled  CustomerPaymentSessionStatus = "cancelled"
)

func (e CustomerPaymentSessionStatus) ToPointer() *CustomerPaymentSessionStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CustomerPaymentSessionStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "processing", "completed", "failed", "expired", "cancelled":
			return true
		}
	}
	return false
}

type CustomerPaymentSession struct {
	Object CustomerPaymentSessionObject `json:"object"`
	// Payment session identifier (e.g. `ps_...`).
	ID     string                       `json:"id"`
	Mode   Mode                         `json:"mode"`
	Status CustomerPaymentSessionStatus `json:"status"`
	// Hosted page URL. Redirect the customer here, or load it inside an iframe — when iframed, the page reports outcomes via `postMessage` (`payment_success` / `payment_error`) to the parent window.
	URL                string                                       `json:"url"`
	SuccessRedirectURL optionalnullable.OptionalNullable[string]    `json:"successRedirectUrl,omitzero"`
	FailureRedirectURL optionalnullable.OptionalNullable[string]    `json:"failureRedirectUrl,omitzero"`
	Metadata           map[string]any                               `json:"metadata,omitzero"`
	ExpiresAt          time.Time                                    `json:"expiresAt"`
	CompletedAt        optionalnullable.OptionalNullable[time.Time] `json:"completedAt,omitzero"`
	CreatedAt          time.Time                                    `json:"createdAt"`
}

func (c CustomerPaymentSession) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomerPaymentSession) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomerPaymentSession) GetObject() CustomerPaymentSessionObject {
	if c == nil {
		return CustomerPaymentSessionObject("")
	}
	return c.Object
}

func (c *CustomerPaymentSession) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CustomerPaymentSession) GetMode() Mode {
	if c == nil {
		return Mode("")
	}
	return c.Mode
}

func (c *CustomerPaymentSession) GetStatus() CustomerPaymentSessionStatus {
	if c == nil {
		return CustomerPaymentSessionStatus("")
	}
	return c.Status
}

func (c *CustomerPaymentSession) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

func (c *CustomerPaymentSession) GetSuccessRedirectURL() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.SuccessRedirectURL
}

func (c *CustomerPaymentSession) GetFailureRedirectURL() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.FailureRedirectURL
}

func (c *CustomerPaymentSession) GetMetadata() map[string]any {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CustomerPaymentSession) GetExpiresAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.ExpiresAt
}

func (c *CustomerPaymentSession) GetCompletedAt() optionalnullable.OptionalNullable[time.Time] {
	if c == nil {
		return nil
	}
	return c.CompletedAt
}

func (c *CustomerPaymentSession) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}
