// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

type CustomerObject string

const (
	CustomerObjectCustomer CustomerObject = "customer"
)

func (e CustomerObject) ToPointer() *CustomerObject {
	return &e
}
func (e *CustomerObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "customer":
		*e = CustomerObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomerObject: %v", v)
	}
}

type CustomerOrganization struct {
	ID            string   `json:"id"`
	Address       *Address `json:"address,omitzero"`
	BillingEmails []string `json:"billingEmails,omitzero"`
	Name          string   `json:"name"`
	Phone         *string  `json:"phone,omitzero"`
}

func (c CustomerOrganization) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomerOrganization) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomerOrganization) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CustomerOrganization) GetAddress() *Address {
	if c == nil {
		return nil
	}
	return c.Address
}

func (c *CustomerOrganization) GetBillingEmails() []string {
	if c == nil {
		return nil
	}
	return c.BillingEmails
}

func (c *CustomerOrganization) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomerOrganization) GetPhone() *string {
	if c == nil {
		return nil
	}
	return c.Phone
}

type NotificationSettings struct {
	// Whether to send invoice issued emails to this customer.
	InvoiceIssued bool `json:"invoiceIssued"`
	// Whether to send invoice paid emails to this customer.
	InvoicePaid bool `json:"invoicePaid"`
	// Whether to send renewal reminder emails to this customer.
	RenewalReminder bool `json:"renewalReminder"`
}

func (n *NotificationSettings) GetInvoiceIssued() bool {
	if n == nil {
		return false
	}
	return n.InvoiceIssued
}

func (n *NotificationSettings) GetInvoicePaid() bool {
	if n == nil {
		return false
	}
	return n.InvoicePaid
}

func (n *NotificationSettings) GetRenewalReminder() bool {
	if n == nil {
		return false
	}
	return n.RenewalReminder
}

type Customer struct {
	// Unique identifier for a customer
	ID     string          `json:"id"`
	Object *CustomerObject `default:"customer" json:"object"`
	// Unique identifier for an organization
	ConsumerID string    `json:"consumerId"`
	CreatedAt  time.Time `json:"createdAt"`
	// Unique identifier for an organization
	MerchantID   string                `json:"merchantId"`
	Organization *CustomerOrganization `json:"organization,omitzero"`
	// Business tax registration identifier. Sample values: 'GB123456789' for UK VAT, 'DE123456789' for German VAT, 'FR12345678901' for French VAT. Enables inter-company tax handling and exemption from standard tax collection.
	TaxID *string `json:"taxId,omitzero"`
	// Merchant-defined identifier for this customer in their own system.
	ExternalID *string `json:"externalId,omitzero"`
	// An object mapping plan IDs, metric IDs, or 'default' to a tax rate percentage (e.g., 13 for 13%)
	TaxRates  map[string]float64 `json:"taxRates,omitzero"`
	UpdatedAt time.Time          `json:"updatedAt"`
	// Indicates whether the consumer address is valid for tax calculation when using Paygentic Tax. If valid=false, tax calculation will be skipped and internal invoice flow with default tax rate will be used.
	ValidTaxAddress      ValidTaxAddress       `json:"validTaxAddress"`
	NotificationSettings *NotificationSettings `json:"notificationSettings,omitzero"`
}

func (c Customer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Customer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Customer) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *Customer) GetObject() *CustomerObject {
	if c == nil {
		return nil
	}
	return c.Object
}

func (c *Customer) GetConsumerID() string {
	if c == nil {
		return ""
	}
	return c.ConsumerID
}

func (c *Customer) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *Customer) GetMerchantID() string {
	if c == nil {
		return ""
	}
	return c.MerchantID
}

func (c *Customer) GetOrganization() *CustomerOrganization {
	if c == nil {
		return nil
	}
	return c.Organization
}

func (c *Customer) GetTaxID() *string {
	if c == nil {
		return nil
	}
	return c.TaxID
}

func (c *Customer) GetExternalID() *string {
	if c == nil {
		return nil
	}
	return c.ExternalID
}

func (c *Customer) GetTaxRates() map[string]float64 {
	if c == nil {
		return nil
	}
	return c.TaxRates
}

func (c *Customer) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *Customer) GetValidTaxAddress() ValidTaxAddress {
	if c == nil {
		return ValidTaxAddress{}
	}
	return c.ValidTaxAddress
}

func (c *Customer) GetNotificationSettings() *NotificationSettings {
	if c == nil {
		return nil
	}
	return c.NotificationSettings
}
