// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// EntitlementStatus - Current status of the entitlement.
type EntitlementStatus string

const (
	EntitlementStatusActive   EntitlementStatus = "active"
	EntitlementStatusCanceled EntitlementStatus = "canceled"
	EntitlementStatusExpired  EntitlementStatus = "expired"
)

func (e EntitlementStatus) ToPointer() *EntitlementStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EntitlementStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "canceled", "expired":
			return true
		}
	}
	return false
}
