// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type EntitlementObject string

const (
	EntitlementObjectEntitlement EntitlementObject = "entitlement"
)

func (e EntitlementObject) ToPointer() *EntitlementObject {
	return &e
}
func (e *EntitlementObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "entitlement":
		*e = EntitlementObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EntitlementObject: %v", v)
	}
}

// EntitlementStatus - Current status of the entitlement.
type EntitlementStatus string

const (
	EntitlementStatusActive   EntitlementStatus = "active"
	EntitlementStatusCanceled EntitlementStatus = "canceled"
	EntitlementStatusExpired  EntitlementStatus = "expired"
)

func (e EntitlementStatus) ToPointer() *EntitlementStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EntitlementStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "canceled", "expired":
			return true
		}
	}
	return false
}

type Entitlement struct {
	Object *EntitlementObject `default:"entitlement" json:"object"`
	// Unique identifier for the entitlement.
	ID string `json:"id"`
	// Unique identifier for a customer
	CustomerID string `json:"customerId"`
	// The feature this entitlement grants access to.
	FeatureID string `json:"featureId"`
	// The subscription this entitlement is associated with, if any.
	SubscriptionID optionalnullable.OptionalNullable[string] `json:"subscriptionId,omitzero"`
	// Current status of the entitlement.
	Status EntitlementStatus `json:"status"`
	// When the entitlement becomes active.
	ActiveFrom time.Time `json:"activeFrom"`
	// When the entitlement expires. Null means no expiration.
	ActiveTo optionalnullable.OptionalNullable[time.Time] `json:"activeTo,omitzero"`
	// Configuration values for static features.
	Config map[string]any `json:"config"`
	// Additional metadata for the entitlement.
	Metadata map[string]string `json:"metadata,omitzero"`
}

func (e Entitlement) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Entitlement) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *Entitlement) GetObject() *EntitlementObject {
	if e == nil {
		return nil
	}
	return e.Object
}

func (e *Entitlement) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *Entitlement) GetCustomerID() string {
	if e == nil {
		return ""
	}
	return e.CustomerID
}

func (e *Entitlement) GetFeatureID() string {
	if e == nil {
		return ""
	}
	return e.FeatureID
}

func (e *Entitlement) GetSubscriptionID() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.SubscriptionID
}

func (e *Entitlement) GetStatus() EntitlementStatus {
	if e == nil {
		return EntitlementStatus("")
	}
	return e.Status
}

func (e *Entitlement) GetActiveFrom() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.ActiveFrom
}

func (e *Entitlement) GetActiveTo() optionalnullable.OptionalNullable[time.Time] {
	if e == nil {
		return nil
	}
	return e.ActiveTo
}

func (e *Entitlement) GetConfig() map[string]any {
	if e == nil {
		return nil
	}
	return e.Config
}

func (e *Entitlement) GetMetadata() map[string]string {
	if e == nil {
		return nil
	}
	return e.Metadata
}
