// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

// FeatureTypeEnum - The type of feature: `boolean` (on/off), `static` (with config), or `metered` (usage-based).
type FeatureTypeEnum string

const (
	FeatureTypeEnumBoolean FeatureTypeEnum = "boolean"
	FeatureTypeEnumStatic  FeatureTypeEnum = "static"
	FeatureTypeEnumMetered FeatureTypeEnum = "metered"
)

func (e FeatureTypeEnum) ToPointer() *FeatureTypeEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FeatureTypeEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "boolean", "static", "metered":
			return true
		}
	}
	return false
}

// EntitlementAccessResultStatus - Current status of the entitlement.
type EntitlementAccessResultStatus string

const (
	EntitlementAccessResultStatusActive   EntitlementAccessResultStatus = "active"
	EntitlementAccessResultStatusCanceled EntitlementAccessResultStatus = "canceled"
	EntitlementAccessResultStatusExpired  EntitlementAccessResultStatus = "expired"
)

func (e EntitlementAccessResultStatus) ToPointer() *EntitlementAccessResultStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EntitlementAccessResultStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "canceled", "expired":
			return true
		}
	}
	return false
}

// EntitlementAccessResult - A customer's entitlement to a specific feature.
type EntitlementAccessResult struct {
	// Whether the customer currently has active access to this feature.
	HasAccess bool `json:"hasAccess"`
	// The unique key identifying the feature.
	FeatureKey string `json:"featureKey"`
	// The type of feature: `boolean` (on/off), `static` (with config), or `metered` (usage-based).
	FeatureType FeatureTypeEnum `json:"featureType"`
	// Configuration values for `static` features. Null for other types.
	Config optionalnullable.OptionalNullable[map[string]any] `json:"config,omitzero"`
	// Unique identifier for this entitlement.
	EntitlementID string `json:"entitlementId"`
	// Unique identifier for a product
	ProductID string `json:"productId"`
	// When the entitlement becomes active.
	ActiveFrom time.Time `json:"activeFrom"`
	// When the entitlement expires. Null means no expiration.
	ActiveTo optionalnullable.OptionalNullable[time.Time] `json:"activeTo,omitzero"`
	// Current status of the entitlement.
	Status EntitlementAccessResultStatus `json:"status"`
	// Remaining grant balance. Only present for `metered` features.
	Balance optionalnullable.OptionalNullable[float64] `json:"balance,omitzero"`
	// Total usage in the current period. Only present for `metered` features.
	UsageInPeriod optionalnullable.OptionalNullable[float64] `json:"usageInPeriod,omitzero"`
	// Amount of overage beyond granted balance. Only present for `metered` features.
	Overage optionalnullable.OptionalNullable[float64] `json:"overage,omitzero"`
	// Start of the current usage period. Only present for `metered` features with a usage period configured.
	CurrentPeriodStart optionalnullable.OptionalNullable[time.Time] `json:"currentPeriodStart,omitzero"`
	// End of the current usage period. Only present for `metered` features with a usage period configured.
	CurrentPeriodEnd optionalnullable.OptionalNullable[time.Time] `json:"currentPeriodEnd,omitzero"`
}

func (e EntitlementAccessResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntitlementAccessResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntitlementAccessResult) GetHasAccess() bool {
	if e == nil {
		return false
	}
	return e.HasAccess
}

func (e *EntitlementAccessResult) GetFeatureKey() string {
	if e == nil {
		return ""
	}
	return e.FeatureKey
}

func (e *EntitlementAccessResult) GetFeatureType() FeatureTypeEnum {
	if e == nil {
		return FeatureTypeEnum("")
	}
	return e.FeatureType
}

func (e *EntitlementAccessResult) GetConfig() optionalnullable.OptionalNullable[map[string]any] {
	if e == nil {
		return nil
	}
	return e.Config
}

func (e *EntitlementAccessResult) GetEntitlementID() string {
	if e == nil {
		return ""
	}
	return e.EntitlementID
}

func (e *EntitlementAccessResult) GetProductID() string {
	if e == nil {
		return ""
	}
	return e.ProductID
}

func (e *EntitlementAccessResult) GetActiveFrom() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.ActiveFrom
}

func (e *EntitlementAccessResult) GetActiveTo() optionalnullable.OptionalNullable[time.Time] {
	if e == nil {
		return nil
	}
	return e.ActiveTo
}

func (e *EntitlementAccessResult) GetStatus() EntitlementAccessResultStatus {
	if e == nil {
		return EntitlementAccessResultStatus("")
	}
	return e.Status
}

func (e *EntitlementAccessResult) GetBalance() optionalnullable.OptionalNullable[float64] {
	if e == nil {
		return nil
	}
	return e.Balance
}

func (e *EntitlementAccessResult) GetUsageInPeriod() optionalnullable.OptionalNullable[float64] {
	if e == nil {
		return nil
	}
	return e.UsageInPeriod
}

func (e *EntitlementAccessResult) GetOverage() optionalnullable.OptionalNullable[float64] {
	if e == nil {
		return nil
	}
	return e.Overage
}

func (e *EntitlementAccessResult) GetCurrentPeriodStart() optionalnullable.OptionalNullable[time.Time] {
	if e == nil {
		return nil
	}
	return e.CurrentPeriodStart
}

func (e *EntitlementAccessResult) GetCurrentPeriodEnd() optionalnullable.OptionalNullable[time.Time] {
	if e == nil {
		return nil
	}
	return e.CurrentPeriodEnd
}
