// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

type EntitlementObject string

const (
	EntitlementObjectEntitlement EntitlementObject = "entitlement"
)

func (e EntitlementObject) ToPointer() *EntitlementObject {
	return &e
}
func (e *EntitlementObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "entitlement":
		*e = EntitlementObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EntitlementObject: %v", v)
	}
}

type EntitlementBillableMetric struct {
	// Unique identifier for a billable metric
	BillableMetricID *string `json:"billableMetricId,omitzero"`
	// Custom price override in decimal dollars. Sample values: '0.000012' sets $0.000012 per unit, '0.50' sets $0.50 per unit, '1.25' sets $1.25 per unit
	Price *string `json:"price,omitzero"`
	// Pre-authorized metric quantity amount. Sample values: 10000 tokens, 500 GB storage, 1000 API calls, 24 compute hours
	Quantity *float64 `json:"quantity,omitzero"`
}

func (e *EntitlementBillableMetric) GetBillableMetricID() *string {
	if e == nil {
		return nil
	}
	return e.BillableMetricID
}

func (e *EntitlementBillableMetric) GetPrice() *string {
	if e == nil {
		return nil
	}
	return e.Price
}

func (e *EntitlementBillableMetric) GetQuantity() *float64 {
	if e == nil {
		return nil
	}
	return e.Quantity
}

type Entitlement struct {
	// Unique identifier for an entitlement
	ID     *string            `json:"id,omitzero"`
	Object *EntitlementObject `default:"entitlement" json:"object"`
	// Billable metrics and quantities reserved stored as JSON.
	BillableMetrics []EntitlementBillableMetric `json:"billableMetrics,omitzero"`
	// Entitlement creation timestamp in ISO 8601 format. Sample values: '2024-01-15T10:30:00Z', '2024-02-01T14:45:30Z'
	CreatedAt *time.Time `json:"createdAt,omitzero"`
	// Unique identifier for a customer
	CustomerID *string `json:"customerId,omitzero"`
	// Entitlement expiration timestamp in ISO 8601 format. Sample values: '2024-12-31T23:59:59Z', '2025-01-15T10:30:00Z'
	ExpiresAt *time.Time `json:"expiresAt,omitzero"`
	// Maximum consumption events allowed before entitlement expires. Sample values: 1 allows single use, 10 allows ten uses, 100 allows one hundred uses
	MaxUses *int64 `json:"maxUses,omitzero"`
	// Unique identifier for a merchant/organization
	MerchantID *string `json:"merchantId,omitzero"`
	// Geographic restriction zone limiting where this entitlement applies. Sample values: 'us-west-2' confines usage to AWS US West 2 region, 'eu-central-1' confines usage to EU Central 1 region, 'global' permits usage from all regions
	Region *string `json:"region,omitzero"`
	// Unused entitlement balance in atomic units (string representation of BigInt). Sample values: '100000000000' equals $100.00 remaining, '50000000000' equals $50.00 remaining, '0' equals fully consumed
	RemainingBalance *string `json:"remainingBalance,omitzero"`
	// Count of consumption events processed using this entitlement. Sample values: 0 indicates unused, 5 indicates five events processed, 10 indicates ten events processed
	UsedCount *int64 `json:"usedCount,omitzero"`
}

func (e Entitlement) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Entitlement) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *Entitlement) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *Entitlement) GetObject() *EntitlementObject {
	if e == nil {
		return nil
	}
	return e.Object
}

func (e *Entitlement) GetBillableMetrics() []EntitlementBillableMetric {
	if e == nil {
		return nil
	}
	return e.BillableMetrics
}

func (e *Entitlement) GetCreatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.CreatedAt
}

func (e *Entitlement) GetCustomerID() *string {
	if e == nil {
		return nil
	}
	return e.CustomerID
}

func (e *Entitlement) GetExpiresAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.ExpiresAt
}

func (e *Entitlement) GetMaxUses() *int64 {
	if e == nil {
		return nil
	}
	return e.MaxUses
}

func (e *Entitlement) GetMerchantID() *string {
	if e == nil {
		return nil
	}
	return e.MerchantID
}

func (e *Entitlement) GetRegion() *string {
	if e == nil {
		return nil
	}
	return e.Region
}

func (e *Entitlement) GetRemainingBalance() *string {
	if e == nil {
		return nil
	}
	return e.RemainingBalance
}

func (e *Entitlement) GetUsedCount() *int64 {
	if e == nil {
		return nil
	}
	return e.UsedCount
}
