// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Code - Optional semantic business error code for machine-readable discrimination (e.g. 'TAX_NOT_ENABLED'). UPPER_SNAKE_CASE. Clients should check this field, not message.
type Code string

const (
	CodeTaxNotEnabled         Code = "TAX_NOT_ENABLED"
	CodePaymentSessionExpired Code = "PAYMENT_SESSION_EXPIRED"
)

func (e Code) ToPointer() *Code {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Code) IsExact() bool {
	if e != nil {
		switch *e {
		case "TAX_NOT_ENABLED", "PAYMENT_SESSION_EXPIRED":
			return true
		}
	}
	return false
}
