// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

type FeatureObject string

const (
	FeatureObjectFeature FeatureObject = "feature"
)

func (e FeatureObject) ToPointer() *FeatureObject {
	return &e
}
func (e *FeatureObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "feature":
		*e = FeatureObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FeatureObject: %v", v)
	}
}

type FeatureType string

const (
	FeatureTypeMetered FeatureType = "metered"
	FeatureTypeStatic  FeatureType = "static"
	FeatureTypeBoolean FeatureType = "boolean"
)

func (e FeatureType) ToPointer() *FeatureType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FeatureType) IsExact() bool {
	if e != nil {
		switch *e {
		case "metered", "static", "boolean":
			return true
		}
	}
	return false
}

type Feature struct {
	// Unique identifier for a feature
	ID     string         `json:"id"`
	Object *FeatureObject `default:"feature" json:"object"`
	Key    string         `json:"key"`
	Name   string         `json:"name"`
	Type   FeatureType    `json:"type"`
	// Unique identifier for an organization
	MerchantID string `json:"merchantId"`
	// Unique identifier for a product
	ProductID string            `json:"productId"`
	Metadata  map[string]string `json:"metadata"`
	// Timestamp when the feature was created
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when the feature was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

func (f Feature) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *Feature) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *Feature) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *Feature) GetObject() *FeatureObject {
	if f == nil {
		return nil
	}
	return f.Object
}

func (f *Feature) GetKey() string {
	if f == nil {
		return ""
	}
	return f.Key
}

func (f *Feature) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *Feature) GetType() FeatureType {
	if f == nil {
		return FeatureType("")
	}
	return f.Type
}

func (f *Feature) GetMerchantID() string {
	if f == nil {
		return ""
	}
	return f.MerchantID
}

func (f *Feature) GetProductID() string {
	if f == nil {
		return ""
	}
	return f.ProductID
}

func (f *Feature) GetMetadata() map[string]string {
	if f == nil {
		return map[string]string{}
	}
	return f.Metadata
}

func (f *Feature) GetCreatedAt() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.CreatedAt
}

func (f *Feature) GetUpdatedAt() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.UpdatedAt
}
