// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GroupInvoiceSummary struct {
	// Unique identifier for the group (e.g. plan ID, or 'other')
	GroupKey string `json:"groupKey"`
	// Human-readable label for the group (e.g. plan name)
	GroupLabel  string                 `json:"groupLabel"`
	Outstanding InvoiceCategorySummary `json:"outstanding"`
	Paid        InvoiceCategorySummary `json:"paid"`
	WrittenOff  InvoiceCategorySummary `json:"writtenOff"`
}

func (g *GroupInvoiceSummary) GetGroupKey() string {
	if g == nil {
		return ""
	}
	return g.GroupKey
}

func (g *GroupInvoiceSummary) GetGroupLabel() string {
	if g == nil {
		return ""
	}
	return g.GroupLabel
}

func (g *GroupInvoiceSummary) GetOutstanding() InvoiceCategorySummary {
	if g == nil {
		return InvoiceCategorySummary{}
	}
	return g.Outstanding
}

func (g *GroupInvoiceSummary) GetPaid() InvoiceCategorySummary {
	if g == nil {
		return InvoiceCategorySummary{}
	}
	return g.Paid
}

func (g *GroupInvoiceSummary) GetWrittenOff() InvoiceCategorySummary {
	if g == nil {
		return InvoiceCategorySummary{}
	}
	return g.WrittenOff
}
