// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

// EventType - Type of event: 'usage' for billable metric events, 'fee' for fee events, 'discount' for grant discount line items (subtotal/total are negative, representing a credit)
type EventType string

const (
	EventTypeUsage    EventType = "usage"
	EventTypeFee      EventType = "fee"
	EventTypeDiscount EventType = "discount"
)

func (e EventType) ToPointer() *EventType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EventType) IsExact() bool {
	if e != nil {
		switch *e {
		case "usage", "fee", "discount":
			return true
		}
	}
	return false
}

// InvoiceLineItemPaymentTerm - When this line falls due relative to the window it covers: `in_advance` at the window's start, `in_arrears` at its end. A metered line is stamped `in_arrears`, because usage is only known once the window closes — but metered rows written before that rule carry `null` and were never backfilled, so do not read a metered line's term as guaranteed. `null` also means the line is not billed on a term of its own: manual, grant-discount and adjustment lines carry no term, and an adjustment instead falls due with the charge it reduces. Treat `null` as an expected value on any line type, not an error.
type InvoiceLineItemPaymentTerm string

const (
	InvoiceLineItemPaymentTermInAdvance InvoiceLineItemPaymentTerm = "in_advance"
	InvoiceLineItemPaymentTermInArrears InvoiceLineItemPaymentTerm = "in_arrears"
)

func (e InvoiceLineItemPaymentTerm) ToPointer() *InvoiceLineItemPaymentTerm {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *InvoiceLineItemPaymentTerm) IsExact() bool {
	if e != nil {
		switch *e {
		case "in_advance", "in_arrears":
			return true
		}
	}
	return false
}

// InvoiceLineItemLineItemType - Type of line item: 'charge' for regular billing, 'refund' for refunded items (amounts are negated)
type InvoiceLineItemLineItemType string

const (
	InvoiceLineItemLineItemTypeCharge InvoiceLineItemLineItemType = "charge"
	InvoiceLineItemLineItemTypeRefund InvoiceLineItemLineItemType = "refund"
)

func (e InvoiceLineItemLineItemType) ToPointer() *InvoiceLineItemLineItemType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *InvoiceLineItemLineItemType) IsExact() bool {
	if e != nil {
		switch *e {
		case "charge", "refund":
			return true
		}
	}
	return false
}

type InvoiceLineItem struct {
	// Type of event: 'usage' for billable metric events, 'fee' for fee events, 'discount' for grant discount line items (subtotal/total are negative, representing a credit)
	EventType EventType `json:"eventType"`
	// The event ID (usage_event_id or fee_event_id)
	EventID string `json:"eventId"`
	// Source ID: billable_metric_id for usage events, fee_id for fee events
	EventSourceID string `json:"eventSourceId"`
	// HOTFIX: Mirrors eventSourceId for backward compatibility
	BillableMetricID string `json:"billableMetricId"`
	// Item the line's charge was tagged with, recorded when the line was generated and not re-resolved on read. A discount line carries the same item as the charge it offsets. `null` means the charge carried no tag at that moment, the line predates item stamping, or the line has no originating charge (a grant-credit purchase) — it is an expected value, not an error. Use `priceId` to tell those cases apart.
	ItemID optionalnullable.OptionalNullable[string] `json:"itemId,omitzero"`
	// The price this line was generated from, or `null` when the line has no originating charge. With `itemId` it says whether a missing tag is fixable: `priceId` set and `itemId` null means the charge was simply untagged, which tagging it and restamping resolves; both null means the line records a grant-credit purchase, which is deferred revenue and is never tagged. Any measure of outstanding mapping work must exclude the latter or it can never reach zero.
	PriceID optionalnullable.OptionalNullable[string] `json:"priceId,omitzero"`
	// Start of the billed window this line covers, inclusive. Distinct from the invoice's own period, which is the union of its lines' windows (earliest start to latest end) and so covers time no single line bills on a mixed-timing invoice.
	PeriodStart *time.Time `json:"periodStart,omitzero"`
	// End of the billed window this line covers, exclusive — the instant at `periodEnd` belongs to the next window. Equal to `periodStart` on a one-off charge, which bills at an instant and has no period grid.
	PeriodEnd *time.Time `json:"periodEnd,omitzero"`
	// When this line falls due relative to the window it covers: `in_advance` at the window's start, `in_arrears` at its end. A metered line is stamped `in_arrears`, because usage is only known once the window closes — but metered rows written before that rule carry `null` and were never backfilled, so do not read a metered line's term as guaranteed. `null` also means the line is not billed on a term of its own: manual, grant-discount and adjustment lines carry no term, and an adjustment instead falls due with the charge it reduces. Treat `null` as an expected value on any line type, not an error.
	PaymentTerm optionalnullable.OptionalNullable[InvoiceLineItemPaymentTerm] `json:"paymentTerm,omitzero"`
	// Display name for this line item on invoices
	InvoiceDisplayName string `json:"invoiceDisplayName"`
	// Type of line item: 'charge' for regular billing, 'refund' for refunded items (amounts are negated)
	LineItemType InvoiceLineItemLineItemType `json:"lineItemType"`
	// The meter event ID (usage events only)
	MeterEventID string `json:"meterEventId"`
	// Description of what this metric or fee measures
	MetricDescription string `json:"metricDescription"`
	// Human-readable name of the billable metric or fee
	MetricName string `json:"metricName"`
	// Measurement unit label. Sample values: 'calls' for API calls, 'GB' for storage, 'hours' for compute time, 'tokens' for LLM tokens, 'charge' for fees
	MetricUnit string `json:"metricUnit"`
	// Quantity of usage. Negative for refunds.
	Quantity float64 `json:"quantity"`
	// Tax rate as decimal (0.10 = 10%)
	TaxRate float64 `json:"taxRate"`
	// Total amount (totalPrice + totalTax) in decimal dollars. Negative for refunds.
	TotalAmount string `json:"totalAmount"`
	// Total price (tax-exclusive) in decimal dollars. Negative for refunds.
	TotalPrice string `json:"totalPrice"`
	// Total tax in decimal dollars. Negative for refunds.
	TotalTax string `json:"totalTax"`
	// Unit price in decimal dollars
	UnitPrice string `json:"unitPrice"`
}

func (i InvoiceLineItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InvoiceLineItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InvoiceLineItem) GetEventType() EventType {
	if i == nil {
		return EventType("")
	}
	return i.EventType
}

func (i *InvoiceLineItem) GetEventID() string {
	if i == nil {
		return ""
	}
	return i.EventID
}

func (i *InvoiceLineItem) GetEventSourceID() string {
	if i == nil {
		return ""
	}
	return i.EventSourceID
}

func (i *InvoiceLineItem) GetBillableMetricID() string {
	if i == nil {
		return ""
	}
	return i.BillableMetricID
}

func (i *InvoiceLineItem) GetItemID() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.ItemID
}

func (i *InvoiceLineItem) GetPriceID() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.PriceID
}

func (i *InvoiceLineItem) GetPeriodStart() *time.Time {
	if i == nil {
		return nil
	}
	return i.PeriodStart
}

func (i *InvoiceLineItem) GetPeriodEnd() *time.Time {
	if i == nil {
		return nil
	}
	return i.PeriodEnd
}

func (i *InvoiceLineItem) GetPaymentTerm() optionalnullable.OptionalNullable[InvoiceLineItemPaymentTerm] {
	if i == nil {
		return nil
	}
	return i.PaymentTerm
}

func (i *InvoiceLineItem) GetInvoiceDisplayName() string {
	if i == nil {
		return ""
	}
	return i.InvoiceDisplayName
}

func (i *InvoiceLineItem) GetLineItemType() InvoiceLineItemLineItemType {
	if i == nil {
		return InvoiceLineItemLineItemType("")
	}
	return i.LineItemType
}

func (i *InvoiceLineItem) GetMeterEventID() string {
	if i == nil {
		return ""
	}
	return i.MeterEventID
}

func (i *InvoiceLineItem) GetMetricDescription() string {
	if i == nil {
		return ""
	}
	return i.MetricDescription
}

func (i *InvoiceLineItem) GetMetricName() string {
	if i == nil {
		return ""
	}
	return i.MetricName
}

func (i *InvoiceLineItem) GetMetricUnit() string {
	if i == nil {
		return ""
	}
	return i.MetricUnit
}

func (i *InvoiceLineItem) GetQuantity() float64 {
	if i == nil {
		return 0.0
	}
	return i.Quantity
}

func (i *InvoiceLineItem) GetTaxRate() float64 {
	if i == nil {
		return 0.0
	}
	return i.TaxRate
}

func (i *InvoiceLineItem) GetTotalAmount() string {
	if i == nil {
		return ""
	}
	return i.TotalAmount
}

func (i *InvoiceLineItem) GetTotalPrice() string {
	if i == nil {
		return ""
	}
	return i.TotalPrice
}

func (i *InvoiceLineItem) GetTotalTax() string {
	if i == nil {
		return ""
	}
	return i.TotalTax
}

func (i *InvoiceLineItem) GetUnitPrice() string {
	if i == nil {
		return ""
	}
	return i.UnitPrice
}
