// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/paygentic/sdk-go/optionalnullable"
)

type InvoiceLineItemsResponse struct {
	// The invoice ID
	InvoiceID string `json:"invoiceId"`
	// Array of line items for this page
	LineItems []InvoiceLineItem `json:"lineItems"`
	// Token for fetching the next page, null if no more pages
	NextPageToken optionalnullable.OptionalNullable[string] `json:"nextPageToken,omitzero"`
	// Total number of line items across all pages
	TotalCount int64 `json:"totalCount"`
}

func (i *InvoiceLineItemsResponse) GetInvoiceID() string {
	if i == nil {
		return ""
	}
	return i.InvoiceID
}

func (i *InvoiceLineItemsResponse) GetLineItems() []InvoiceLineItem {
	if i == nil {
		return []InvoiceLineItem{}
	}
	return i.LineItems
}

func (i *InvoiceLineItemsResponse) GetNextPageToken() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.NextPageToken
}

func (i *InvoiceLineItemsResponse) GetTotalCount() int64 {
	if i == nil {
		return 0
	}
	return i.TotalCount
}
