// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

// InvoiceRefundObject - The object type
type InvoiceRefundObject string

const (
	InvoiceRefundObjectInvoiceRefund InvoiceRefundObject = "invoice_refund"
)

func (e InvoiceRefundObject) ToPointer() *InvoiceRefundObject {
	return &e
}
func (e *InvoiceRefundObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "invoice_refund":
		*e = InvoiceRefundObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InvoiceRefundObject: %v", v)
	}
}

// InvoiceRefundStatus - Credit note status
type InvoiceRefundStatus string

const (
	InvoiceRefundStatusIssued InvoiceRefundStatus = "ISSUED"
	InvoiceRefundStatusVoided InvoiceRefundStatus = "VOIDED"
)

func (e InvoiceRefundStatus) ToPointer() *InvoiceRefundStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *InvoiceRefundStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "ISSUED", "VOIDED":
			return true
		}
	}
	return false
}

type InvoiceRefund struct {
	// The object type
	Object InvoiceRefundObject `json:"object"`
	// The credit note ID (crn_*)
	ID string `json:"id"`
	// The invoice this refund credits
	InvoiceID string `json:"invoiceId"`
	// The merchant that owns the invoice
	MerchantID string `json:"merchantId"`
	// Refunded subtotal (pre-tax) in decimal dollars
	Amount string `json:"amount"`
	// Reversed tax in decimal dollars
	TaxAmount string `json:"taxAmount"`
	// Total refunded (amount + taxAmount) in decimal dollars
	Total string `json:"total"`
	// ISO 4217 currency code
	Currency string `json:"currency"`
	// Credit note status
	Status InvoiceRefundStatus `json:"status"`
	// Credit note id in the tax provider
	ExternalCreditNoteID string `json:"externalCreditNoteId"`
	// Public URL to view the credit note document
	Permalink optionalnullable.OptionalNullable[string] `json:"permalink,omitzero"`
	// Direct PDF download link
	PdfURL optionalnullable.OptionalNullable[string] `json:"pdfUrl,omitzero"`
	// Optional refund reason
	Reason optionalnullable.OptionalNullable[string] `json:"reason,omitzero"`
	// When the refund was issued
	CreatedAt time.Time `json:"createdAt"`
	// When the refund was voided, if applicable
	VoidedAt optionalnullable.OptionalNullable[time.Time] `json:"voidedAt,omitzero"`
}

func (i InvoiceRefund) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InvoiceRefund) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InvoiceRefund) GetObject() InvoiceRefundObject {
	if i == nil {
		return InvoiceRefundObject("")
	}
	return i.Object
}

func (i *InvoiceRefund) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *InvoiceRefund) GetInvoiceID() string {
	if i == nil {
		return ""
	}
	return i.InvoiceID
}

func (i *InvoiceRefund) GetMerchantID() string {
	if i == nil {
		return ""
	}
	return i.MerchantID
}

func (i *InvoiceRefund) GetAmount() string {
	if i == nil {
		return ""
	}
	return i.Amount
}

func (i *InvoiceRefund) GetTaxAmount() string {
	if i == nil {
		return ""
	}
	return i.TaxAmount
}

func (i *InvoiceRefund) GetTotal() string {
	if i == nil {
		return ""
	}
	return i.Total
}

func (i *InvoiceRefund) GetCurrency() string {
	if i == nil {
		return ""
	}
	return i.Currency
}

func (i *InvoiceRefund) GetStatus() InvoiceRefundStatus {
	if i == nil {
		return InvoiceRefundStatus("")
	}
	return i.Status
}

func (i *InvoiceRefund) GetExternalCreditNoteID() string {
	if i == nil {
		return ""
	}
	return i.ExternalCreditNoteID
}

func (i *InvoiceRefund) GetPermalink() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.Permalink
}

func (i *InvoiceRefund) GetPdfURL() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.PdfURL
}

func (i *InvoiceRefund) GetReason() optionalnullable.OptionalNullable[string] {
	if i == nil {
		return nil
	}
	return i.Reason
}

func (i *InvoiceRefund) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *InvoiceRefund) GetVoidedAt() optionalnullable.OptionalNullable[time.Time] {
	if i == nil {
		return nil
	}
	return i.VoidedAt
}
