// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

type ItemObject string

const (
	ItemObjectItem ItemObject = "item"
)

func (e ItemObject) ToPointer() *ItemObject {
	return &e
}
func (e *ItemObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "item":
		*e = ItemObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ItemObject: %v", v)
	}
}

type Item struct {
	ID                 string              `json:"id"`
	Object             *ItemObject         `default:"item" json:"object"`
	MerchantID         string              `json:"merchantId"`
	Name               string              `json:"name"`
	Metadata           map[string]any      `json:"metadata"`
	ExternalReferences []ExternalReference `json:"externalReferences"`
	CreatedAt          time.Time           `json:"createdAt"`
	UpdatedAt          time.Time           `json:"updatedAt"`
}

func (i Item) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Item) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *Item) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *Item) GetObject() *ItemObject {
	if i == nil {
		return nil
	}
	return i.Object
}

func (i *Item) GetMerchantID() string {
	if i == nil {
		return ""
	}
	return i.MerchantID
}

func (i *Item) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *Item) GetMetadata() map[string]any {
	if i == nil {
		return map[string]any{}
	}
	return i.Metadata
}

func (i *Item) GetExternalReferences() []ExternalReference {
	if i == nil {
		return []ExternalReference{}
	}
	return i.ExternalReferences
}

func (i *Item) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *Item) GetUpdatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.UpdatedAt
}
