// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// LineItemsResponseObject - The object type
type LineItemsResponseObject string

const (
	LineItemsResponseObjectList LineItemsResponseObject = "list"
)

func (e LineItemsResponseObject) ToPointer() *LineItemsResponseObject {
	return &e
}
func (e *LineItemsResponseObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = LineItemsResponseObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LineItemsResponseObject: %v", v)
	}
}

type LineItemsResponse struct {
	// The object type
	Object LineItemsResponseObject `json:"object"`
	// Array of line items
	Data []LineItem `json:"data"`
	// Total number of matching line items
	TotalCount int64            `json:"totalCount"`
	Summary    LineItemsSummary `json:"summary"`
}

func (l *LineItemsResponse) GetObject() LineItemsResponseObject {
	if l == nil {
		return LineItemsResponseObject("")
	}
	return l.Object
}

func (l *LineItemsResponse) GetData() []LineItem {
	if l == nil {
		return []LineItem{}
	}
	return l.Data
}

func (l *LineItemsResponse) GetTotalCount() int64 {
	if l == nil {
		return 0
	}
	return l.TotalCount
}

func (l *LineItemsResponse) GetSummary() LineItemsSummary {
	if l == nil {
		return LineItemsSummary{}
	}
	return l.Summary
}
