// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

// MeteredEntitlementListItem - Common fields shared by all entitlement list items. List items use `entitlementId` (not `id`) to preserve the original public field name on `/v1/entitlements`. The get-by-id endpoint returns the same object with a top-level `id` and `object: "entitlement"` instead.
type MeteredEntitlementListItem struct {
	// Unique identifier for the entitlement.
	EntitlementID string `json:"entitlementId"`
	// Unique identifier for a customer
	CustomerID string `json:"customerId"`
	// The feature this entitlement grants access to.
	FeatureID string `json:"featureId"`
	// The unique key identifying the feature.
	FeatureKey string `json:"featureKey"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	featureType string `const:"metered" json:"featureType"`
	// Unique identifier for a product
	ProductID string `json:"productId"`
	// The subscription this entitlement is associated with, if any.
	SubscriptionID *string `json:"subscriptionId"`
	// Current status of the entitlement.
	Status EntitlementStatus `json:"status"`
	// When the entitlement becomes active.
	ActiveFrom time.Time `json:"activeFrom"`
	// When the entitlement expires. Null means no expiration.
	ActiveTo *time.Time `json:"activeTo"`
	// Whether the customer currently has active access to this entitlement.
	HasAccess bool `json:"hasAccess"`
	// Additional metadata for the entitlement.
	Metadata map[string]string `json:"metadata"`
	// Always `null` for metered entitlements. Surfaced on every list item so clients can read `item.config` without first switching on `featureType`.
	Config map[string]any `json:"config"`
	// When false (hard limit), access is blocked when balance is exhausted and overage is not charged on invoices. When true (soft limit), access continues past the grant and overage is charged at the per-unit rate.
	IsSoftLimit bool `json:"isSoftLimit"`
	// Remaining grant balance for the current period.
	Balance float64 `json:"balance"`
	// Total usage consumed in the current billing period.
	UsageInPeriod float64 `json:"usageInPeriod"`
	// Amount of usage exceeding the granted balance.
	Overage float64 `json:"overage"`
	// Start of the current usage period. Before the entitlement activates (the pre-activation "dark window", when the query time is earlier than `activeFrom`) this instead describes the pre-activation `[subscription start, activation)` window and may be `null` when there is no associated subscription.
	CurrentPeriodStart *time.Time `json:"currentPeriodStart"`
	// End of the current usage period. Before the entitlement activates (the pre-activation "dark window", when the query time is earlier than `activeFrom`) this instead holds `activeFrom` — the end of the pre-activation `[subscription start, activation)` window.
	CurrentPeriodEnd *time.Time `json:"currentPeriodEnd"`
}

func (m MeteredEntitlementListItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MeteredEntitlementListItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MeteredEntitlementListItem) GetEntitlementID() string {
	if m == nil {
		return ""
	}
	return m.EntitlementID
}

func (m *MeteredEntitlementListItem) GetCustomerID() string {
	if m == nil {
		return ""
	}
	return m.CustomerID
}

func (m *MeteredEntitlementListItem) GetFeatureID() string {
	if m == nil {
		return ""
	}
	return m.FeatureID
}

func (m *MeteredEntitlementListItem) GetFeatureKey() string {
	if m == nil {
		return ""
	}
	return m.FeatureKey
}

func (m *MeteredEntitlementListItem) GetFeatureType() string {
	return "metered"
}

func (m *MeteredEntitlementListItem) GetProductID() string {
	if m == nil {
		return ""
	}
	return m.ProductID
}

func (m *MeteredEntitlementListItem) GetSubscriptionID() *string {
	if m == nil {
		return nil
	}
	return m.SubscriptionID
}

func (m *MeteredEntitlementListItem) GetStatus() EntitlementStatus {
	if m == nil {
		return EntitlementStatus("")
	}
	return m.Status
}

func (m *MeteredEntitlementListItem) GetActiveFrom() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.ActiveFrom
}

func (m *MeteredEntitlementListItem) GetActiveTo() *time.Time {
	if m == nil {
		return nil
	}
	return m.ActiveTo
}

func (m *MeteredEntitlementListItem) GetHasAccess() bool {
	if m == nil {
		return false
	}
	return m.HasAccess
}

func (m *MeteredEntitlementListItem) GetMetadata() map[string]string {
	if m == nil {
		return map[string]string{}
	}
	return m.Metadata
}

func (m *MeteredEntitlementListItem) GetConfig() map[string]any {
	if m == nil {
		return nil
	}
	return m.Config
}

func (m *MeteredEntitlementListItem) GetIsSoftLimit() bool {
	if m == nil {
		return false
	}
	return m.IsSoftLimit
}

func (m *MeteredEntitlementListItem) GetBalance() float64 {
	if m == nil {
		return 0.0
	}
	return m.Balance
}

func (m *MeteredEntitlementListItem) GetUsageInPeriod() float64 {
	if m == nil {
		return 0.0
	}
	return m.UsageInPeriod
}

func (m *MeteredEntitlementListItem) GetOverage() float64 {
	if m == nil {
		return 0.0
	}
	return m.Overage
}

func (m *MeteredEntitlementListItem) GetCurrentPeriodStart() *time.Time {
	if m == nil {
		return nil
	}
	return m.CurrentPeriodStart
}

func (m *MeteredEntitlementListItem) GetCurrentPeriodEnd() *time.Time {
	if m == nil {
		return nil
	}
	return m.CurrentPeriodEnd
}
