// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/paygentic/sdk-go/internal/utils"
)

type ReplacePrice struct {
	// Unique identifier for a price
	ReplacesPriceID string `json:"replacesPriceId"`
	// Unique identifier for a price
	WithPriceID string `json:"withPriceId"`
}

func (r *ReplacePrice) GetReplacesPriceID() string {
	if r == nil {
		return ""
	}
	return r.ReplacesPriceID
}

func (r *ReplacePrice) GetWithPriceID() string {
	if r == nil {
		return ""
	}
	return r.WithPriceID
}

// MintPlanVersionRequest - A reference-by-id price diff applied to the prices of the plan's current version. Every id references an existing price created via POST /prices; inline price definitions are not accepted. A mint must carry at least one price change, so an empty body is rejected. A version must carry at least one price, so a diff that would leave none is rejected.
type MintPlanVersionRequest struct {
	// Prices to add to the version. Each must not already be on the plan's current version.
	AddPrices []string `json:"addPrices,omitzero"`
	// Prices to remove. Each must be on the plan's current version.
	RemovePrices []string `json:"removePrices,omitzero"`
	// Prices to swap in place, preserving the slot's lineage so the price keeps its identity where the plan is configured for stable price ids. replacesPriceId must be on the plan's current version; withPriceId is the new price.
	ReplacePrices []ReplacePrice `json:"replacePrices,omitzero"`
}

func (m MintPlanVersionRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MintPlanVersionRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MintPlanVersionRequest) GetAddPrices() []string {
	if m == nil {
		return nil
	}
	return m.AddPrices
}

func (m *MintPlanVersionRequest) GetRemovePrices() []string {
	if m == nil {
		return nil
	}
	return m.RemovePrices
}

func (m *MintPlanVersionRequest) GetReplacePrices() []ReplacePrice {
	if m == nil {
		return nil
	}
	return m.ReplacePrices
}
