// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
)

type MintPlanLineRefType string

const (
	MintPlanLineRefTypePriceID           MintPlanLineRefType = "PriceId"
	MintPlanLineRefTypeMintPlanLineInput MintPlanLineRefType = "MintPlanLineInput"
)

// MintPlanLineRef - Either a price ID on its own, or a price ID with the key that names its line.
type MintPlanLineRef struct {
	PriceID           *string            `queryParam:"inline" union:"member"`
	MintPlanLineInput *MintPlanLineInput `queryParam:"inline" union:"member"`

	Type MintPlanLineRefType
}

func CreateMintPlanLineRefPriceID(priceID string) MintPlanLineRef {
	typ := MintPlanLineRefTypePriceID

	return MintPlanLineRef{
		PriceID: &priceID,
		Type:    typ,
	}
}

func CreateMintPlanLineRefMintPlanLineInput(mintPlanLineInput MintPlanLineInput) MintPlanLineRef {
	typ := MintPlanLineRefTypeMintPlanLineInput

	return MintPlanLineRef{
		MintPlanLineInput: &mintPlanLineInput,
		Type:              typ,
	}
}

func (u *MintPlanLineRef) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = MintPlanLineRef{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var priceID string = ""
	if err := utils.UnmarshalJSON(data, &priceID, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MintPlanLineRefTypePriceID,
			Value: &priceID,
		})
	}

	var mintPlanLineInput MintPlanLineInput = MintPlanLineInput{}
	if err := utils.UnmarshalJSON(data, &mintPlanLineInput, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  MintPlanLineRefTypeMintPlanLineInput,
			Value: &mintPlanLineInput,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MintPlanLineRef", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for MintPlanLineRef", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(MintPlanLineRefType)
	switch best.Type {
	case MintPlanLineRefTypePriceID:
		u.PriceID = best.Value.(*string)
		return nil
	case MintPlanLineRefTypeMintPlanLineInput:
		u.MintPlanLineInput = best.Value.(*MintPlanLineInput)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for MintPlanLineRef", string(data))
}

func (u MintPlanLineRef) MarshalJSON() ([]byte, error) {
	if u.PriceID != nil {
		return utils.MarshalJSON(u.PriceID, "", true)
	}

	if u.MintPlanLineInput != nil {
		return utils.MarshalJSON(u.MintPlanLineInput, "", true)
	}

	return nil, errors.New("could not marshal union type MintPlanLineRef: all fields are null")
}
