// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// OffsetPagination - Offset-based pagination response.
type OffsetPagination struct {
	// Number of items returned in the current page.
	Limit *int64 `json:"limit,omitzero"`
	// Number of items skipped.
	Offset *int64 `json:"offset,omitzero"`
	// Total number of items available.
	Total *int64 `json:"total,omitzero"`
}

func (o *OffsetPagination) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *OffsetPagination) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *OffsetPagination) GetTotal() *int64 {
	if o == nil {
		return nil
	}
	return o.Total
}
