// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type OrderApprovalObject string

const (
	OrderApprovalObjectApproval OrderApprovalObject = "approval"
)

func (e OrderApprovalObject) ToPointer() *OrderApprovalObject {
	return &e
}
func (e *OrderApprovalObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "approval":
		*e = OrderApprovalObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OrderApprovalObject: %v", v)
	}
}

type OrderApprovalDecision string

const (
	OrderApprovalDecisionPending   OrderApprovalDecision = "pending"
	OrderApprovalDecisionApproved  OrderApprovalDecision = "approved"
	OrderApprovalDecisionRejected  OrderApprovalDecision = "rejected"
	OrderApprovalDecisionCancelled OrderApprovalDecision = "cancelled"
)

func (e OrderApprovalDecision) ToPointer() *OrderApprovalDecision {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OrderApprovalDecision) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "approved", "rejected", "cancelled":
			return true
		}
	}
	return false
}

type OrderApproval struct {
	ID               string                                       `json:"id"`
	Object           OrderApprovalObject                          `json:"object"`
	MerchantID       string                                       `json:"merchantId"`
	ResourceType     string                                       `json:"resourceType"`
	ResourceID       string                                       `json:"resourceId"`
	Kind             string                                       `json:"kind"`
	Decision         OrderApprovalDecision                        `json:"decision"`
	Requester        string                                       `json:"requester"`
	Reviewer         optionalnullable.OptionalNullable[string]    `json:"reviewer,omitzero"`
	Note             optionalnullable.OptionalNullable[string]    `json:"note,omitzero"`
	DataSnapshotHash string                                       `json:"dataSnapshotHash"`
	DecidedAt        optionalnullable.OptionalNullable[time.Time] `json:"decidedAt,omitzero"`
	CreatedAt        time.Time                                    `json:"createdAt"`
}

func (o OrderApproval) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrderApproval) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrderApproval) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OrderApproval) GetObject() OrderApprovalObject {
	if o == nil {
		return OrderApprovalObject("")
	}
	return o.Object
}

func (o *OrderApproval) GetMerchantID() string {
	if o == nil {
		return ""
	}
	return o.MerchantID
}

func (o *OrderApproval) GetResourceType() string {
	if o == nil {
		return ""
	}
	return o.ResourceType
}

func (o *OrderApproval) GetResourceID() string {
	if o == nil {
		return ""
	}
	return o.ResourceID
}

func (o *OrderApproval) GetKind() string {
	if o == nil {
		return ""
	}
	return o.Kind
}

func (o *OrderApproval) GetDecision() OrderApprovalDecision {
	if o == nil {
		return OrderApprovalDecision("")
	}
	return o.Decision
}

func (o *OrderApproval) GetRequester() string {
	if o == nil {
		return ""
	}
	return o.Requester
}

func (o *OrderApproval) GetReviewer() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Reviewer
}

func (o *OrderApproval) GetNote() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Note
}

func (o *OrderApproval) GetDataSnapshotHash() string {
	if o == nil {
		return ""
	}
	return o.DataSnapshotHash
}

func (o *OrderApproval) GetDecidedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.DecidedAt
}

func (o *OrderApproval) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}
