// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type PaymentMethodObject string

const (
	PaymentMethodObjectPaymentMethod PaymentMethodObject = "paymentMethod"
)

func (e PaymentMethodObject) ToPointer() *PaymentMethodObject {
	return &e
}
func (e *PaymentMethodObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "paymentMethod":
		*e = PaymentMethodObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentMethodObject: %v", v)
	}
}

type PaymentMethod struct {
	Object PaymentMethodObject `json:"object"`
	// Payment method identifier.
	ID string `json:"id"`
	// Payment method type (e.g. `card`, `sepa_debit`).
	Type      optionalnullable.OptionalNullable[string] `json:"type,omitzero"`
	Brand     optionalnullable.OptionalNullable[string] `json:"brand,omitzero"`
	Last4     optionalnullable.OptionalNullable[string] `json:"last4,omitzero"`
	ExpMonth  optionalnullable.OptionalNullable[int64]  `json:"expMonth,omitzero"`
	ExpYear   optionalnullable.OptionalNullable[int64]  `json:"expYear,omitzero"`
	CreatedAt time.Time                                 `json:"createdAt"`
}

func (p PaymentMethod) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentMethod) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PaymentMethod) GetObject() PaymentMethodObject {
	if p == nil {
		return PaymentMethodObject("")
	}
	return p.Object
}

func (p *PaymentMethod) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PaymentMethod) GetType() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Type
}

func (p *PaymentMethod) GetBrand() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Brand
}

func (p *PaymentMethod) GetLast4() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Last4
}

func (p *PaymentMethod) GetExpMonth() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.ExpMonth
}

func (p *PaymentMethod) GetExpYear() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.ExpYear
}

func (p *PaymentMethod) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}
