// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type PlanVersionPriceSlotObject string

const (
	PlanVersionPriceSlotObjectPrice PlanVersionPriceSlotObject = "price"
)

func (e PlanVersionPriceSlotObject) ToPointer() *PlanVersionPriceSlotObject {
	return &e
}
func (e *PlanVersionPriceSlotObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "price":
		*e = PlanVersionPriceSlotObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlanVersionPriceSlotObject: %v", v)
	}
}

type PlanVersionPriceSlotModel string

const (
	PlanVersionPriceSlotModelStandard   PlanVersionPriceSlotModel = "standard"
	PlanVersionPriceSlotModelDynamic    PlanVersionPriceSlotModel = "dynamic"
	PlanVersionPriceSlotModelVolume     PlanVersionPriceSlotModel = "volume"
	PlanVersionPriceSlotModelPercentage PlanVersionPriceSlotModel = "percentage"
)

func (e PlanVersionPriceSlotModel) ToPointer() *PlanVersionPriceSlotModel {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PlanVersionPriceSlotModel) IsExact() bool {
	if e != nil {
		switch *e {
		case "standard", "dynamic", "volume", "percentage":
			return true
		}
	}
	return false
}

type PlanVersionPriceSlotPaymentTerm string

const (
	PlanVersionPriceSlotPaymentTermInArrears PlanVersionPriceSlotPaymentTerm = "in_arrears"
	PlanVersionPriceSlotPaymentTermInAdvance PlanVersionPriceSlotPaymentTerm = "in_advance"
)

func (e PlanVersionPriceSlotPaymentTerm) ToPointer() *PlanVersionPriceSlotPaymentTerm {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PlanVersionPriceSlotPaymentTerm) IsExact() bool {
	if e != nil {
		switch *e {
		case "in_arrears", "in_advance":
			return true
		}
	}
	return false
}

// PlanVersionPriceSlotRateType - What properties.unitPrice is denominated in. 'amount' (the default) is an amount of the invoice currency for each unit metered, so the quantity is the multiplier. 'proportion' is the reverse: a dimensionless share of a currency-denominated quantity, so '0.02' is 2% and the invoice prints '2.00%'. Presentation only. Requires a standard metered price in real currency.
type PlanVersionPriceSlotRateType string

const (
	PlanVersionPriceSlotRateTypeAmount     PlanVersionPriceSlotRateType = "amount"
	PlanVersionPriceSlotRateTypeProportion PlanVersionPriceSlotRateType = "proportion"
)

func (e PlanVersionPriceSlotRateType) ToPointer() *PlanVersionPriceSlotRateType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PlanVersionPriceSlotRateType) IsExact() bool {
	if e != nil {
		switch *e {
		case "amount", "proportion":
			return true
		}
	}
	return false
}

// PlanVersionPriceSlot - One price slot on a plan version. Every `Price` field is present, plus `priceDeleted` layered on top.
type PlanVersionPriceSlot struct {
	// Unique identifier for a price
	ID     string                      `json:"id"`
	Object *PlanVersionPriceSlotObject `default:"price" json:"object"`
	// Unique identifier for an organization
	MerchantID       string  `json:"merchantId"`
	BillableMetricID *string `json:"billableMetricId,omitzero"`
	// The unique identifier for the fee referred to by this price
	FeeID *string `json:"feeId,omitzero"`
	// ISO 8601 duration for billing frequency (e.g., P1M for monthly)
	BillingCadence     optionalnullable.OptionalNullable[string] `json:"billingCadence,omitzero"`
	CreatedAt          time.Time                                 `json:"createdAt"`
	Currency           *string                                   `json:"currency,omitzero"`
	Description        *string                                   `json:"description,omitzero"`
	InvoiceDisplayName string                                    `json:"invoiceDisplayName"`
	Model              PlanVersionPriceSlotModel                 `json:"model"`
	PaymentTerm        PlanVersionPriceSlotPaymentTerm           `json:"paymentTerm"`
	Properties         map[string]any                            `json:"properties"`
	UnitAmount         *string                                   `json:"unitAmount,omitzero"`
	UpdatedAt          time.Time                                 `json:"updatedAt"`
	// Features associated with this price
	Features []PriceFeature `json:"features,omitzero"`
	// When true, grants applied to a subscription will discount usage charged by this price. Only supported for standard metered prices.
	GrantDiscountEnabled *bool `default:"false" json:"grantDiscountEnabled"`
	// A fixed amount owed whole rather than a per-period rate. An obligation is not prorated over a partial first period: when a subscription starts before its billing anchor, no truncated stub is billed and the first charge is the full amount at the next anchor. An obligation also refuses an interval boundary that falls strictly inside one of its own billing periods, since part of an amount owed whole is not a thing to bill. Defaults to false, which is a rate and is today's behaviour for every price. Not supported on a metered price, whose amount resolves from usage at close.
	IsObligation *bool `default:"false" json:"isObligation"`
	// What properties.unitPrice is denominated in. 'amount' (the default) is an amount of the invoice currency for each unit metered, so the quantity is the multiplier. 'proportion' is the reverse: a dimensionless share of a currency-denominated quantity, so '0.02' is 2% and the invoice prints '2.00%'. Presentation only. Requires a standard metered price in real currency.
	RateType *PlanVersionPriceSlotRateType `default:"amount" json:"rateType"`
	// Presentation only. Prices sharing this value, within one billing period, print as a single row on the rendered invoice PDF and are described by this string. Every member still bills its own line item on the ledger, this API and the compliance document. The combined row's rate is derived from the members' own rates. Requires the 'standard' pricing model. Sample values: 'Cross Border Fees', 'FX Fees'
	InvoiceDisplayGroup optionalnullable.OptionalNullable[string] `json:"invoiceDisplayGroup,omitzero"`
	// Unique identifier for a pricing unit
	PricingUnitID *string `json:"pricingUnitId,omitzero"`
	// A price's tax declaration. Optional on write — a price that declares nothing is `IN_SCOPE`, and is billed and taxed exactly as it was before this object existed. Always present on read. Replaced as a whole on update: send the object to change it, omit it to leave it alone.
	Tax PriceTax `json:"tax"`
	// Quantity used when generating invoice line items for this price. Total per period = quantity × unitPrice. Only supported for fee prices; metered prices derive quantity from usage. Defaults to 1.
	Quantity *int64 `default:"1" json:"quantity"`
	// True when the underlying price this slot references has been soft-deleted.
	PriceDeleted bool `json:"priceDeleted"`
}

func (p PlanVersionPriceSlot) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlanVersionPriceSlot) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlanVersionPriceSlot) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PlanVersionPriceSlot) GetObject() *PlanVersionPriceSlotObject {
	if p == nil {
		return nil
	}
	return p.Object
}

func (p *PlanVersionPriceSlot) GetMerchantID() string {
	if p == nil {
		return ""
	}
	return p.MerchantID
}

func (p *PlanVersionPriceSlot) GetBillableMetricID() *string {
	if p == nil {
		return nil
	}
	return p.BillableMetricID
}

func (p *PlanVersionPriceSlot) GetFeeID() *string {
	if p == nil {
		return nil
	}
	return p.FeeID
}

func (p *PlanVersionPriceSlot) GetBillingCadence() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.BillingCadence
}

func (p *PlanVersionPriceSlot) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PlanVersionPriceSlot) GetCurrency() *string {
	if p == nil {
		return nil
	}
	return p.Currency
}

func (p *PlanVersionPriceSlot) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PlanVersionPriceSlot) GetInvoiceDisplayName() string {
	if p == nil {
		return ""
	}
	return p.InvoiceDisplayName
}

func (p *PlanVersionPriceSlot) GetModel() PlanVersionPriceSlotModel {
	if p == nil {
		return PlanVersionPriceSlotModel("")
	}
	return p.Model
}

func (p *PlanVersionPriceSlot) GetPaymentTerm() PlanVersionPriceSlotPaymentTerm {
	if p == nil {
		return PlanVersionPriceSlotPaymentTerm("")
	}
	return p.PaymentTerm
}

func (p *PlanVersionPriceSlot) GetProperties() map[string]any {
	if p == nil {
		return map[string]any{}
	}
	return p.Properties
}

func (p *PlanVersionPriceSlot) GetUnitAmount() *string {
	if p == nil {
		return nil
	}
	return p.UnitAmount
}

func (p *PlanVersionPriceSlot) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

func (p *PlanVersionPriceSlot) GetFeatures() []PriceFeature {
	if p == nil {
		return nil
	}
	return p.Features
}

func (p *PlanVersionPriceSlot) GetGrantDiscountEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.GrantDiscountEnabled
}

func (p *PlanVersionPriceSlot) GetIsObligation() *bool {
	if p == nil {
		return nil
	}
	return p.IsObligation
}

func (p *PlanVersionPriceSlot) GetRateType() *PlanVersionPriceSlotRateType {
	if p == nil {
		return nil
	}
	return p.RateType
}

func (p *PlanVersionPriceSlot) GetInvoiceDisplayGroup() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.InvoiceDisplayGroup
}

func (p *PlanVersionPriceSlot) GetPricingUnitID() *string {
	if p == nil {
		return nil
	}
	return p.PricingUnitID
}

func (p *PlanVersionPriceSlot) GetTax() PriceTax {
	if p == nil {
		return PriceTax{}
	}
	return p.Tax
}

func (p *PlanVersionPriceSlot) GetQuantity() *int64 {
	if p == nil {
		return nil
	}
	return p.Quantity
}

func (p *PlanVersionPriceSlot) GetPriceDeleted() bool {
	if p == nil {
		return false
	}
	return p.PriceDeleted
}
