// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

type PlanVersionObject string

const (
	PlanVersionObjectPlanVersion PlanVersionObject = "plan_version"
)

func (e PlanVersionObject) ToPointer() *PlanVersionObject {
	return &e
}
func (e *PlanVersionObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "plan_version":
		*e = PlanVersionObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlanVersionObject: %v", v)
	}
}

// PlanVersionStatus - Lifecycle status of the version.
type PlanVersionStatus string

const (
	PlanVersionStatusDraft     PlanVersionStatus = "draft"
	PlanVersionStatusPublished PlanVersionStatus = "published"
	PlanVersionStatusArchived  PlanVersionStatus = "archived"
)

func (e PlanVersionStatus) ToPointer() *PlanVersionStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PlanVersionStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "draft", "published", "archived":
			return true
		}
	}
	return false
}

// PlanVersion - A single plan version, including its price slots. Extends the list summary with the version's prices for draft review.
type PlanVersion struct {
	// Unique identifier for a plan version
	ID     string            `json:"id"`
	Object PlanVersionObject `json:"object"`
	// Monotonic version number within the plan, starting at 1.
	VersionNumber int64 `json:"versionNumber"`
	// Lifecycle status of the version.
	Status PlanVersionStatus `json:"status"`
	// When this version was published. Absent for draft versions.
	PublishedAt *time.Time `json:"publishedAt,omitzero"`
	// Whether this version is the plan's current default (live) version.
	IsDefault bool `json:"isDefault"`
	// Number of committed-status subscriptions pinned to this version at creation time. Not a live-billing cohort.
	SubscriptionCount int64 `json:"subscriptionCount"`
	// Unique identifier for a plan version
	BasedOnVersionID *string `json:"basedOnVersionId,omitzero"`
	// When this version was last modified. Optimistic-concurrency token: read this value and echo it back as an `If-Match` header on a draft-price-mutation request to reject the write (412) if the draft changed since this read.
	UpdatedAt time.Time `json:"updatedAt"`
	// The price slots that make up this version.
	Prices []PlanVersionPriceSlot `json:"prices"`
}

func (p PlanVersion) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlanVersion) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlanVersion) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PlanVersion) GetObject() PlanVersionObject {
	if p == nil {
		return PlanVersionObject("")
	}
	return p.Object
}

func (p *PlanVersion) GetVersionNumber() int64 {
	if p == nil {
		return 0
	}
	return p.VersionNumber
}

func (p *PlanVersion) GetStatus() PlanVersionStatus {
	if p == nil {
		return PlanVersionStatus("")
	}
	return p.Status
}

func (p *PlanVersion) GetPublishedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.PublishedAt
}

func (p *PlanVersion) GetIsDefault() bool {
	if p == nil {
		return false
	}
	return p.IsDefault
}

func (p *PlanVersion) GetSubscriptionCount() int64 {
	if p == nil {
		return 0
	}
	return p.SubscriptionCount
}

func (p *PlanVersion) GetBasedOnVersionID() *string {
	if p == nil {
		return nil
	}
	return p.BasedOnVersionID
}

func (p *PlanVersion) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

func (p *PlanVersion) GetPrices() []PlanVersionPriceSlot {
	if p == nil {
		return []PlanVersionPriceSlot{}
	}
	return p.Prices
}
