// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type PriceObject string

const (
	PriceObjectPrice PriceObject = "price"
)

func (e PriceObject) ToPointer() *PriceObject {
	return &e
}
func (e *PriceObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "price":
		*e = PriceObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PriceObject: %v", v)
	}
}

type PriceModel string

const (
	PriceModelStandard   PriceModel = "standard"
	PriceModelDynamic    PriceModel = "dynamic"
	PriceModelVolume     PriceModel = "volume"
	PriceModelPercentage PriceModel = "percentage"
)

func (e PriceModel) ToPointer() *PriceModel {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PriceModel) IsExact() bool {
	if e != nil {
		switch *e {
		case "standard", "dynamic", "volume", "percentage":
			return true
		}
	}
	return false
}

type PricePaymentTerm string

const (
	PricePaymentTermInstant   PricePaymentTerm = "instant"
	PricePaymentTermInArrears PricePaymentTerm = "in_arrears"
	PricePaymentTermInAdvance PricePaymentTerm = "in_advance"
)

func (e PricePaymentTerm) ToPointer() *PricePaymentTerm {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PricePaymentTerm) IsExact() bool {
	if e != nil {
		switch *e {
		case "instant", "in_arrears", "in_advance":
			return true
		}
	}
	return false
}

type Price struct {
	// Unique identifier for a price
	ID               string       `json:"id"`
	Object           *PriceObject `default:"price" json:"object"`
	BillableMetricID *string      `json:"billableMetricId,omitzero"`
	// The unique identifier for the fee referred to by this price
	FeeID *string `json:"feeId,omitzero"`
	// ISO 8601 duration for billing frequency (e.g., P1M for monthly)
	BillingCadence     optionalnullable.OptionalNullable[string] `json:"billingCadence,omitzero"`
	CreatedAt          time.Time                                 `json:"createdAt"`
	Currency           *string                                   `json:"currency,omitzero"`
	Description        *string                                   `json:"description,omitzero"`
	InvoiceDisplayName string                                    `json:"invoiceDisplayName"`
	Model              PriceModel                                `json:"model"`
	PaymentTerm        PricePaymentTerm                          `json:"paymentTerm"`
	Properties         map[string]any                            `json:"properties"`
	UnitAmount         *string                                   `json:"unitAmount,omitzero"`
	UpdatedAt          time.Time                                 `json:"updatedAt"`
	// Features associated with this price
	Features []PriceFeature `json:"features,omitzero"`
	// When true, grants applied to a subscription will discount usage charged by this price. Only supported for standard metered prices.
	GrantDiscountEnabled *bool `default:"false" json:"grantDiscountEnabled"`
}

func (p Price) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Price) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Price) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *Price) GetObject() *PriceObject {
	if p == nil {
		return nil
	}
	return p.Object
}

func (p *Price) GetBillableMetricID() *string {
	if p == nil {
		return nil
	}
	return p.BillableMetricID
}

func (p *Price) GetFeeID() *string {
	if p == nil {
		return nil
	}
	return p.FeeID
}

func (p *Price) GetBillingCadence() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.BillingCadence
}

func (p *Price) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *Price) GetCurrency() *string {
	if p == nil {
		return nil
	}
	return p.Currency
}

func (p *Price) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *Price) GetInvoiceDisplayName() string {
	if p == nil {
		return ""
	}
	return p.InvoiceDisplayName
}

func (p *Price) GetModel() PriceModel {
	if p == nil {
		return PriceModel("")
	}
	return p.Model
}

func (p *Price) GetPaymentTerm() PricePaymentTerm {
	if p == nil {
		return PricePaymentTerm("")
	}
	return p.PaymentTerm
}

func (p *Price) GetProperties() map[string]any {
	if p == nil {
		return map[string]any{}
	}
	return p.Properties
}

func (p *Price) GetUnitAmount() *string {
	if p == nil {
		return nil
	}
	return p.UnitAmount
}

func (p *Price) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

func (p *Price) GetFeatures() []PriceFeature {
	if p == nil {
		return nil
	}
	return p.Features
}

func (p *Price) GetGrantDiscountEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.GrantDiscountEnabled
}
