// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"github.com/paygentic/sdk-go/internal/utils"
)

// PercentagePriceProperties - Percentage pricing model
type PercentagePriceProperties struct {
	// Ceiling amount limiting total charge regardless of percentage calculation. Sample values: '500.00' caps fees at $500 maximum, '2000.00' limits charges to $2000 per period
	MaxCharge string `json:"maxCharge"`
	// Floor amount charged regardless of percentage calculation. Sample values: '5.00' ensures minimum $5 fee, '25.00' guarantees at least $25 per billing event
	MinCharge string `json:"minCharge"`
	// Rate expressed as decimal between 0 and 10, supporting up to 4 decimal precision. Sample values: '0.03' represents 3%, '0.075' represents 7.5%, '1.10' represents 110%
	Percentage string `json:"percentage"`
}

func (p PercentagePriceProperties) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PercentagePriceProperties) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PercentagePriceProperties) GetMaxCharge() string {
	if p == nil {
		return ""
	}
	return p.MaxCharge
}

func (p *PercentagePriceProperties) GetMinCharge() string {
	if p == nil {
		return ""
	}
	return p.MinCharge
}

func (p *PercentagePriceProperties) GetPercentage() string {
	if p == nil {
		return ""
	}
	return p.Percentage
}

type VolumeTier struct {
	// Inclusive upper bound of the band, as a decimal string. Null on the last band only, which carries the remainder. Sample values: '100' bounds the band at 100 units, null leaves the top open.
	UpTo *string `json:"upTo"`
	// Per-unit cost inside this band, as a decimal string, capped at 6 decimal places. Sample values: '5' represents $5 per unit, '0.004' represents $0.004 per unit.
	UnitPrice string `json:"unitPrice"`
}

func (v VolumeTier) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VolumeTier) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VolumeTier) GetUpTo() *string {
	if v == nil {
		return nil
	}
	return v.UpTo
}

func (v *VolumeTier) GetUnitPrice() string {
	if v == nil {
		return ""
	}
	return v.UnitPrice
}

// VolumePriceProperties - Volume pricing model
type VolumePriceProperties struct {
	// Ordered ladder of bands. The band is selected by the period's total metered usage, and its rate applies to every billed unit. A band matches when the quantity is less than or equal to its `upTo`, and the first matching band wins; the previous band's `upTo` is the exclusive lower bound, and the first band's floor is 0.
	Tiers []VolumeTier `json:"tiers"`
}

func (v VolumePriceProperties) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VolumePriceProperties) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VolumePriceProperties) GetTiers() []VolumeTier {
	if v == nil {
		return []VolumeTier{}
	}
	return v.Tiers
}

// DynamicPriceProperties - Dynamic pricing model
type DynamicPriceProperties struct {
	// Upper limit of the price range for dynamic pricing. Sample values: '0.10' means $0.10 per token for large volumes at peak times
	MaxPrice string `json:"maxPrice"`
	// Lower limit of the price range for dynamic pricing. Sample values: '0.01' means $0.01 per token for low volumes during off-peak hours
	MinPrice string `json:"minPrice"`
}

func (d DynamicPriceProperties) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DynamicPriceProperties) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DynamicPriceProperties) GetMaxPrice() string {
	if d == nil {
		return ""
	}
	return d.MaxPrice
}

func (d *DynamicPriceProperties) GetMinPrice() string {
	if d == nil {
		return ""
	}
	return d.MinPrice
}

// StandardPriceProperties - Standard pricing model
type StandardPriceProperties struct {
	// Per-unit cost in decimal format for fixed-rate pricing. Sample values: '0.00002' represents $0.00002 per token, '0.15' represents $0.15 per gigabyte stored, '0.05' represents $0.05 per API call. Per unit. Total per period = quantity × unitPrice; see the `quantity` field. A negative value defines a usage-scaled rebate: the line's subtotal is negative and reduces the invoice. A rebate never drives an invoice total below zero, so set rebate rates below the charges they offset. A negative unitPrice is only valid on a metered price (a billableMetricId is required — there is no usage to scale on a fee price) and cannot be combined with grantDiscountEnabled, a hard-limit feature, or a pricingUnitId. When a rebate and a charge price share a billable metric but attach to different features, they compute against different quantity bases: a price attached to a feature bills the overage against its allowance, while a featureless price bills the raw metered usage. That is a permitted configuration, not an error. Attach both to the same feature to bill them against one basis.
	UnitPrice string `json:"unitPrice"`
}

func (s StandardPriceProperties) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StandardPriceProperties) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StandardPriceProperties) GetUnitPrice() string {
	if s == nil {
		return ""
	}
	return s.UnitPrice
}

type PricePropertiesType string

const (
	PricePropertiesTypeStandardPriceProperties   PricePropertiesType = "StandardPriceProperties"
	PricePropertiesTypeDynamicPriceProperties    PricePropertiesType = "DynamicPriceProperties"
	PricePropertiesTypeVolumePriceProperties     PricePropertiesType = "VolumePriceProperties"
	PricePropertiesTypePercentagePriceProperties PricePropertiesType = "PercentagePriceProperties"
	PricePropertiesTypeUnknown                   PricePropertiesType = "Unknown"
)

type PriceProperties struct {
	StandardPriceProperties   *StandardPriceProperties   `queryParam:"inline" union:"member"`
	DynamicPriceProperties    *DynamicPriceProperties    `queryParam:"inline" union:"member"`
	VolumePriceProperties     *VolumePriceProperties     `queryParam:"inline" union:"member"`
	PercentagePriceProperties *PercentagePriceProperties `queryParam:"inline" union:"member"`
	UnknownRaw                json.RawMessage            `json:"-" union:"unknown"`

	Type PricePropertiesType
}

func CreatePricePropertiesStandardPriceProperties(standardPriceProperties StandardPriceProperties) PriceProperties {
	typ := PricePropertiesTypeStandardPriceProperties

	return PriceProperties{
		StandardPriceProperties: &standardPriceProperties,
		Type:                    typ,
	}
}

func CreatePricePropertiesDynamicPriceProperties(dynamicPriceProperties DynamicPriceProperties) PriceProperties {
	typ := PricePropertiesTypeDynamicPriceProperties

	return PriceProperties{
		DynamicPriceProperties: &dynamicPriceProperties,
		Type:                   typ,
	}
}

func CreatePricePropertiesVolumePriceProperties(volumePriceProperties VolumePriceProperties) PriceProperties {
	typ := PricePropertiesTypeVolumePriceProperties

	return PriceProperties{
		VolumePriceProperties: &volumePriceProperties,
		Type:                  typ,
	}
}

func CreatePricePropertiesPercentagePriceProperties(percentagePriceProperties PercentagePriceProperties) PriceProperties {
	typ := PricePropertiesTypePercentagePriceProperties

	return PriceProperties{
		PercentagePriceProperties: &percentagePriceProperties,
		Type:                      typ,
	}
}

func CreatePricePropertiesUnknown(raw json.RawMessage) PriceProperties {
	return PriceProperties{
		UnknownRaw: raw,
		Type:       PricePropertiesTypeUnknown,
	}
}

func (u PriceProperties) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u PriceProperties) IsUnknown() bool {
	return u.Type == PricePropertiesTypeUnknown
}

func (u *PriceProperties) UnmarshalJSON(data []byte) error {
	*u = PriceProperties{}

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var standardPriceProperties StandardPriceProperties = StandardPriceProperties{}
	if err := utils.UnmarshalJSON(data, &standardPriceProperties, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PricePropertiesTypeStandardPriceProperties,
			Value: &standardPriceProperties,
		})
	}

	var dynamicPriceProperties DynamicPriceProperties = DynamicPriceProperties{}
	if err := utils.UnmarshalJSON(data, &dynamicPriceProperties, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PricePropertiesTypeDynamicPriceProperties,
			Value: &dynamicPriceProperties,
		})
	}

	var volumePriceProperties VolumePriceProperties = VolumePriceProperties{}
	if err := utils.UnmarshalJSON(data, &volumePriceProperties, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PricePropertiesTypeVolumePriceProperties,
			Value: &volumePriceProperties,
		})
	}

	var percentagePriceProperties PercentagePriceProperties = PercentagePriceProperties{}
	if err := utils.UnmarshalJSON(data, &percentagePriceProperties, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PricePropertiesTypePercentagePriceProperties,
			Value: &percentagePriceProperties,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = PricePropertiesTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = PricePropertiesTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(PricePropertiesType)
	switch best.Type {
	case PricePropertiesTypeStandardPriceProperties:
		u.StandardPriceProperties = best.Value.(*StandardPriceProperties)
		return nil
	case PricePropertiesTypeDynamicPriceProperties:
		u.DynamicPriceProperties = best.Value.(*DynamicPriceProperties)
		return nil
	case PricePropertiesTypeVolumePriceProperties:
		u.VolumePriceProperties = best.Value.(*VolumePriceProperties)
		return nil
	case PricePropertiesTypePercentagePriceProperties:
		u.PercentagePriceProperties = best.Value.(*PercentagePriceProperties)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = PricePropertiesTypeUnknown
	return nil
}

func (u PriceProperties) MarshalJSON() ([]byte, error) {
	if u.StandardPriceProperties != nil {
		return utils.MarshalJSON(u.StandardPriceProperties, "", true)
	}

	if u.DynamicPriceProperties != nil {
		return utils.MarshalJSON(u.DynamicPriceProperties, "", true)
	}

	if u.VolumePriceProperties != nil {
		return utils.MarshalJSON(u.VolumePriceProperties, "", true)
	}

	if u.PercentagePriceProperties != nil {
		return utils.MarshalJSON(u.PercentagePriceProperties, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type PriceProperties: all fields are null")
}
