// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/paygentic/sdk-go/internal/utils"
)

type PriceFeatureType string

const (
	PriceFeatureTypeMetered PriceFeatureType = "metered"
	PriceFeatureTypeStatic  PriceFeatureType = "static"
	PriceFeatureTypeBoolean PriceFeatureType = "boolean"
)

func (e PriceFeatureType) ToPointer() *PriceFeatureType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PriceFeatureType) IsExact() bool {
	if e != nil {
		switch *e {
		case "metered", "static", "boolean":
			return true
		}
	}
	return false
}

type PriceFeatureFeature struct {
	Key  *string           `json:"key,omitzero"`
	Name *string           `json:"name,omitzero"`
	Type *PriceFeatureType `json:"type,omitzero"`
}

func (p *PriceFeatureFeature) GetKey() *string {
	if p == nil {
		return nil
	}
	return p.Key
}

func (p *PriceFeatureFeature) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PriceFeatureFeature) GetType() *PriceFeatureType {
	if p == nil {
		return nil
	}
	return p.Type
}

type PriceFeature struct {
	ID                  string               `json:"id"`
	FeatureID           string               `json:"featureId"`
	EntitlementTemplate map[string]any       `json:"entitlementTemplate"`
	Feature             *PriceFeatureFeature `json:"feature,omitzero"`
}

func (p PriceFeature) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PriceFeature) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PriceFeature) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PriceFeature) GetFeatureID() string {
	if p == nil {
		return ""
	}
	return p.FeatureID
}

func (p *PriceFeature) GetEntitlementTemplate() map[string]any {
	if p == nil {
		return map[string]any{}
	}
	return p.EntitlementTemplate
}

func (p *PriceFeature) GetFeature() *PriceFeatureFeature {
	if p == nil {
		return nil
	}
	return p.Feature
}
