// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProfitabilityRow struct {
	// Customer ID, or the literal 'other' for the overflow row.
	CustomerID string `json:"customerId"`
	// Display name for the row. 'Other' for the overflow row.
	CustomerName string `json:"customerName"`
	// Net revenue (paid + outstanding) in unit currency, with two decimals.
	NetRevenue string `json:"netRevenue"`
	// Aggregated cost in unit currency, with two decimals.
	TotalCost string `json:"totalCost"`
	// Profit (revenue − cost) in unit currency, with two decimals. May be negative.
	Profit string `json:"profit"`
	// Margin percent (profit / revenue × 100), with two decimals. Null when revenue is zero.
	MarginPct *string `json:"marginPct"`
	// Per-customer revenue trend over the period. Null for the 'Other' row and when there's insufficient data.
	Trend *ProfitabilityTrend `json:"trend"`
}

func (p *ProfitabilityRow) GetCustomerID() string {
	if p == nil {
		return ""
	}
	return p.CustomerID
}

func (p *ProfitabilityRow) GetCustomerName() string {
	if p == nil {
		return ""
	}
	return p.CustomerName
}

func (p *ProfitabilityRow) GetNetRevenue() string {
	if p == nil {
		return ""
	}
	return p.NetRevenue
}

func (p *ProfitabilityRow) GetTotalCost() string {
	if p == nil {
		return ""
	}
	return p.TotalCost
}

func (p *ProfitabilityRow) GetProfit() string {
	if p == nil {
		return ""
	}
	return p.Profit
}

func (p *ProfitabilityRow) GetMarginPct() *string {
	if p == nil {
		return nil
	}
	return p.MarginPct
}

func (p *ProfitabilityRow) GetTrend() *ProfitabilityTrend {
	if p == nil {
		return nil
	}
	return p.Trend
}
