// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Reason - Coded failure reason. `entitlement_failed` means the entitlement itself could not be created. `grant_mint_failed` means the entitlement was created but its initial metered grant could not be minted; re-running this reconciliation retries the mint. `reset_cycle_misaligned` means the feature grants a credit discount on a reset cycle that is not the window it would be billed on, so re-running cannot succeed until the plan or the price is corrected.
type Reason string

const (
	ReasonEntitlementFailed    Reason = "entitlement_failed"
	ReasonGrantMintFailed      Reason = "grant_mint_failed"
	ReasonResetCycleMisaligned Reason = "reset_cycle_misaligned"
)

func (e Reason) ToPointer() *Reason {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Reason) IsExact() bool {
	if e != nil {
		switch *e {
		case "entitlement_failed", "grant_mint_failed", "reset_cycle_misaligned":
			return true
		}
	}
	return false
}

type ReconciledFeatureFailed struct {
	FeatureID  string `json:"featureId"`
	FeatureKey string `json:"featureKey"`
	// Coded failure reason. `entitlement_failed` means the entitlement itself could not be created. `grant_mint_failed` means the entitlement was created but its initial metered grant could not be minted; re-running this reconciliation retries the mint. `reset_cycle_misaligned` means the feature grants a credit discount on a reset cycle that is not the window it would be billed on, so re-running cannot succeed until the plan or the price is corrected.
	Reason Reason `json:"reason"`
}

func (r *ReconciledFeatureFailed) GetFeatureID() string {
	if r == nil {
		return ""
	}
	return r.FeatureID
}

func (r *ReconciledFeatureFailed) GetFeatureKey() string {
	if r == nil {
		return ""
	}
	return r.FeatureKey
}

func (r *ReconciledFeatureFailed) GetReason() Reason {
	if r == nil {
		return Reason("")
	}
	return r.Reason
}
