// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

// RevenueSummaryResponseRevenueRange - Where the caller's revenue actually lies in time. Scoped by the same filters as the request (merchant, and where given customer, subscription and currency), so it is not an account-wide statement. Present only when the selected range returned nothing. An object carries the bounds of the real revenue; null means no revenue under these filters at any time; an absent field means the extent was not resolved, because the result was not empty or because the lookup failed. An absent field must never be read as an absence. The bounds may span more than this endpoint's maximum queryable range, so clamp before re-querying.
type RevenueSummaryResponseRevenueRange struct {
	// Earliest invoice issue instant.
	From time.Time `json:"from"`
	// Latest invoice issue instant.
	To time.Time `json:"to"`
}

func (r RevenueSummaryResponseRevenueRange) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RevenueSummaryResponseRevenueRange) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RevenueSummaryResponseRevenueRange) GetFrom() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.From
}

func (r *RevenueSummaryResponseRevenueRange) GetTo() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.To
}

type RevenueSummaryResponse struct {
	// Object type identifier
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object string `const:"revenue_summary" json:"object"`
	// Net collected revenue in dollars (paid invoices + completed payments), already net of non-voided refunds. Omitted when groupBy=currency is active.
	NetRevenue *string `json:"netRevenue,omitzero"`
	// Gross total of non-voided refunds (credit notes) issued in the period, in dollars. Already subtracted from netRevenue and invoice totals. Omitted when groupBy=currency is active.
	TotalRefunds *string `json:"totalRefunds,omitzero"`
	// Number of non-voided refunds (credit notes) issued in the period. Omitted when groupBy=currency is active.
	RefundCount *float64 `json:"refundCount,omitzero"`
	// Gross total of usage-scaled rebates (negative metered line items) on invoices issued in the period, in dollars. Already netted into issued invoice grandTotals, so surfaced here for visibility. Omitted when groupBy=currency is active.
	TotalRebates *string `json:"totalRebates,omitzero"`
	// Number of rebate line items on invoices issued in the period. Omitted when groupBy=currency is active.
	RebateCount *float64        `json:"rebateCount,omitzero"`
	Invoices    *InvoiceSummary `json:"invoices,omitzero"`
	Payments    *PaymentSummary `json:"payments,omitzero"`
	// Time-bucketed revenue trend data. Omitted when groupBy=currency is active.
	Trend []RevenueTrendBucket `json:"trend,omitzero"`
	// Invoice breakdown by group dimension (only present when groupBy=plan or groupBy=customer is specified)
	GroupBreakdown []GroupInvoiceSummary `json:"groupBreakdown,omitzero"`
	// Per-currency revenue aggregates (only present when groupBy=currency is specified). Primary currency appears first, then alphabetical by ISO code. When present, top-level netRevenue, invoices, payments, and trend fields are omitted.
	CurrencyBreakdown []CurrencyBreakdownEntry `json:"currencyBreakdown,omitzero"`
	// Where the caller's revenue actually lies in time. Scoped by the same filters as the request (merchant, and where given customer, subscription and currency), so it is not an account-wide statement. Present only when the selected range returned nothing. An object carries the bounds of the real revenue; null means no revenue under these filters at any time; an absent field means the extent was not resolved, because the result was not empty or because the lookup failed. An absent field must never be read as an absence. The bounds may span more than this endpoint's maximum queryable range, so clamp before re-querying.
	RevenueRange optionalnullable.OptionalNullable[RevenueSummaryResponseRevenueRange] `json:"revenueRange,omitzero"`
}

func (r RevenueSummaryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RevenueSummaryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RevenueSummaryResponse) GetObject() string {
	return "revenue_summary"
}

func (r *RevenueSummaryResponse) GetNetRevenue() *string {
	if r == nil {
		return nil
	}
	return r.NetRevenue
}

func (r *RevenueSummaryResponse) GetTotalRefunds() *string {
	if r == nil {
		return nil
	}
	return r.TotalRefunds
}

func (r *RevenueSummaryResponse) GetRefundCount() *float64 {
	if r == nil {
		return nil
	}
	return r.RefundCount
}

func (r *RevenueSummaryResponse) GetTotalRebates() *string {
	if r == nil {
		return nil
	}
	return r.TotalRebates
}

func (r *RevenueSummaryResponse) GetRebateCount() *float64 {
	if r == nil {
		return nil
	}
	return r.RebateCount
}

func (r *RevenueSummaryResponse) GetInvoices() *InvoiceSummary {
	if r == nil {
		return nil
	}
	return r.Invoices
}

func (r *RevenueSummaryResponse) GetPayments() *PaymentSummary {
	if r == nil {
		return nil
	}
	return r.Payments
}

func (r *RevenueSummaryResponse) GetTrend() []RevenueTrendBucket {
	if r == nil {
		return nil
	}
	return r.Trend
}

func (r *RevenueSummaryResponse) GetGroupBreakdown() []GroupInvoiceSummary {
	if r == nil {
		return nil
	}
	return r.GroupBreakdown
}

func (r *RevenueSummaryResponse) GetCurrencyBreakdown() []CurrencyBreakdownEntry {
	if r == nil {
		return nil
	}
	return r.CurrencyBreakdown
}

func (r *RevenueSummaryResponse) GetRevenueRange() optionalnullable.OptionalNullable[RevenueSummaryResponseRevenueRange] {
	if r == nil {
		return nil
	}
	return r.RevenueRange
}
