// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

type RevenueTrendBucket struct {
	// Start time of this bucket
	Timestamp time.Time `json:"timestamp"`
	// Total amount of all invoices issued in this bucket (all statuses, by issuedAt)
	IssuedInvoices string `json:"issuedInvoices"`
	// Amount of written-off invoices in dollars for this bucket (by writtenOffAt)
	WrittenOffInvoices string `json:"writtenOffInvoices"`
	// Revenue from completed payments in dollars for this bucket
	CompletedPayments string `json:"completedPayments"`
	// Per-group trend entries (present when groupBy=plan or groupBy=customer)
	GroupBreakdown []GroupTrendEntry `json:"groupBreakdown,omitzero"`
}

func (r RevenueTrendBucket) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RevenueTrendBucket) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RevenueTrendBucket) GetTimestamp() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.Timestamp
}

func (r *RevenueTrendBucket) GetIssuedInvoices() string {
	if r == nil {
		return ""
	}
	return r.IssuedInvoices
}

func (r *RevenueTrendBucket) GetWrittenOffInvoices() string {
	if r == nil {
		return ""
	}
	return r.WrittenOffInvoices
}

func (r *RevenueTrendBucket) GetCompletedPayments() string {
	if r == nil {
		return ""
	}
	return r.CompletedPayments
}

func (r *RevenueTrendBucket) GetGroupBreakdown() []GroupTrendEntry {
	if r == nil {
		return nil
	}
	return r.GroupBreakdown
}
