// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/paygentic/sdk-go/internal/utils"
)

type RevenueSummaryResponse struct {
	// Object type identifier
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	object string `const:"revenue_summary" json:"object"`
	// Net collected revenue in dollars (paid invoices + completed payments)
	NetRevenue string         `json:"netRevenue"`
	Invoices   InvoiceSummary `json:"invoices"`
	Payments   PaymentSummary `json:"payments"`
	// Time-bucketed revenue trend data
	Trend []RevenueTrendBucket `json:"trend"`
	// Invoice breakdown by group dimension (only present when groupBy is specified)
	GroupBreakdown []GroupInvoiceSummary `json:"groupBreakdown,omitzero"`
}

func (r RevenueSummaryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RevenueSummaryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RevenueSummaryResponse) GetObject() string {
	return "revenue_summary"
}

func (r *RevenueSummaryResponse) GetNetRevenue() string {
	if r == nil {
		return ""
	}
	return r.NetRevenue
}

func (r *RevenueSummaryResponse) GetInvoices() InvoiceSummary {
	if r == nil {
		return InvoiceSummary{}
	}
	return r.Invoices
}

func (r *RevenueSummaryResponse) GetPayments() PaymentSummary {
	if r == nil {
		return PaymentSummary{}
	}
	return r.Payments
}

func (r *RevenueSummaryResponse) GetTrend() []RevenueTrendBucket {
	if r == nil {
		return []RevenueTrendBucket{}
	}
	return r.Trend
}

func (r *RevenueSummaryResponse) GetGroupBreakdown() []GroupInvoiceSummary {
	if r == nil {
		return nil
	}
	return r.GroupBreakdown
}
