// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type SchemasApprovalObject string

const (
	SchemasApprovalObjectApproval SchemasApprovalObject = "approval"
)

func (e SchemasApprovalObject) ToPointer() *SchemasApprovalObject {
	return &e
}
func (e *SchemasApprovalObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "approval":
		*e = SchemasApprovalObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasApprovalObject: %v", v)
	}
}

type SchemasApprovalResourceType string

const (
	SchemasApprovalResourceTypeOrder   SchemasApprovalResourceType = "order"
	SchemasApprovalResourceTypeInvoice SchemasApprovalResourceType = "invoice"
)

func (e SchemasApprovalResourceType) ToPointer() *SchemasApprovalResourceType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SchemasApprovalResourceType) IsExact() bool {
	if e != nil {
		switch *e {
		case "order", "invoice":
			return true
		}
	}
	return false
}

type SchemasApprovalKind string

const (
	SchemasApprovalKindDataReview      SchemasApprovalKind = "data_review"
	SchemasApprovalKindFinancialReview SchemasApprovalKind = "financial_review"
	SchemasApprovalKindPush            SchemasApprovalKind = "push"
)

func (e SchemasApprovalKind) ToPointer() *SchemasApprovalKind {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SchemasApprovalKind) IsExact() bool {
	if e != nil {
		switch *e {
		case "data_review", "financial_review", "push":
			return true
		}
	}
	return false
}

type SchemasApprovalDecision string

const (
	SchemasApprovalDecisionPending   SchemasApprovalDecision = "pending"
	SchemasApprovalDecisionApproved  SchemasApprovalDecision = "approved"
	SchemasApprovalDecisionRejected  SchemasApprovalDecision = "rejected"
	SchemasApprovalDecisionCancelled SchemasApprovalDecision = "cancelled"
)

func (e SchemasApprovalDecision) ToPointer() *SchemasApprovalDecision {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SchemasApprovalDecision) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "approved", "rejected", "cancelled":
			return true
		}
	}
	return false
}

type SchemasApproval struct {
	ID               string                                       `json:"id"`
	Object           SchemasApprovalObject                        `json:"object"`
	MerchantID       string                                       `json:"merchantId"`
	ResourceType     SchemasApprovalResourceType                  `json:"resourceType"`
	ResourceID       string                                       `json:"resourceId"`
	Kind             SchemasApprovalKind                          `json:"kind"`
	Decision         SchemasApprovalDecision                      `json:"decision"`
	Requester        string                                       `json:"requester"`
	Reviewer         optionalnullable.OptionalNullable[string]    `json:"reviewer,omitzero"`
	Note             optionalnullable.OptionalNullable[string]    `json:"note,omitzero"`
	DataSnapshotHash string                                       `json:"dataSnapshotHash"`
	DecidedAt        optionalnullable.OptionalNullable[time.Time] `json:"decidedAt,omitzero"`
	CreatedAt        time.Time                                    `json:"createdAt"`
}

func (s SchemasApproval) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasApproval) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SchemasApproval) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SchemasApproval) GetObject() SchemasApprovalObject {
	if s == nil {
		return SchemasApprovalObject("")
	}
	return s.Object
}

func (s *SchemasApproval) GetMerchantID() string {
	if s == nil {
		return ""
	}
	return s.MerchantID
}

func (s *SchemasApproval) GetResourceType() SchemasApprovalResourceType {
	if s == nil {
		return SchemasApprovalResourceType("")
	}
	return s.ResourceType
}

func (s *SchemasApproval) GetResourceID() string {
	if s == nil {
		return ""
	}
	return s.ResourceID
}

func (s *SchemasApproval) GetKind() SchemasApprovalKind {
	if s == nil {
		return SchemasApprovalKind("")
	}
	return s.Kind
}

func (s *SchemasApproval) GetDecision() SchemasApprovalDecision {
	if s == nil {
		return SchemasApprovalDecision("")
	}
	return s.Decision
}

func (s *SchemasApproval) GetRequester() string {
	if s == nil {
		return ""
	}
	return s.Requester
}

func (s *SchemasApproval) GetReviewer() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.Reviewer
}

func (s *SchemasApproval) GetNote() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.Note
}

func (s *SchemasApproval) GetDataSnapshotHash() string {
	if s == nil {
		return ""
	}
	return s.DataSnapshotHash
}

func (s *SchemasApproval) GetDecidedAt() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.DecidedAt
}

func (s *SchemasApproval) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}
