// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

type SourceObject string

const (
	SourceObjectSource SourceObject = "source"
)

func (e SourceObject) ToPointer() *SourceObject {
	return &e
}
func (e *SourceObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "source":
		*e = SourceObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceObject: %v", v)
	}
}

type ProcessingMode string

const (
	ProcessingModeAutomatic ProcessingMode = "automatic"
	ProcessingModeManual    ProcessingMode = "manual"
)

func (e ProcessingMode) ToPointer() *ProcessingMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProcessingMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "automatic", "manual":
			return true
		}
	}
	return false
}

type SourceType string

const (
	SourceTypeStripeRevenue SourceType = "stripe_revenue"
)

func (e SourceType) ToPointer() *SourceType {
	return &e
}
func (e *SourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "stripe_revenue":
		*e = SourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceType: %v", v)
	}
}

type Source struct {
	// Unique identifier for a source
	ID          string         `json:"id"`
	Object      SourceObject   `json:"object"`
	Config      map[string]any `json:"config,omitzero"`
	CreatedAt   time.Time      `json:"createdAt"`
	Description *string        `json:"description,omitzero"`
	Enabled     bool           `json:"enabled"`
	// Unique identifier for an organization
	MerchantID string         `json:"merchantId"`
	Metadata   map[string]any `json:"metadata,omitzero"`
	Name       string         `json:"name"`
	// Unique identifier for a plan
	PlanID         string         `json:"planId"`
	ProcessingMode ProcessingMode `json:"processingMode"`
	Type           SourceType     `json:"type"`
	UpdatedAt      time.Time      `json:"updatedAt"`
}

func (s Source) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Source) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Source) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Source) GetObject() SourceObject {
	if s == nil {
		return SourceObject("")
	}
	return s.Object
}

func (s *Source) GetConfig() map[string]any {
	if s == nil {
		return nil
	}
	return s.Config
}

func (s *Source) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *Source) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *Source) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *Source) GetMerchantID() string {
	if s == nil {
		return ""
	}
	return s.MerchantID
}

func (s *Source) GetMetadata() map[string]any {
	if s == nil {
		return nil
	}
	return s.Metadata
}

func (s *Source) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *Source) GetPlanID() string {
	if s == nil {
		return ""
	}
	return s.PlanID
}

func (s *Source) GetProcessingMode() ProcessingMode {
	if s == nil {
		return ProcessingMode("")
	}
	return s.ProcessingMode
}

func (s *Source) GetType() SourceType {
	if s == nil {
		return SourceType("")
	}
	return s.Type
}

func (s *Source) GetUpdatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.UpdatedAt
}
