// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

type SubscriptionPortalObject string

const (
	SubscriptionPortalObjectSubscriptionPortal SubscriptionPortalObject = "subscriptionPortal"
)

func (e SubscriptionPortalObject) ToPointer() *SubscriptionPortalObject {
	return &e
}
func (e *SubscriptionPortalObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "subscriptionPortal":
		*e = SubscriptionPortalObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SubscriptionPortalObject: %v", v)
	}
}

type SubscriptionPortal struct {
	Object SubscriptionPortalObject `json:"object"`
	// Portal link expiration timestamp in ISO 8601 format. Sample values: '2024-01-15T23:59:59Z', '2024-02-01T12:00:00Z'
	ExpiresAt time.Time `json:"expiresAt"`
	// Secure portal access URL for customer subscription management. Sample values: 'https://portal.paygentic.com/sub/abc123?token=xyz789', 'https://customer.example.com/portal/sub_456def'
	URL string `json:"url"`
}

func (s SubscriptionPortal) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionPortal) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionPortal) GetObject() SubscriptionPortalObject {
	if s == nil {
		return SubscriptionPortalObject("")
	}
	return s.Object
}

func (s *SubscriptionPortal) GetExpiresAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.ExpiresAt
}

func (s *SubscriptionPortal) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}
