// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type SubscriptionIntervalAddOpQuantityTransition struct {
	EffectiveDate time.Time `json:"effectiveDate"`
	// Non-negative decimal string.
	Quantity string `json:"quantity"`
}

func (s SubscriptionIntervalAddOpQuantityTransition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionIntervalAddOpQuantityTransition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionIntervalAddOpQuantityTransition) GetEffectiveDate() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.EffectiveDate
}

func (s *SubscriptionIntervalAddOpQuantityTransition) GetQuantity() string {
	if s == nil {
		return ""
	}
	return s.Quantity
}

type SubscriptionIntervalAddOpBillingMode string

const (
	SubscriptionIntervalAddOpBillingModeAdvance SubscriptionIntervalAddOpBillingMode = "advance"
	SubscriptionIntervalAddOpBillingModeArrears SubscriptionIntervalAddOpBillingMode = "arrears"
)

func (e SubscriptionIntervalAddOpBillingMode) ToPointer() *SubscriptionIntervalAddOpBillingMode {
	return &e
}
func (e *SubscriptionIntervalAddOpBillingMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "advance":
		fallthrough
	case "arrears":
		*e = SubscriptionIntervalAddOpBillingMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SubscriptionIntervalAddOpBillingMode: %v", v)
	}
}

// SubscriptionIntervalAddOp - Adds an interval. If the plan version has a line with this priceKey, the interval overrides that line. If not, send priceId. The interval then belongs to this subscription only and keeps the rate that you write. A plan version change does not carry it forward, so it stops billing at the version boundary. If a later plan version adds the same priceKey, the change is refused until the plan drops the key or the interval ends on or before the boundary.
type SubscriptionIntervalAddOp struct {
	// The price line that this interval bills. Use a priceKey from the plan version. A new key must start with a lowercase letter or a digit, use only lowercase letters, digits, hyphens, and underscores, and have 64 characters or fewer.
	PriceKey string `json:"priceKey"`
	// The catalog price to bill. Required if priceKey is not on the plan version. If it is on the plan, omit this field or send the price of that line. The price must belong to your merchant account.
	PriceID *string `json:"priceId,omitzero"`
	// Optional. If the subscription is on a different plan version, the request fails with 409.
	PlanVersionID *string `json:"planVersionId,omitzero"`
	// Signed net unit price for each period, as a decimal string. Null bills the catalog price. For a subscription-only interval, null saves the current catalog price.
	UnitPrice *string `json:"unitPrice"`
	// Quantity at interval start, as a non-negative decimal string.
	BaseQuantity string `json:"baseQuantity"`
	// Step changes in quantity partway through the interval.
	QuantityTransitions []SubscriptionIntervalAddOpQuantityTransition `json:"quantityTransitions,omitzero"`
	// ISO-8601 duration or 'one_off'
	BillingCadence string                               `json:"billingCadence"`
	BillingMode    SubscriptionIntervalAddOpBillingMode `json:"billingMode"`
	// Required when billingCadence is 'one_off'; must be absent otherwise.
	BillDate  optionalnullable.OptionalNullable[time.Time] `json:"billDate,omitzero"`
	StartDate time.Time                                    `json:"startDate"`
	// Null for an open-ended interval; when set, must be strictly after startDate.
	EndDate optionalnullable.OptionalNullable[time.Time] `json:"endDate,omitzero"`
}

func (s SubscriptionIntervalAddOp) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionIntervalAddOp) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionIntervalAddOp) GetPriceKey() string {
	if s == nil {
		return ""
	}
	return s.PriceKey
}

func (s *SubscriptionIntervalAddOp) GetPriceID() *string {
	if s == nil {
		return nil
	}
	return s.PriceID
}

func (s *SubscriptionIntervalAddOp) GetPlanVersionID() *string {
	if s == nil {
		return nil
	}
	return s.PlanVersionID
}

func (s *SubscriptionIntervalAddOp) GetUnitPrice() *string {
	if s == nil {
		return nil
	}
	return s.UnitPrice
}

func (s *SubscriptionIntervalAddOp) GetBaseQuantity() string {
	if s == nil {
		return ""
	}
	return s.BaseQuantity
}

func (s *SubscriptionIntervalAddOp) GetQuantityTransitions() []SubscriptionIntervalAddOpQuantityTransition {
	if s == nil {
		return nil
	}
	return s.QuantityTransitions
}

func (s *SubscriptionIntervalAddOp) GetBillingCadence() string {
	if s == nil {
		return ""
	}
	return s.BillingCadence
}

func (s *SubscriptionIntervalAddOp) GetBillingMode() SubscriptionIntervalAddOpBillingMode {
	if s == nil {
		return SubscriptionIntervalAddOpBillingMode("")
	}
	return s.BillingMode
}

func (s *SubscriptionIntervalAddOp) GetBillDate() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.BillDate
}

func (s *SubscriptionIntervalAddOp) GetStartDate() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.StartDate
}

func (s *SubscriptionIntervalAddOp) GetEndDate() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.EndDate
}
