// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type SubscriptionIntervalEditOpQuantityTransition struct {
	EffectiveDate time.Time `json:"effectiveDate"`
	// Non-negative decimal string.
	Quantity string `json:"quantity"`
}

func (s SubscriptionIntervalEditOpQuantityTransition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionIntervalEditOpQuantityTransition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionIntervalEditOpQuantityTransition) GetEffectiveDate() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.EffectiveDate
}

func (s *SubscriptionIntervalEditOpQuantityTransition) GetQuantity() string {
	if s == nil {
		return ""
	}
	return s.Quantity
}

// SubscriptionIntervalEditOpBillingMode - Not editable. Must match the interval's current value if supplied.
type SubscriptionIntervalEditOpBillingMode string

const (
	SubscriptionIntervalEditOpBillingModeAdvance SubscriptionIntervalEditOpBillingMode = "advance"
	SubscriptionIntervalEditOpBillingModeArrears SubscriptionIntervalEditOpBillingMode = "arrears"
)

func (e SubscriptionIntervalEditOpBillingMode) ToPointer() *SubscriptionIntervalEditOpBillingMode {
	return &e
}
func (e *SubscriptionIntervalEditOpBillingMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "advance":
		fallthrough
	case "arrears":
		*e = SubscriptionIntervalEditOpBillingMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SubscriptionIntervalEditOpBillingMode: %v", v)
	}
}

// SubscriptionIntervalEditOp - Edits an interval by id. You can change unitPrice, baseQuantity, quantityTransitions, and endDate. Other fields must match the current value if you send them. To bill a different priceId, remove the interval and add a new one.
type SubscriptionIntervalEditOp struct {
	// The interval being edited.
	ID string `json:"id"`
	// Signed per-period net unit price as a decimal string. Set to null to revert to the catalog price. Omit to leave unchanged.
	UnitPrice optionalnullable.OptionalNullable[string] `json:"unitPrice,omitzero"`
	// Quantity at interval start, as a non-negative decimal string. Omit to leave unchanged.
	BaseQuantity *string `json:"baseQuantity,omitzero"`
	// Step changes in quantity partway through the interval. Omit to leave unchanged.
	QuantityTransitions []SubscriptionIntervalEditOpQuantityTransition `json:"quantityTransitions,omitzero"`
	// Not editable. Must match the interval's current value if supplied.
	PriceID *string `json:"priceId,omitzero"`
	// Not editable. Must match the interval's current value if supplied.
	PriceKey *string `json:"priceKey,omitzero"`
	// Not editable. Must match the interval's current value if supplied.
	PlanVersionID *string `json:"planVersionId,omitzero"`
	// Not editable. Must match the interval's current value if supplied.
	BillingCadence *string `json:"billingCadence,omitzero"`
	// Not editable. Must match the interval's current value if supplied.
	BillingMode *SubscriptionIntervalEditOpBillingMode `json:"billingMode,omitzero"`
	// Not editable. Must match the interval's current value if supplied.
	BillDate optionalnullable.OptionalNullable[time.Time] `json:"billDate,omitzero"`
	// Not editable. Must match the interval's current value if supplied.
	StartDate *time.Time `json:"startDate,omitzero"`
	// When the interval stops billing. Send a date on or inside one of the billing periods to close the price. Send null to re-open it. Omit to keep the current value.
	EndDate optionalnullable.OptionalNullable[time.Time] `json:"endDate,omitzero"`
}

func (s SubscriptionIntervalEditOp) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionIntervalEditOp) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionIntervalEditOp) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SubscriptionIntervalEditOp) GetUnitPrice() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.UnitPrice
}

func (s *SubscriptionIntervalEditOp) GetBaseQuantity() *string {
	if s == nil {
		return nil
	}
	return s.BaseQuantity
}

func (s *SubscriptionIntervalEditOp) GetQuantityTransitions() []SubscriptionIntervalEditOpQuantityTransition {
	if s == nil {
		return nil
	}
	return s.QuantityTransitions
}

func (s *SubscriptionIntervalEditOp) GetPriceID() *string {
	if s == nil {
		return nil
	}
	return s.PriceID
}

func (s *SubscriptionIntervalEditOp) GetPriceKey() *string {
	if s == nil {
		return nil
	}
	return s.PriceKey
}

func (s *SubscriptionIntervalEditOp) GetPlanVersionID() *string {
	if s == nil {
		return nil
	}
	return s.PlanVersionID
}

func (s *SubscriptionIntervalEditOp) GetBillingCadence() *string {
	if s == nil {
		return nil
	}
	return s.BillingCadence
}

func (s *SubscriptionIntervalEditOp) GetBillingMode() *SubscriptionIntervalEditOpBillingMode {
	if s == nil {
		return nil
	}
	return s.BillingMode
}

func (s *SubscriptionIntervalEditOp) GetBillDate() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.BillDate
}

func (s *SubscriptionIntervalEditOp) GetStartDate() *time.Time {
	if s == nil {
		return nil
	}
	return s.StartDate
}

func (s *SubscriptionIntervalEditOp) GetEndDate() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.EndDate
}
