// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SubscriptionIntervalRemoveOp struct {
	// The interval being removed.
	ID string `json:"id"`
}

func (s *SubscriptionIntervalRemoveOp) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}
