// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SubscriptionIntervalChangesResponse struct {
	Data []SubscriptionIntervalChange `json:"data"`
	// Offset-based pagination response.
	Pagination OffsetPagination `json:"pagination"`
}

func (s *SubscriptionIntervalChangesResponse) GetData() []SubscriptionIntervalChange {
	if s == nil {
		return []SubscriptionIntervalChange{}
	}
	return s.Data
}

func (s *SubscriptionIntervalChangesResponse) GetPagination() OffsetPagination {
	if s == nil {
		return OffsetPagination{}
	}
	return s.Pagination
}
