// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

// SubscriptionIntervalChange - The record of one change to a subscription's price intervals: what changed, and why.
type SubscriptionIntervalChange struct {
	ID             string `json:"id"`
	MerchantID     string `json:"merchantId"`
	SubscriptionID string `json:"subscriptionId"`
	// Why a change was made. `correction` fixes data to match what was agreed; `migration` moves a contract from another system; `commercial` is a real change to the deal. Defaults to `unspecified`.
	ChangeReason ChangeReason `json:"changeReason"`
	Description  *string      `json:"description"`
	// Your own key-value data about the change, such as a CRM deal ID.
	Metadata  map[string]IntervalChangeMetadata `json:"metadata"`
	CreatedAt time.Time                         `json:"createdAt"`
	// One entry per interval the edit added, changed or removed.
	Intervals []SubscriptionIntervalChangeEntry `json:"intervals"`
}

func (s SubscriptionIntervalChange) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionIntervalChange) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionIntervalChange) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SubscriptionIntervalChange) GetMerchantID() string {
	if s == nil {
		return ""
	}
	return s.MerchantID
}

func (s *SubscriptionIntervalChange) GetSubscriptionID() string {
	if s == nil {
		return ""
	}
	return s.SubscriptionID
}

func (s *SubscriptionIntervalChange) GetChangeReason() ChangeReason {
	if s == nil {
		return ChangeReason("")
	}
	return s.ChangeReason
}

func (s *SubscriptionIntervalChange) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *SubscriptionIntervalChange) GetMetadata() map[string]IntervalChangeMetadata {
	if s == nil {
		return map[string]IntervalChangeMetadata{}
	}
	return s.Metadata
}

func (s *SubscriptionIntervalChange) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *SubscriptionIntervalChange) GetIntervals() []SubscriptionIntervalChangeEntry {
	if s == nil {
		return []SubscriptionIntervalChangeEntry{}
	}
	return s.Intervals
}
