// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

type SubscriptionAdjustmentObject string

const (
	SubscriptionAdjustmentObjectSubscriptionAdjustment SubscriptionAdjustmentObject = "subscriptionAdjustment"
)

func (e SubscriptionAdjustmentObject) ToPointer() *SubscriptionAdjustmentObject {
	return &e
}
func (e *SubscriptionAdjustmentObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "subscriptionAdjustment":
		*e = SubscriptionAdjustmentObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SubscriptionAdjustmentObject: %v", v)
	}
}

type SubscriptionAdjustmentType string

const (
	SubscriptionAdjustmentTypePercentageDiscount SubscriptionAdjustmentType = "percentageDiscount"
)

func (e SubscriptionAdjustmentType) ToPointer() *SubscriptionAdjustmentType {
	return &e
}
func (e *SubscriptionAdjustmentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "percentageDiscount":
		*e = SubscriptionAdjustmentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SubscriptionAdjustmentType: %v", v)
	}
}

type SubscriptionAdjustment struct {
	Object SubscriptionAdjustmentObject `json:"object"`
	// The adjustment ID
	ID string `json:"id"`
	// Unique identifier for a subscription
	SubscriptionID string                     `json:"subscriptionId"`
	Type           SubscriptionAdjustmentType `json:"type"`
	// The discount rate as a decimal fraction between 0 and 1. "0.35" means 35 percent.
	PercentageDiscount string `json:"percentageDiscount"`
	// The first instant the discount applies. Inclusive.
	EffectiveFrom time.Time `json:"effectiveFrom"`
	// The instant the discount stops applying. Exclusive. Null means the discount never stops.
	EffectiveTo *time.Time `json:"effectiveTo"`
	// The deal's own name, shown on each discount line of the invoice.
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
}

func (s SubscriptionAdjustment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionAdjustment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionAdjustment) GetObject() SubscriptionAdjustmentObject {
	if s == nil {
		return SubscriptionAdjustmentObject("")
	}
	return s.Object
}

func (s *SubscriptionAdjustment) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SubscriptionAdjustment) GetSubscriptionID() string {
	if s == nil {
		return ""
	}
	return s.SubscriptionID
}

func (s *SubscriptionAdjustment) GetType() SubscriptionAdjustmentType {
	if s == nil {
		return SubscriptionAdjustmentType("")
	}
	return s.Type
}

func (s *SubscriptionAdjustment) GetPercentageDiscount() string {
	if s == nil {
		return ""
	}
	return s.PercentageDiscount
}

func (s *SubscriptionAdjustment) GetEffectiveFrom() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.EffectiveFrom
}

func (s *SubscriptionAdjustment) GetEffectiveTo() *time.Time {
	if s == nil {
		return nil
	}
	return s.EffectiveTo
}

func (s *SubscriptionAdjustment) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *SubscriptionAdjustment) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}
