// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SubscriptionIntervalChangeEntry - One interval that the change added, edited or removed, with its state before and after.
type SubscriptionIntervalChangeEntry struct {
	IntervalID string `json:"intervalId"`
	// The interval before the edit. Null when the edit added it.
	Before *SubscriptionIntervalChangeCopy `json:"before"`
	// The interval after the edit. Null when the edit removed it.
	After *SubscriptionIntervalChangeCopy `json:"after"`
}

func (s *SubscriptionIntervalChangeEntry) GetIntervalID() string {
	if s == nil {
		return ""
	}
	return s.IntervalID
}

func (s *SubscriptionIntervalChangeEntry) GetBefore() *SubscriptionIntervalChangeCopy {
	if s == nil {
		return nil
	}
	return s.Before
}

func (s *SubscriptionIntervalChangeEntry) GetAfter() *SubscriptionIntervalChangeCopy {
	if s == nil {
		return nil
	}
	return s.After
}
