// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

type SubscriptionIntervalChangeCopyQuantityTransition struct {
	EffectiveDate time.Time `json:"effectiveDate"`
	Quantity      string    `json:"quantity"`
}

func (s SubscriptionIntervalChangeCopyQuantityTransition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionIntervalChangeCopyQuantityTransition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionIntervalChangeCopyQuantityTransition) GetEffectiveDate() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.EffectiveDate
}

func (s *SubscriptionIntervalChangeCopyQuantityTransition) GetQuantity() string {
	if s == nil {
		return ""
	}
	return s.Quantity
}

type SubscriptionIntervalChangeCopyBillingMode string

const (
	SubscriptionIntervalChangeCopyBillingModeAdvance SubscriptionIntervalChangeCopyBillingMode = "advance"
	SubscriptionIntervalChangeCopyBillingModeArrears SubscriptionIntervalChangeCopyBillingMode = "arrears"
)

func (e SubscriptionIntervalChangeCopyBillingMode) ToPointer() *SubscriptionIntervalChangeCopyBillingMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SubscriptionIntervalChangeCopyBillingMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "advance", "arrears":
			return true
		}
	}
	return false
}

// SubscriptionIntervalChangeCopy - What an interval billed at one point in time.
type SubscriptionIntervalChangeCopy struct {
	PriceID  string `json:"priceId"`
	PriceKey string `json:"priceKey"`
	// The plan version the interval belongs to.
	PlanVersionID string `json:"planVersionId"`
	// The rate as a decimal string, or null when the interval bills the catalog rate.
	UnitPrice *string `json:"unitPrice"`
	// The per-unit rate the interval charged when the change was made.
	ResolvedUnitPrice   string                                             `json:"resolvedUnitPrice"`
	BaseQuantity        string                                             `json:"baseQuantity"`
	QuantityTransitions []SubscriptionIntervalChangeCopyQuantityTransition `json:"quantityTransitions"`
	// ISO-8601 duration or 'one_off'
	BillingCadence string                                    `json:"billingCadence"`
	BillingMode    SubscriptionIntervalChangeCopyBillingMode `json:"billingMode"`
	// When a one-off interval bills. Null for every other cadence.
	BillDate  *time.Time `json:"billDate"`
	StartDate time.Time  `json:"startDate"`
	EndDate   *time.Time `json:"endDate"`
}

func (s SubscriptionIntervalChangeCopy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SubscriptionIntervalChangeCopy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SubscriptionIntervalChangeCopy) GetPriceID() string {
	if s == nil {
		return ""
	}
	return s.PriceID
}

func (s *SubscriptionIntervalChangeCopy) GetPriceKey() string {
	if s == nil {
		return ""
	}
	return s.PriceKey
}

func (s *SubscriptionIntervalChangeCopy) GetPlanVersionID() string {
	if s == nil {
		return ""
	}
	return s.PlanVersionID
}

func (s *SubscriptionIntervalChangeCopy) GetUnitPrice() *string {
	if s == nil {
		return nil
	}
	return s.UnitPrice
}

func (s *SubscriptionIntervalChangeCopy) GetResolvedUnitPrice() string {
	if s == nil {
		return ""
	}
	return s.ResolvedUnitPrice
}

func (s *SubscriptionIntervalChangeCopy) GetBaseQuantity() string {
	if s == nil {
		return ""
	}
	return s.BaseQuantity
}

func (s *SubscriptionIntervalChangeCopy) GetQuantityTransitions() []SubscriptionIntervalChangeCopyQuantityTransition {
	if s == nil {
		return []SubscriptionIntervalChangeCopyQuantityTransition{}
	}
	return s.QuantityTransitions
}

func (s *SubscriptionIntervalChangeCopy) GetBillingCadence() string {
	if s == nil {
		return ""
	}
	return s.BillingCadence
}

func (s *SubscriptionIntervalChangeCopy) GetBillingMode() SubscriptionIntervalChangeCopyBillingMode {
	if s == nil {
		return SubscriptionIntervalChangeCopyBillingMode("")
	}
	return s.BillingMode
}

func (s *SubscriptionIntervalChangeCopy) GetBillDate() *time.Time {
	if s == nil {
		return nil
	}
	return s.BillDate
}

func (s *SubscriptionIntervalChangeCopy) GetStartDate() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.StartDate
}

func (s *SubscriptionIntervalChangeCopy) GetEndDate() *time.Time {
	if s == nil {
		return nil
	}
	return s.EndDate
}
