// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/paygentic/sdk-go/internal/utils"
	"github.com/paygentic/sdk-go/optionalnullable"
	"time"
)

type TestClock struct {
	// Unique identifier for the test clock
	ID string `json:"id"`
	// When the test clock was created
	CreatedAt time.Time `json:"createdAt"`
	// The simulated current time of the test clock
	CurrentTime time.Time `json:"currentTime"`
	// When the test clock was deleted (if applicable)
	DeletedAt optionalnullable.OptionalNullable[time.Time] `json:"deletedAt,omitzero"`
	// Description of the test clock's purpose
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// The merchant organization that owns this test clock
	MerchantID string `json:"merchantId"`
	// Name of the test clock
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
	// When the test clock was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

func (t TestClock) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TestClock) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TestClock) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TestClock) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *TestClock) GetCurrentTime() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CurrentTime
}

func (t *TestClock) GetDeletedAt() optionalnullable.OptionalNullable[time.Time] {
	if t == nil {
		return nil
	}
	return t.DeletedAt
}

func (t *TestClock) GetDescription() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TestClock) GetMerchantID() string {
	if t == nil {
		return ""
	}
	return t.MerchantID
}

func (t *TestClock) GetName() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TestClock) GetUpdatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.UpdatedAt
}
