// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TransitionPlanVersionRequest - Sets this version as the plan's default.
type TransitionPlanVersionRequest struct {
	// Set to true to point the plan's default at this version. Idempotent on the already-default version.
	Default *bool `json:"default,omitzero"`
}

func (t *TransitionPlanVersionRequest) GetDefault() *bool {
	if t == nil {
		return nil
	}
	return t.Default
}
