// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
	"time"
)

type UsageResponseObject string

const (
	UsageResponseObjectMeter UsageResponseObject = "meter"
)

func (e UsageResponseObject) ToPointer() *UsageResponseObject {
	return &e
}
func (e *UsageResponseObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "meter":
		*e = UsageResponseObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UsageResponseObject: %v", v)
	}
}

type WindowedValue struct {
	WindowStart time.Time `json:"windowStart"`
	WindowEnd   time.Time `json:"windowEnd"`
	Value       float64   `json:"value"`
}

func (w WindowedValue) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WindowedValue) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WindowedValue) GetWindowStart() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.WindowStart
}

func (w *WindowedValue) GetWindowEnd() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.WindowEnd
}

func (w *WindowedValue) GetValue() float64 {
	if w == nil {
		return 0.0
	}
	return w.Value
}

type GroupedValue struct {
	GroupBy map[string]string `json:"groupBy"`
	Value   float64           `json:"value"`
	// Number of raw events in this group
	EventCount *int64 `json:"eventCount,omitzero"`
}

func (g *GroupedValue) GetGroupBy() map[string]string {
	if g == nil {
		return map[string]string{}
	}
	return g.GroupBy
}

func (g *GroupedValue) GetValue() float64 {
	if g == nil {
		return 0.0
	}
	return g.Value
}

func (g *GroupedValue) GetEventCount() *int64 {
	if g == nil {
		return nil
	}
	return g.EventCount
}

type UsageResponse struct {
	Object *UsageResponseObject `default:"meter" json:"object"`
	// Unique identifier for a billable metric
	BillableMetricID string `json:"billableMetricId"`
	// Total aggregated value across the query window
	TotalValue float64 `json:"totalValue"`
	// Time-bucketed values. Only present when windowSize is specified. When both windowSize and groupBy are set, windowedValues[i] is index-aligned with groupedValues[i] (same window and group).
	WindowedValues []WindowedValue `json:"windowedValues,omitzero"`
	// Dimension-grouped values. Only present when groupBy is specified. When both windowSize and groupBy are set, groupedValues[i] is index-aligned with windowedValues[i] (same window and group).
	GroupedValues []GroupedValue `json:"groupedValues,omitzero"`
	// Total distinct groups before groupLimit/groupOffset truncation. Only present when groupLimit is specified; use it to drive pagination totals.
	GroupCount *int64 `json:"groupCount,omitzero"`
}

func (u UsageResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UsageResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UsageResponse) GetObject() *UsageResponseObject {
	if u == nil {
		return nil
	}
	return u.Object
}

func (u *UsageResponse) GetBillableMetricID() string {
	if u == nil {
		return ""
	}
	return u.BillableMetricID
}

func (u *UsageResponse) GetTotalValue() float64 {
	if u == nil {
		return 0.0
	}
	return u.TotalValue
}

func (u *UsageResponse) GetWindowedValues() []WindowedValue {
	if u == nil {
		return nil
	}
	return u.WindowedValues
}

func (u *UsageResponse) GetGroupedValues() []GroupedValue {
	if u == nil {
		return nil
	}
	return u.GroupedValues
}

func (u *UsageResponse) GetGroupCount() *int64 {
	if u == nil {
		return nil
	}
	return u.GroupCount
}
