// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/sdk-go/internal/utils"
)

// ErrorEnum - Error type indicating validation failure
type ErrorEnum string

const (
	ErrorEnumValidationError ErrorEnum = "validation_error"
)

func (e ErrorEnum) ToPointer() *ErrorEnum {
	return &e
}
func (e *ErrorEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "validation_error":
		*e = ErrorEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ErrorEnum: %v", v)
	}
}

type Error struct {
	// The field that failed validation
	Field string `json:"field"`
	// Validation error message for this field
	Message string `json:"message"`
	// Validation error code
	Code *string `json:"code,omitzero"`
}

func (e Error) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Error) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *Error) GetField() string {
	if e == nil {
		return ""
	}
	return e.Field
}

func (e *Error) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *Error) GetCode() *string {
	if e == nil {
		return nil
	}
	return e.Code
}
