// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package errors

import (
	"encoding/json"
	"github.com/paygentic/sdk-go/models/operations"
)

// DeletePriceConflictError - Price cannot be deleted because a live plan still references it
type DeletePriceConflictError struct {
	Error_  *string                        `json:"error,omitzero"`
	Message *string                        `json:"message,omitzero"`
	Details *operations.DeletePriceDetails `json:"details,omitzero"`
}

var _ error = &DeletePriceConflictError{}

func (e *DeletePriceConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
