// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package errors

import (
	"encoding/json"
	"github.com/paygentic/sdk-go/models/operations"
)

// UpdatePriceConflictError - Price cannot be restructured because a subscription still bills it directly
type UpdatePriceConflictError struct {
	Error_  *string `json:"error,omitzero"`
	Message string  `json:"message"`
	// Machine-readable conflict code. Open set: a new code may appear, so branch on the ones you handle and treat anything else as an unhandled conflict.
	Code    string                         `json:"code"`
	Details *operations.UpdatePriceDetails `json:"details,omitzero"`
}

var _ error = &UpdatePriceConflictError{}

func (e *UpdatePriceConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
