workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Paygentic API:
        inputs:
            - location: registry.speakeasyapi.dev/paygentic/default/paygentic-api@$TAG
targets:
    go:
        target: go
        source: Paygentic API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/paygentic/default/paygentic-api-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
        testing:
            enabled: true
